// Generated by scripts/generate_bundled_userscripts.py — do not edit by hand.
// Source of truth: wBlockCoreService/BundledUserscripts/*.user.js

import Foundation

/// Userscripts that ship inside the wBlockCoreService framework rather than
/// being downloaded from a remote URL. Content is embedded verbatim so the
/// scripts work offline and update alongside the app.
enum BundledUserScriptSources {
    /// Embedded source of tube-cleaner.user.js.
    static let tubeCleaner = ###"""
// ==UserScript==
// @name         Tube Cleaner
// @namespace    com.skula.wblock
// @version      4.0.0
// @description  Replaces the YouTube player with a native HTML video element using YouTube's stream. Removes ads, restores picture-in-picture, keeps videos playing in background tabs, and adds an audio-only mode.
// @description:de  Ersetzt den YouTube-Player durch ein natives HTML-Videoelement mit YouTube-Stream. Entfernt Werbung, stellt Bild-in-Bild wieder her, hält Videos in Hintergrund-Tabs am Laufen und fügt einen Nur-Audio-Modus hinzu.
// @description:es  Reemplaza el reproductor de YouTube con un elemento de video HTML nativo usando el stream de YouTube. Elimina anuncios, restaura picture-in-picture, mantiene los videos reproduciéndose en segundo plano y añade un modo de solo audio.
// @description:fr  Remplace le lecteur YouTube par un élément vidéo HTML natif utilisant le flux YouTube. Supprime les publicités, restaure l'image dans l'image, garde les vidéos en lecture en arrière-plan et ajoute un mode audio seul.
// @description:it  Sostituisce il lettore YouTube con un elemento video HTML nativo usando lo stream YouTube. Rimuove gli annunci, ripristina picture-in-picture, mantiene i video in riproduzione in background e aggiunge una modalità solo audio.
// @description:pt-BR  Substitui o player do YouTube por um elemento de vídeo HTML nativo usando o stream do YouTube. Remove anúncios, restaura picture-in-picture, mantém vídeos em reprodução em segundo plano e adiciona modo somente áudio.
// @description:ja  YouTubeのプレーヤーをネイティブHTMLビデオ要素に置き換え、YouTubeのストリームを使用します。広告を削除し、ピクチャーインピクチャーを復元し、バックグラウンドタブで動画を再生し続け、オーディオのみのモードを追加します。
// @description:ko  YouTube 플레이어를 YouTube 스트림을 사용하는 네이티브 HTML 비디오 요소로 대체합니다. 광고를 제거하고, PIP를 복원하고, 백그라운드 탭에서 동영상 재생을 유지하고, 오디오 전용 모드를 추가합니다.
// @description:ru  Заменяет плеер YouTube на нативный HTML-видеоэлемент, использующий поток YouTube. Удаляет рекламу, восстанавливает картинку-в-картинке, продолжает воспроизведение в фоновых вкладках и добавляет режим только аудио.
// @description:zh-Hans  使用 YouTube 的流替换 YouTube 播放器为原生 HTML 视频元素。移除广告，恢复画中画，保持视频在后台标签页播放，并添加纯音频模式。
// @author       wBlock
// @match        https://www.youtube.com/*
// @match        https://m.youtube.com/*
// @match        https://music.youtube.com/*
// @match        https://www.youtube-nocookie.com/*
// @run-at       document-start
// @inject-into  page
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    // ------------------------------------------------------------------
    // Tube Cleaner v3.0.0
    //
    // Vinegar Extract approach: instead of trying to extract stream URLs
    // from the player response (which 403 due to SABR), we let YouTube's
    // player create and initialize the <video> element with its SABR/MSE
    // pipeline, then we repurpose that <video> element into a native
    // Safari player.
    //
    // How it works:
    //   1. Wait for YouTube's player to create a <video> element
    //   2. Detach it from YouTube's player container
    //   3. Insert it into a minimal native wrapper
    //   4. Enable Safari's native controls
    //   5. Hide YouTube's player chrome via CSS
    //   6. Ad blocking is handled by wBlock's content blocker
    //
    // This preserves full quality (SABR adaptive bitrate) while giving
    // the user a native Safari video experience.
    // ------------------------------------------------------------------

    var LOG_PREFIX = '[Tube Cleaner]';
    var STORAGE_AUDIO = 'wblock.tubeCleaner.audioOnly';
    var STORAGE_QUALITY = 'wblock.tubeCleaner.quality';
    var ATTR_CLEANED = 'data-wblock-tc-cleaned';

    var debug = true;

    function log() {
        if (!debug) return;
        try { console.log.apply(console, [LOG_PREFIX].concat([].slice.call(arguments))); }
        catch (e) { /* ignore */ }
    }

    function warn() {
        try { console.warn.apply(console, [LOG_PREFIX].concat([].slice.call(arguments))); }
        catch (e) { /* ignore */ }
    }

    // ------------------------------------------------------------------
    // iOS / iPadOS detection
    // ------------------------------------------------------------------

    // iPadOS requesting the desktop site reports "MacIntel" with touch support;
    // the ontouchstart check keeps real Macs (trackpads) from matching.
    var IS_IOS = /iPad|iPhone|iPod/.test(navigator.userAgent) ||
        (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1 &&
         typeof document.documentElement.ontouchstart !== 'undefined');
    var IS_MOBILE_SITE = location.hostname === 'm.youtube.com' ||
        /mobi|android/i.test(navigator.userAgent);

    // ------------------------------------------------------------------
    // Auto PiP
    // ------------------------------------------------------------------

    var AUTO_PIP_KEY = 'wblock.tubeCleaner.autoPiP';
    var autoPiPEnabled = true;
    var pipActive = false;

    function getAutoPiP() {
        try {
            var stored = localStorage.getItem(AUTO_PIP_KEY);
            return stored === null ? true : stored === '1';
        } catch (e) { return true; }
    }

    function setAutoPiP(v) {
        try { localStorage.setItem(AUTO_PIP_KEY, v ? '1' : '0'); } catch (e) { /* ignore */ }
        autoPiPEnabled = v;
    }

    try { autoPiPEnabled = getAutoPiP(); } catch (e) { /* ignore */ }

    function isPiPActive(video) {
        return document.pictureInPictureElement === video ||
            (video && video.webkitPresentationMode === 'picture-in-picture');
    }

    function enterPiP(video) {
        if (!video || !autoPiPEnabled) return;
        if (isPiPActive(video)) return;
        if (video.paused || video.ended) return;
        try {
            if (video.webkitSupportsPresentationMode &&
                typeof video.webkitSetPresentationMode === 'function') {
                video.webkitSetPresentationMode('picture-in-picture');
                log('PiP entered');
            } else if (video.requestPictureInPicture) {
                video.requestPictureInPicture();
                log('PiP entered via API');
            }
        } catch (e) { warn('enterPiP failed', e); }
    }

    function exitPiP(video) {
        if (!video) return;
        if (!isPiPActive(video)) return;
        try {
            if (video.webkitSupportsPresentationMode &&
                typeof video.webkitSetPresentationMode === 'function') {
                video.webkitSetPresentationMode('inline');
                log('PiP exited');
            } else if (document.pictureInPictureElement) {
                document.exitPictureInPicture();
            }
        } catch (e) { warn('exitPiP failed', e); }
    }

    function setupAutoPiP(video) {
        if (!video || video._wblockAutoPiPHooked) return;
        video._wblockAutoPiPHooked = true;

        // Tab switch: enter PiP when tab hides, exit when visible.
        // Note: enableBackgroundPlayback() overrides document.hidden to always
        // return false, so we use _realHidden which tracks the true state.
        function onVisibilityChange() {
            if (!autoPiPEnabled) return;
            if (_realHidden) {
                if (!video.paused && !video.ended) {
                    enterPiP(video);
                }
            } else {
                if (document.hasFocus() && isPiPActive(video)) {
                    exitPiP(video);
                }
            }
        }

        // Window blur: enter PiP when switching to another app
        function onBlur() {
            if (!autoPiPEnabled) return;
            if (_realHidden) return; // already handled by visibilitychange
            setTimeout(function () {
                if (document.hasFocus()) return; // focus moved within document
                if (!video.paused && !video.ended) {
                    enterPiP(video);
                }
            }, 100);
        }

        function onFocus() {
            if (!autoPiPEnabled) return;
            if (_realHidden) return;
            if (document.hasFocus() && isPiPActive(video)) {
                exitPiP(video);
            }
        }

        document.addEventListener('visibilitychange', onVisibilityChange);
        window.addEventListener('blur', onBlur);
        window.addEventListener('focus', onFocus);

        // Scroll out of view: use IntersectionObserver
        var scrollObserver = new IntersectionObserver(function (entries) {
            if (!autoPiPEnabled) return;
            entries.forEach(function (entry) {
                if (!entry.isIntersecting && !video.paused && !video.ended) {
                    enterPiP(video);
                } else if (entry.isIntersecting && isPiPActive(video)) {
                    exitPiP(video);
                }
            });
        }, { threshold: 0.1 });
        scrollObserver.observe(video);

        // Listen for presentation mode changes
        function onPresentationModeChange() {
            log('presentation mode changed:', video.webkitPresentationMode);
        }
        video.addEventListener('webkitpresentationmodechanged', onPresentationModeChange);

        // Release all of the above when this video is superseded, so listeners
        // and observers do not accumulate across SPA navigations.
        registerCleanup(function () {
            document.removeEventListener('visibilitychange', onVisibilityChange);
            window.removeEventListener('blur', onBlur);
            window.removeEventListener('focus', onFocus);
            try { scrollObserver.disconnect(); } catch (e) { /* ignore */ }
            video.removeEventListener('webkitpresentationmodechanged', onPresentationModeChange);
        });
    }

    // ------------------------------------------------------------------
    // Preferences
    // ------------------------------------------------------------------

    function isAudioOnly() {
        try { return localStorage.getItem(STORAGE_AUDIO) === '1'; } catch (e) { return false; }
    }

    function setAudioOnly(v) {
        try { localStorage.setItem(STORAGE_AUDIO, v ? '1' : '0'); } catch (e) { /* ignore */ }
    }

    function getPreferredQuality() {
        try { return localStorage.getItem(STORAGE_QUALITY) || 'auto'; } catch (e) { return 'auto'; }
    }

    function setPreferredQuality(q) {
        try { localStorage.setItem(STORAGE_QUALITY, q); } catch (e) { /* ignore */ }
    }

    // ------------------------------------------------------------------
    // CSS injected into the page
    // ------------------------------------------------------------------

    var STYLE_ID = 'wblock-tc-style';

    var CSS = [
        // Hide YouTube's player chrome entirely. The native <video>
        // element gets its own controls from Safari.
        '#movie_player .ytp-chrome-top,',
        '#movie_player .ytp-chrome-bottom,',
        '#movie_player .ytp-gradient-top,',
        '#movie_player .ytp-gradient-bottom,',
        '#movie_player .ytp-title,',
        '#movie_player .ytp-pip-button,',
        '#movie_player .ytp-chrome-controls,',
        '#movie_player .ytp-right-controls,',
        '#movie_player .ytp-left-controls,',
        '#movie_player .ytp-play-button,',
        '#movie_player .ytp-volume-area,',
        '#movie_player .ytp-time-display,',
        '#movie_player .ytp-progress-bar,',
        '#movie_player .ytp-progress-bar-container,',
        '#movie_player .ytp-settings-button,',
        '#movie_player .ytp-fullscreen-button,',
        '#movie_player .ytp-remote-button,',
        '#movie_player .ytp-size-button,',
        '#movie_player .ytp-subtitles-button,',
        '#movie_player .ytp-autonav-endscreen-button,',
        '#movie_player .ytp-share-button,',
        '#movie_player .ytp-watch-later-button,',
        '#movie_player .ytp-menuitem,',
        // Storyboard scrubbing preview
        '.ytp-storyboard-framepreview,',
        '.ytp-tooltip,',
        // Ad overlays
        '.ytp-ad-module,',
        '.video-ads,',
        '#player-ads,',
        '.ytp-ad-overlay-container,',
        '.ytp-ad-overlay-slot,',
        '.ytp-ad-image-overlay,',
        '.ytp-ad-overlay-image,',
        '.ytp-ad-badge,',
        // Annotations, cards, end screen
        '.ytp-ce-element,',
        '.ytp-cards-teaser,',
        '.iv-branding,',
        '.ytp-ce-covering-overlay,',
        '.ytp-ce-cover,',
        // Pause overlay
        '.ytp-pause-overlay,',
        // Autoplay countdown
        '.ytp-autonav-endscreen-countdown-overlay,',
        '.ytp-autonav-toggle-button-container,',
        // Info panel
        '.ytp-video-info-panel,',
        // Channel watermark
        '.ytp-watermark,',
        // Related videos overlay
        '.ytp-related-overlay,',
        // Large play button in center
        '.ytp-large-play-button,',
        // Unplayable text
        '.ytp-error,',
        // Spoiler overlay
        '.ytp-spoiler-overlay',
        '{ display: none !important; }',

        // Make the video container fully transparent so only the
        // native <video> element shows through.
        '#movie_player .html5-video-player,',
        '#movie_player',
        '{ background: transparent !important; }',

        // Remove padding/margins that YouTube adds for its controls.
        '#movie_player .html5-video-container',
        '{ position: static !important; }',

        // Let the video fill the container.
        '#movie_player video',
        '{ width: 100% !important; height: 100% !important; }',

        // Hide the YouTube player container's custom cursor.
        '#movie_player',
        '{ cursor: default !important; }',

        // Hide the "Youtube" link in the player.
        '.ytp-youtube-button,',
        '.ytp-title-link',
        '{ display: none !important; }',

        // Ensure the player container doesn't clip our toolbar.
        '#movie_player',
        '{ overflow: visible !important; }',

        // Toolbar is hidden by default, appears on hover near bottom.
        // '.wblock-tc-toolbar',
        // '{ opacity: 1 !important; display: flex !important; }',

        // Ensure the native controls bar is visible on the video.
        // YouTube's player often sets the video to be a child of
        // elements with overflow:hidden or pointer-events:none.
        '.wblock-tc-native video',
        '{ display: block !important; }',

        // Ensure Safari's native media controls show up.
        '.wblock-tc-native video::-webkit-media-controls',
        '{ display: flex !important; opacity: 1 !important; visibility: visible !important; }',

        '.wblock-tc-native video::-webkit-media-controls-panel',
        '{ display: flex !important; opacity: 1 !important; }',

        // Make sure the video container allows native controls to
        // render by removing overflow hidden.
        '#movie_player .html5-video-container',
        '{ overflow: visible !important; }',

        // Let the native controls bar extend below the video.
        '.wblock-tc-native',
        '{ overflow: visible !important; }',

        // Prevent iOS double-tap zoom on toolbar buttons.
        '.wblock-tc-toolbar button, .wblock-tc-toolbar div',
        '{ touch-action: manipulation !important; }',
    ].join(' ');

    var AUDIO_ONLY_CSS = [
        '.wblock-tc-native video,',
        '.wblock-tc-native .html5-video-container',
        '{ visibility: hidden !important; }'
    ].join(' ');

    function injectStyles() {
        if (document.getElementById(STYLE_ID)) { return; }
        var style = document.createElement('style');
        style.id = STYLE_ID;
        style.textContent = CSS;
        if (document.head) {
            document.head.appendChild(style);
        } else {
            document.documentElement.appendChild(style);
        }
    }

    function setAudioOnlyStyles(enabled) {
        var id = STYLE_ID + '-audio';
        var existing = document.getElementById(id);
        if (enabled && !existing) {
            var style = document.createElement('style');
            style.id = id;
            style.textContent = AUDIO_ONLY_CSS;
            (document.head || document.documentElement).appendChild(style);
        } else if (!enabled && existing) {
            existing.remove();
        }
    }

    // ------------------------------------------------------------------
    // Background playback
    // ------------------------------------------------------------------

    // Track real visibility state separately since we override document.hidden
    var _realHidden = false;
    var _realVisibility = 'visible';

    document.addEventListener('visibilitychange', function () {
        // Store the real state before it gets overridden
        try {
            _realHidden = document.hidden;
            _realVisibility = document.visibilityState;
        } catch (e) { /* ignore */ }
    });

    // Also capture the initial state
    try {
        _realHidden = document.hidden;
        _realVisibility = document.visibilityState;
    } catch (e) { /* ignore */ }

    function enableBackgroundPlayback() {
        try {
            Object.defineProperty(document, 'hidden', {
                get: function () { return false; },
                configurable: true
            });
        } catch (e) { /* ignore */ }
        try {
            Object.defineProperty(document, 'visibilityState', {
                get: function () { return 'visible'; },
                configurable: true
            });
        } catch (e) { /* ignore */ }
    }

    // ------------------------------------------------------------------
    // Core: extract the <video> from YouTube's player and make it native
    // ------------------------------------------------------------------

    var currentState = null;

    // ------------------------------------------------------------------
    // Per-video resource tracking
    //
    // YouTube is a single-page app. Navigating between videos (or the player
    // recreating its <video> element) used to leak resources: each new video
    // added more document/window listeners, MutationObservers, and setInterval
    // timers without removing the previous video's. We track the active video's
    // teardown callbacks and run them before activating a new video, so resource
    // counts stay flat no matter how many videos play in a session.
    // ------------------------------------------------------------------

    var activeVideo = null;
    var playerObserver = null;
    var activeCleanups = [];

    function registerCleanup(fn) {
        activeCleanups.push(fn);
    }

    function releaseActiveVideo() {
        var cleanups = activeCleanups;
        activeCleanups = [];
        for (var i = 0; i < cleanups.length; i++) {
            try { cleanups[i](); } catch (e) { /* ignore */ }
        }
        activeVideo = null;
    }

    // Intercept addEventListener on the video to drop only YouTube's
    // tracking/hijacking listeners, not the essential playback events the player
    // needs to manage the stream. We keep YouTube's own <video> element (cloning
    // would lose the SABR/MSE source buffers and cause 403s).
    function patchVideoListeners(video) {
        if (video._wblockPatched) return;
        video._wblockPatched = true;
        var origAdd = video.addEventListener.bind(video);
        video.addEventListener = function (type, listener, options) {
            var blocked = [
                'timeupdate', 'progress', 'waiting', 'stalled',
                'suspend', 'abort', 'emptied'
            ];
            if (blocked.indexOf(type) !== -1) {
                return; // silently drop tracking
            }
            return origAdd(type, listener, options);
        };
    }

    // Activate a video element: tear down the previous video's resources first,
    // then apply every per-video enhancement. Called on first transform and again
    // whenever the player recreates its <video> element.
    function activateVideo(player, video) {
        releaseActiveVideo();
        activeVideo = video;
        forceNativeControls(video);
        guardNativeControls(video);
        video.removeAttribute('disablepictureinpicture');
        video.disablePictureInPicture = false;
        ensurePlaysInline(video);
        patchVideoListeners(video);
        buildToolbar(player, video);
        setupAutoPiP(video);
    }

    function forceNativeControls(video) {
        // YouTube's player actively sets controls=false.  We intercept
        // the property setter to prevent that.  Safari's native controls
        // bar will then stay visible.
        if (video._wblockControlsPatched) return;
        video._wblockControlsPatched = true;

        video.controls = true;

        // Intercept the 'controls' property so YouTube can't turn it off
        try {
            Object.defineProperty(video, 'controls', {
                get: function () { return true; },
                set: function (v) { /* ignore YouTube's attempts to disable */ },
                configurable: false
            });
        } catch (e) {
            // If it fails (e.g. already defined), just try again periodically
        }

        // Also set the attribute directly in case YouTube uses setAttribute
        video.setAttribute('controls', '');
    }

    // WebKit renders Safari's native controls from the video's `controls`
    // CONTENT ATTRIBUTE, not from the JavaScript property. forceNativeControls()
    // shadows the `controls` property so YouTube's `video.controls = false`
    // assignments are ignored, but YouTube can still strip the attribute via
    // removeAttribute(), which hides the native controls. A naive
    // `!video.controls` guard never fires there because the shadowed getter
    // always returns true. So we defend the attribute itself: a MutationObserver
    // restores it whenever it is removed, with a polling fallback.
    function guardNativeControls(video) {
        if (!video || video._wblockControlsGuarded) return;
        video._wblockControlsGuarded = true;

        function restore() {
            if (video && !video.hasAttribute('controls')) {
                video.setAttribute('controls', '');
            }
        }

        var observer = null;
        try {
            observer = new MutationObserver(restore);
            observer.observe(video, { attributes: true, attributeFilter: ['controls'] });
        } catch (e) { /* ignore */ }

        restore();
        var timer = setInterval(restore, 1000);

        registerCleanup(function () {
            if (observer) { try { observer.disconnect(); } catch (e) { /* ignore */ } }
            clearInterval(timer);
        });
    }

    // Ensure inline playback on iOS/iPadOS. Without `playsinline`, iOS opens the
    // video in the fullscreen system player instead of playing inline. YouTube's
    // desktop player (served to iPadOS by default) may omit this attribute, and
    // since we reuse YouTube's <video> element we must set it ourselves.
    function ensurePlaysInline(video) {
        if (!video) return;
        try {
            video.playsInline = true;
            video.setAttribute('playsinline', '');
            video.setAttribute('webkit-playsinline', '');
        } catch (e) { /* ignore */ }
    }

    function transformPlayer() {
        var player = document.getElementById('movie_player');
        if (!player) {
            player = document.querySelector('.html5-video-player');
            if (!player) return;
        }

        var video = player.querySelector('video');
        if (!video) return;

        // Check if we already processed this video
        var videoId = '';
        try {
            var params = new URLSearchParams(location.search);
            videoId = params.get('v') || '';
        } catch (e) { /* ignore */ }

        if (player.getAttribute(ATTR_CLEANED) === videoId) return;
        player.setAttribute(ATTR_CLEANED, videoId);

        log('transforming player for', videoId || '(unknown)');

        // 1. Mark the video as native by adding a wrapper class
        player.classList.add('wblock-tc-native');

        // 2-5. Apply all per-video enhancements (native controls, PiP/inline
        // attrs, listener patching, controls guard, toolbar, auto-PiP).
        // activateVideo first tears down the previous video's resources so
        // nothing leaks across SPA navigations.
        activateVideo(player, video);

        // 6. Apply audio-only preference
        setAudioOnlyStyles(isAudioOnly());

        // 7. Enable background playback
        enableBackgroundPlayback();

        // 6. Apply preferred quality (deferred — let the player finish init)
        setTimeout(function () {
            applyPreferredQuality();
        }, 3000);

        // 7. Observe for video element recreation. The player element persists
        // across SPA navigations, so disconnect any previous observer before
        // creating a new one to avoid accumulating observers.
        if (playerObserver) {
            try { playerObserver.disconnect(); } catch (e) { /* ignore */ }
        }
        playerObserver = new MutationObserver(function () {
            var newVid = player.querySelector('video');
            if (newVid && newVid !== activeVideo) {
                log('re-patching new video element');
                activateVideo(player, newVid);
            }
        });
        playerObserver.observe(player, { childList: true, subtree: true });

        log('player transformed');
    }

    // ------------------------------------------------------------------
    // Quality control via YouTube's internal player UI
    // ------------------------------------------------------------------

    // YouTube's quality labels match quality strings
    var QUALITY_LABELS = {
        auto: 'Auto',
        hd2160: '4K',
        hd1440: '1440p',
        hd1080: '1080p',
        hd720: '720p',
        large: '480p',
        medium: '360p',
        small: '240p',
        tiny: '144p'
    };

    // Ordered from highest to lowest (excluding 'auto')
    var QUALITY_ORDER = [
        'hd2160', 'hd1440', 'hd1080', 'hd720',
        'large', 'medium', 'small', 'tiny'
    ];

    function getAvailableQualities() {
        var player = document.getElementById('movie_player');
        if (!player || !player.getAvailableQualityLevels) return [];
        var levels = player.getAvailableQualityLevels();
        if (!levels || !levels.length) return [];
        // levels is ordered highest-first, may include 'auto'
        return levels.filter(function (q) { return q && q !== 'auto'; });
    }

    function getCurrentQuality() {
        var player = document.getElementById('movie_player');
        if (!player || !player.getPlaybackQuality) return 'auto';
        var q = player.getPlaybackQuality();
        return q || 'auto';
    }

    // Click YouTube's internal settings button to open the quality menu
    function openSettingsMenu(player) {
        var settingsBtn = player.querySelector('.ytp-settings-button') ||
            player.querySelector('[aria-label="Settings"]') ||
            player.querySelector('.ytp-button[aria-label*="Settings"]');
        if (!settingsBtn) { warn('openSettings: no settings button'); return false; }
        // Click it twice to ensure it opens (first click closes, second opens)
        settingsBtn.click();
        settingsBtn.click();
        return true;
    }

    // Find the quality menu item in the settings panel
    function clickQualityMenuItem(player) {
        var menuItems = player.querySelectorAll('.ytp-menuitem');
        for (var i = 0; i < menuItems.length; i++) {
            var item = menuItems[i];
            var content = item.querySelector('.ytp-menuitem-content');
            if (content && content.textContent && content.textContent.match(/\d{3,}/)) {
                // This is the quality menu item (has resolution numbers)
                item.click();
                return true;
            }
        }
        // Alternative: look for the label
        for (var j = 0; j < menuItems.length; j++) {
            var label = menuItems[j].querySelector('.ytp-menuitem-label');
            if (label && label.textContent && label.textContent.toLowerCase().indexOf('quality') !== -1) {
                menuItems[j].click();
                return true;
            }
        }
        return false;
    }

    // Click a specific quality option in the quality submenu
    function clickQualityOption(player, target) {
        var targetLabel = QUALITY_LABELS[target] || target;
        // Try to find by quality label text (e.g. "1080p", "720p")
        var allOptions = player.querySelectorAll('.ytp-quality-menu .ytp-menuitem, ' +
            '.ytp-drop-down-menu-button, ' +
            '[role="menuitemradio"]');

        // Also try the panel menu items
        var panelItems = player.querySelectorAll('.ytp-panel-menu .ytp-menuitem');

        // Look for the label that matches our target
        var items = [];
        for (var i = 0; i < panelItems.length; i++) items.push(panelItems[i]);

        // Sort: prefer exact match, then partial match
        var bestMatch = null;
        var bestScore = -1;
        for (var j = 0; j < items.length; j++) {
            var text = items[j].textContent || '';
            var score = 0;
            if (text.indexOf(targetLabel) !== -1) score = 2;
            else if (text.indexOf(target) !== -1) score = 1;
            if (score > bestScore) {
                bestScore = score;
                bestMatch = items[j];
            }
        }

        if (bestMatch && bestScore > 0) {
            log('clicking quality option:', bestMatch.textContent);
            bestMatch.click();
            return true;
        }

        return false;
    }

    // Close the settings panel
    function closeSettingsPanel(player) {
        var backBtn = player.querySelector('.ytp-panel-header button');
        if (backBtn) {
            backBtn.click();
            return true;
        }
        // Click the settings button again to toggle it closed
        var settingsBtn = player.querySelector('.ytp-settings-button');
        if (settingsBtn) {
            settingsBtn.click();
        }
        return false;
    }

    function setQuality(target) {
        var player = document.getElementById('movie_player');
        if (!player) { warn('setQuality: no player'); return false; }

        if (target === 'auto') {
            // Reset to auto by setting a wide range via API
            if (player.setPlaybackQualityRange) {
                try { player.setPlaybackQualityRange('tiny', 'hd2160'); } catch (e) { /* ignore */ }
            }
            return true;
        }

        var levels = getAvailableQualities();
        if (levels.indexOf(target) === -1) {
            // Target not available, pick the closest lower quality
            var targetIdx = QUALITY_ORDER.indexOf(target);
            for (var i = targetIdx + 1; i < QUALITY_ORDER.length; i++) {
                if (levels.indexOf(QUALITY_ORDER[i]) !== -1) {
                    target = QUALITY_ORDER[i];
                    break;
                }
            }
        }

        log('setQuality:', target, 'available:', levels);

        var worked = false;

        // Approach 1: Simulate clicks on YouTube's quality UI (most reliable)
        // This is what YouTube Auto HD does and it works on the SABR player.
        try {
            if (openSettingsMenu(player)) {
                setTimeout(function () {
                    if (clickQualityMenuItem(player)) {
                        setTimeout(function () {
                            if (clickQualityOption(player, target)) {
                                worked = true;
                                log('UI click approach succeeded for', target);
                            }
                            // Close the settings panel
                            setTimeout(function () {
                                closeSettingsPanel(player);
                            }, 100);
                        }, 200);
                    } else {
                        // If we can't find the quality menu, close settings
                        closeSettingsPanel(player);
                    }
                }, 200);
            }
        } catch (e) { warn('UI click approach failed', e); }

        // Approach 2: setPlaybackQualityRange (may work on non-SABR players)
        if (player.setPlaybackQualityRange) {
            try {
                log('calling setPlaybackQualityRange', target, target);
                player.setPlaybackQualityRange(target, target);
                worked = true;
            } catch (e) { /* ignore */ }
        }

        // Approach 3: setPlaybackQuality (older API — no-op on SABR)
        if (player.setPlaybackQuality) {
            try {
                log('calling setPlaybackQuality', target);
                player.setPlaybackQuality(target);
            } catch (e) { /* ignore */ }
        }

        // Approach 4: set the yt-player-quality in localStorage as a bias
        try {
            localStorage.setItem('yt-player-quality', JSON.stringify({
                quality: target,
                previousQuality: 'auto',
                expiry: Date.now() + 86400000
            }));
        } catch (e) { /* ignore */ }

        log('setQuality complete, UI click:', worked);
        return worked;
    }

    function applyPreferredQuality() {
        var preferred = getPreferredQuality();
        if (preferred === 'auto') return;
        // Retry a few times — the player may not be fully ready
        var attempts = 0;
        var timer = setInterval(function () {
            attempts++;
            var current = getCurrentQuality();
            if (current === preferred || attempts > 10) {
                clearInterval(timer);
                return;
            }
            setQuality(preferred);
        }, 500);
    }

    // ------------------------------------------------------------------
    // Toolbar overlay (quality, audio-only, PiP)
    // ------------------------------------------------------------------

    function buildToolbar(player, video) {
        var existing = player.querySelector('.wblock-tc-toolbar');
        if (existing) {
            if (existing._wblockQualityTimer) clearInterval(existing._wblockQualityTimer);
            existing.remove();
        }

        var toolbar = document.createElement('div');
        toolbar.className = 'wblock-tc-toolbar';
        // Position at bottom-right, above native controls. Always visible but
        // semi-transparent, full opacity on hover.
        // On mobile (iOS/iPadOS) use larger touch targets and always-visible.
        var toolbarBottom = IS_IOS ? '12px' : '42px';
        var toolbarOpacity = IS_IOS ? '1' : '0.75';
        var toolbarFont = IS_IOS ? '14px' : '11px';
        toolbar.style.cssText = 'position:absolute;bottom:' + toolbarBottom + ';right:8px;z-index:60;display:flex;gap:6px;align-items:center;pointer-events:auto;font:' + toolbarFont + '/1.2 -apple-system,system-ui,sans-serif;opacity:' + toolbarOpacity + ';transition:opacity 0.15s';

        var btnStyle = 'background:rgba(0,0,0,0.7);color:#fff;border:none;border-radius:4px;padding:3px 8px;font-size:11px;cursor:pointer;-webkit-user-select:none;user-select:none';
        // On iOS, use larger touch targets (minimum 44pt)
        if (IS_IOS) {
            btnStyle = 'background:rgba(0,0,0,0.7);color:#fff;border:none;border-radius:6px;padding:8px 12px;font-size:14px;cursor:pointer;-webkit-user-select:none;user-select:none';
        }

        // Quality selector
        var qualityBtn = document.createElement('button');
        qualityBtn.type = 'button';
        qualityBtn.style.cssText = btnStyle;
        function updateQualityBtn() {
            var current = getCurrentQuality();
            var label = QUALITY_LABELS[current] || current;
            qualityBtn.textContent = label;
            qualityBtn.title = 'Video quality (click to change)';
        }
        updateQualityBtn();

        // Quality dropdown — opens upward since toolbar is at bottom
        var qualityMenu = document.createElement('div');
        var menuFont = IS_IOS ? '16px' : '12px';
        var menuPadding = IS_IOS ? '8px 0' : '4px 0';
        var menuMinWidth = IS_IOS ? '140px' : '100px';
        qualityMenu.style.cssText = 'position:absolute;bottom:100%;right:0;margin-bottom:4px;background:rgba(0,0,0,0.9);border-radius:5px;padding:' + menuPadding + ';min-width:' + menuMinWidth + ';display:none;z-index:70;font:' + menuFont + '/1.8 -apple-system,system-ui,sans-serif';

        function buildQualityMenu() {
            // Clear safely — avoid innerHTML which triggers TrustedHTML CSP
            while (qualityMenu.firstChild) {
                qualityMenu.removeChild(qualityMenu.firstChild);
            }
            var levels = getAvailableQualities();
            var preferred = getPreferredQuality();

            var itemPadding = IS_IOS ? '10px 16px' : '4px 12px';

            // Auto option
            var autoItem = document.createElement('div');
            autoItem.style.cssText = 'padding:' + itemPadding + ';cursor:pointer;color:#fff;white-space:nowrap';
            autoItem.textContent = 'Auto';
            if (preferred === 'auto') {
                autoItem.style.color = '#4fc3f7';
            }
            autoItem.addEventListener('click', function (e) {
                e.stopPropagation();
                setPreferredQuality('auto');
                setQuality('auto');
                updateQualityBtn();
                qualityMenu.style.display = 'none';
            });
            autoItem.addEventListener('mouseenter', function () { this.style.background = 'rgba(255,255,255,0.15)'; });
            autoItem.addEventListener('mouseleave', function () { this.style.background = ''; });
            qualityMenu.appendChild(autoItem);

            // Available quality levels
            for (var i = 0; i < levels.length; i++) {
                (function (q) {
                    var item = document.createElement('div');
                    item.style.cssText = 'padding:' + itemPadding + ';cursor:pointer;color:#fff;white-space:nowrap';
                    item.textContent = QUALITY_LABELS[q] || q;
                    if (preferred === q) {
                        item.style.color = '#4fc3f7';
                    }
                    item.addEventListener('click', function (e) {
                        e.stopPropagation();
                        setPreferredQuality(q);
                        setQuality(q);
                        updateQualityBtn();
                        qualityMenu.style.display = 'none';
                    });
                    item.addEventListener('mouseenter', function () { this.style.background = 'rgba(255,255,255,0.15)'; });
                    item.addEventListener('mouseleave', function () { this.style.background = ''; });
                    qualityMenu.appendChild(item);
                })(levels[i]);
            }
        }

        qualityBtn.addEventListener('click', function (e) {
            e.stopPropagation();
            if (qualityMenu.style.display === 'none') {
                buildQualityMenu();
                qualityMenu.style.display = 'block';
            } else {
                qualityMenu.style.display = 'none';
            }
        });

        // Close menu on outside click
        document.addEventListener('click', function () {
            qualityMenu.style.display = 'none';
        });

        var qualityWrap = document.createElement('div');
        qualityWrap.style.cssText = 'position:relative';
        qualityWrap.appendChild(qualityBtn);
        qualityWrap.appendChild(qualityMenu);
        toolbar.appendChild(qualityWrap);

        // Update quality label periodically. Store the timer on the toolbar so
        // it can be cleared when the toolbar is rebuilt (avoids a leak across
        // video-element re-creation).
        toolbar._wblockQualityTimer = setInterval(updateQualityBtn, 2000);

        // Audio-only toggle
        var audioBtn = document.createElement('button');
        audioBtn.type = 'button';
        audioBtn.style.cssText = btnStyle;
        function updateAudioBtn() {
            audioBtn.textContent = isAudioOnly() ? 'Video' : 'Audio';
            audioBtn.title = isAudioOnly() ? 'Switch to video mode' : 'Switch to audio-only mode';
        }
        updateAudioBtn();
        audioBtn.addEventListener('click', function (e) {
            e.stopPropagation();
            var next = !isAudioOnly();
            setAudioOnly(next);
            setAudioOnlyStyles(next);
            updateAudioBtn();
        });
        toolbar.appendChild(audioBtn);

        // PiP button is intentionally omitted — Safari's native controls
        // already provide PiP. Auto PiP handles automatic PiP entry.

        // On iOS / iPadOS: hide by default, show on tap, auto-hide after
        // a few seconds (same behavior as Safari's native controls).
        if (IS_IOS) {
            toolbar.style.opacity = '0';
            toolbar.style.pointerEvents = 'none';

            var iosToolbarTimer = null;

            function showToolbarIOS() {
                toolbar.style.opacity = '1';
                toolbar.style.pointerEvents = 'auto';
                clearTimeout(iosToolbarTimer);
                iosToolbarTimer = setTimeout(function () {
                    toolbar.style.opacity = '0';
                    toolbar.style.pointerEvents = 'none';
                }, 4000);
            }

            // Show on tap anywhere on the player
            player.addEventListener('touchstart', showToolbarIOS, { passive: true });

            // Also show on play/pause (user tapped the native controls)
            video.addEventListener('play', showToolbarIOS);
            video.addEventListener('pause', showToolbarIOS);

            // Keep visible while tapping directly on toolbar buttons
            toolbar.addEventListener('touchstart', function (e) {
                e.stopPropagation();
                clearTimeout(iosToolbarTimer);
            }, { passive: true });

            // Hide after a timeout when a toolbar button is tapped
            toolbar.addEventListener('click', function () {
                clearTimeout(iosToolbarTimer);
                iosToolbarTimer = setTimeout(function () {
                    toolbar.style.opacity = '0';
                    toolbar.style.pointerEvents = 'none';
                }, 4000);
            });
        } else {
            // Start hidden on desktop — it appears with native controls
            toolbar.style.opacity = '0';
            toolbar.style.pointerEvents = 'none';

            var toolbarTimer = null;
            var TOOLBAR_HIDE_DELAY = 3000;

            function showToolbar() {
                toolbar.style.opacity = '1';
                toolbar.style.pointerEvents = 'auto';
                clearTimeout(toolbarTimer);
            }

            function hideToolbar() {
                toolbar.style.opacity = '0';
                toolbar.style.pointerEvents = 'none';
            }

            function scheduleHideToolbar() {
                clearTimeout(toolbarTimer);
                toolbarTimer = setTimeout(hideToolbar, TOOLBAR_HIDE_DELAY);
            }

            // Listen for mouse movement anywhere on the player to show
            // toolbar (same trigger as Safari's native controls)
            //
            // We use a document-level mousemove listener and check if
            // the mouse is over the player area. This is more reliable
            // than listening on the player element because YouTube's
            // overlay divs (html5-video-container, etc.) sit on top and
            // can intercept mouse events.
            var _isOverPlayer = false;
            document.addEventListener('mousemove', function (e) {
                var rect = player.getBoundingClientRect();
                var over = e.clientX >= rect.left && e.clientX <= rect.right &&
                    e.clientY >= rect.top && e.clientY <= rect.bottom;
                if (over && !_isOverPlayer) {
                    _isOverPlayer = true;
                    showToolbar();
                }
                if (over) {
                    scheduleHideToolbar();
                }
                if (!over && _isOverPlayer) {
                    _isOverPlayer = false;
                    scheduleHideToolbar();
                }
            });

            // Also show on mouse entering the player from outside
            player.addEventListener('mouseenter', function () {
                showToolbar();
            });

            // Keep visible while hovering directly over toolbar
            toolbar.addEventListener('mouseenter', function () {
                showToolbar();
                clearTimeout(toolbarTimer);
            });

            toolbar.addEventListener('mouseleave', function () {
                scheduleHideToolbar();
            });

            // Show on keyboard focus (tab navigation)
            toolbar.addEventListener('focusin', function () {
                showToolbar();
            });

            // Hide when video starts playing (controls auto-hide)
            video.addEventListener('play', function () {
                scheduleHideToolbar();
            });

            // Show when video is paused
            video.addEventListener('pause', function () {
                showToolbar();
            });

            // Show toolbar briefly when entering PiP (user can interact)
            video.addEventListener('webkitpresentationmodechanged', function () {
                if (video.webkitPresentationMode === 'picture-in-picture') {
                    showToolbar();
                    setTimeout(hideToolbar, 3000);
                }
            });
        }

        // Show on CSS class toggle (for keyboard shortcuts)
        toolbar.classList.add('wblock-tc-toolbar-built');

        player.appendChild(toolbar);
    }

    // ------------------------------------------------------------------
    // SPA navigation handling
    // ------------------------------------------------------------------

    var lastUrl = '';

    function onNavigate() {
        if (location.href === lastUrl) return;
        lastUrl = location.href;

        var player = document.getElementById('movie_player') ||
            document.querySelector('.html5-video-player');
        if (player) {
            player.removeAttribute(ATTR_CLEANED);
            player.classList.remove('wblock-tc-native');
        }

        // Try to transform at intervals
        setTimeout(transformPlayer, 500);
        setTimeout(transformPlayer, 1500);
        setTimeout(transformPlayer, 3000);
    }

    function watchNavigation() {
        document.addEventListener('yt-navigate-finish', onNavigate, true);
        try {
            document.addEventListener('yt-page-data-updated', onNavigate, true);
        } catch (e) { /* ignore */ }
        window.addEventListener('popstate', onNavigate, true);
        // Poll for URL changes as a fallback
        setInterval(function () {
            if (location.href !== lastUrl) onNavigate();
        }, 1000);
    }

    // ------------------------------------------------------------------
    // Boot
    // ------------------------------------------------------------------

    function waitForPlayer() {
        var started = Date.now();
        var timer = setInterval(function () {
            var player = document.getElementById('movie_player') ||
                document.querySelector('.html5-video-player');
            // On mobile YouTube, the player may be in a different container
            if (!player && IS_MOBILE_SITE) {
                player = document.querySelector('ytd-player') ||
                    document.querySelector('#player-container');
            }
            var video = player && player.querySelector('video');
            if (player && video) {
                clearInterval(timer);
                transformPlayer();
            } else if (Date.now() - started > 15000) {
                clearInterval(timer);
                warn('timed out waiting for player');
            }
        }, 250);
    }

    function boot() {
        // Inject CSS immediately
        injectStyles();
        enableBackgroundPlayback();

        lastUrl = location.href;
        watchNavigation();
        waitForPlayer();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', boot);
    } else {
        boot();
    }

    // Expose debug helpers on window for console testing
    try {
        window.__wblockTubeDebug = {
            getAvailableQualities: getAvailableQualities,
            getCurrentQuality: getCurrentQuality,
            setQuality: setQuality,
            getPreferredQuality: getPreferredQuality,
            setPreferredQuality: setPreferredQuality,
            QUALITY_LABELS: QUALITY_LABELS,
            getPlayer: function () { return document.getElementById('movie_player'); },
            inspectPlayer: function () {
                var p = document.getElementById('movie_player');
                if (!p) return 'no player';
                var methods = [];
                for (var k in p) {
                    if (typeof p[k] === 'function' && k.indexOf('playback') !== -1 || k.indexOf('Quality') !== -1) {
                        methods.push(k);
                    }
                }
                return {
                    methods: methods,
                    hasGetAvailableQualityLevels: typeof p.getAvailableQualityLevels === 'function',
                    hasGetAvailableQualityData: typeof p.getAvailableQualityData === 'function',
                    hasSetPlaybackQualityRange: typeof p.setPlaybackQualityRange === 'function',
                    hasSetPlaybackQuality: typeof p.setPlaybackQuality === 'function',
                    hasGetPlaybackQuality: typeof p.getPlaybackQuality === 'function',
                    levels: typeof p.getAvailableQualityLevels === 'function' ? p.getAvailableQualityLevels() : 'N/A',
                    qualityData: typeof p.getAvailableQualityData === 'function' ? p.getAvailableQualityData() : 'N/A',
                    current: typeof p.getPlaybackQuality === 'function' ? p.getPlaybackQuality() : 'N/A'
                };
            }
        };
        log('debug helpers exposed at window.__wblockTubeDebug');
    } catch (e) { /* ignore */ }
})();
"""###

    /// Embedded source of player-cleaner.user.js.
    static let playerCleaner = ###"""
// ==UserScript==
// @name         Player Cleaner
// @namespace    com.skula.wblock
// @version      1.1.0
// @description  Replaces custom video players on websites (other than YouTube) with a clean HTML5 video element, restoring native controls, Picture-in-Picture, auto PiP, and background playback. Disable it per site from the wBlock toolbar if a player misbehaves.
// @description:de  Ersetzt benutzerdefinierte Video-Player auf Websites (außer YouTube) durch ein sauberes HTML5-Videoelement und stellt native Steuerelemente, Bild-in-Bild, automatisches PiP und Hintergrundwiedergabe wieder her. Deaktivieren Sie ihn bei Problemen pro Website in der wBlock-Symbolleiste.
// @description:es  Reemplaza los reproductores de vídeo personalizados en sitios web (distintos de YouTube) con un elemento de vídeo HTML5 limpio, restaurando los controles nativos, Picture-in-Picture, PiP automático y reproducción en segundo plano. Desactívelo por sitio desde la barra de herramientas de wBlock si un reproductor falla.
// @description:fr  Remplace les lecteurs vidéo personnalisés des sites web (autres que YouTube) par un élément vidéo HTML5 propre, en restaurant les commandes natives, l'image dans l'image, le PiP automatique et la lecture en arrière-plan. Désactivez-le par site depuis la barre d'outils wBlock si un lecteur se comporte mal.
// @description:it  Sostituisce i lettori video personalizzati sui siti web (diversi da YouTube) con un elemento video HTML5 pulito, ripristinando i controlli nativi, Picture-in-Picture, PiP automatico e riproduzione in background. Disattivalo per sito dalla barra degli strumenti di wBlock se un lettore non funziona.
// @description:pt-BR  Substitui players de vídeo personalizados em sites (diferentes do YouTube) por um elemento de vídeo HTML5 limpo, restaurando os controles nativos, Picture-in-Picture, PiP automático e reprodução em segundo plano. Desative-o por site na barra de ferramentas do wBlock se um player se comportar mal.
// @description:ja  YouTube以外のWebサイトのカスタム動画プレーヤーをクリーンなHTML5 video要素に置き換え、ネイティブコントロール、ピクチャー・イン・ピクチャー、自動PiP、バックグラウンド再生を復元します。プレーヤーが誤動作する場合は、wBlockツールバーからサイトごとに無効にできます。
// @description:ko  YouTube 이외의 웹사이트에서 사용자 지정 동영상 플레이어를 깨끗한 HTML5 video 요소로 대체하여 네이티브 컨트롤, PIP, 자동 PIP, 백그라운드 재생을 복원합니다. 플레이어가 오작동하면 wBlock 도구 막대에서 사이트별로 비활성화하세요.
// @description:ru  Заменяет пользовательские видеоплееры на сайтах (кроме YouTube) чистым HTML5-элементом video, восстанавливая нативные элементы управления, картинку-в-картинке, автоматический PiP и фоновое воспроизведение. Отключите его для сайта на панели wBlock, если плеер работает некорректно.
// @description:zh-Hans  将网站（YouTube 除外）上的自定义视频播放器替换为干净的 HTML5 video 元素，恢复原生控件、画中画、自动画中画和后台播放。如果某个播放器出现问题，可从 wBlock 工具栏按网站停用。
// @author       wBlock
// @match        http://*/*
// @match        https://*/*
// @exclude      https://www.youtube.com/*
// @exclude      https://m.youtube.com/*
// @exclude      https://music.youtube.com/*
// @exclude      https://www.youtube-nocookie.com/*
// @run-at       document-idle
// @inject-into  page
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    // ------------------------------------------------------------------
    // Player Cleaner
    //
    // Many sites wrap a perfectly good HTML5 <video> in a custom player
    // (video.js, JW Player, Plyr, Flowplayer, MediaElement, Clappr, ...)
    // whose chrome hides native controls and breaks Picture-in-Picture.
    // This script finds those players, resolves the underlying media source
    // where possible, and swaps in a clean native <video>. When the source
    // is an opaque media-source blob we instead enhance the existing video
    // in place so playback keeps working with native controls.
    //
    // Features:
    //   - Custom player detection & replacement (video.js, JW, Plyr, ...)
    //   - Auto PiP: enters PiP on tab switch, window blur, scroll out of view
    //   - Background playback: keeps playing in background tabs
    //   - iOS toolbar: hidden by default, shows on tap, auto-hides
    //
    // YouTube is excluded; Tube Cleaner handles it. Per-site disabling is
    // provided by wBlock's userscript site settings.
    // ------------------------------------------------------------------

    var LOG_PREFIX = '[Player Cleaner]';
    var ATTR_DONE = 'data-wblock-player-cleaner';

    var IS_IOS = /iPad|iPhone|iPod/.test(navigator.userAgent) ||
        (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);

    // ------------------------------------------------------------------
    // Background playback — keep videos playing in background tabs
    // ------------------------------------------------------------------

    var _realHidden = false;
    var _realVisibility = 'visible';

    // Capture real visibility state before we override document.hidden
    try {
        _realHidden = document.hidden;
        _realVisibility = document.visibilityState;
    } catch (e) { /* ignore */ }

    document.addEventListener('visibilitychange', function () {
        try {
            _realHidden = document.hidden;
            _realVisibility = document.visibilityState;
        } catch (e) { /* ignore */ }
    });

    function enableBackgroundPlayback() {
        try {
            Object.defineProperty(document, 'hidden', {
                get: function () { return false; },
                configurable: true
            });
        } catch (e) { /* ignore */ }
        try {
            Object.defineProperty(document, 'visibilityState', {
                get: function () { return 'visible'; },
                configurable: true
            });
        } catch (e) { /* ignore */ }
    }

    // ------------------------------------------------------------------
    // Auto PiP — automatic Picture-in-Picture
    // ------------------------------------------------------------------

    var AUTO_PIP_KEY = 'wblock.playerCleaner.autoPiP';
    var autoPiPEnabled = true;

    function getAutoPiP() {
        try {
            var stored = localStorage.getItem(AUTO_PIP_KEY);
            return stored === null ? true : stored === '1';
        } catch (e) { return true; }
    }

    function setAutoPiP(v) {
        try { localStorage.setItem(AUTO_PIP_KEY, v ? '1' : '0'); } catch (e) { /* ignore */ }
        autoPiPEnabled = v;
    }

    try { autoPiPEnabled = getAutoPiP(); } catch (e) { /* ignore */ }

    function isPiPActive(video) {
        return document.pictureInPictureElement === video ||
            (video && video.webkitPresentationMode === 'picture-in-picture');
    }

    function enterPiP(video) {
        if (!video || !autoPiPEnabled) return;
        if (isPiPActive(video)) return;
        if (video.paused || video.ended) return;
        try {
            if (video.webkitSupportsPresentationMode &&
                typeof video.webkitSetPresentationMode === 'function') {
                video.webkitSetPresentationMode('picture-in-picture');
            } else if (video.requestPictureInPicture) {
                video.requestPictureInPicture();
            }
        } catch (e) { /* ignore */ }
    }

    function exitPiP(video) {
        if (!video) return;
        if (!isPiPActive(video)) return;
        try {
            if (video.webkitSupportsPresentationMode &&
                typeof video.webkitSetPresentationMode === 'function') {
                video.webkitSetPresentationMode('inline');
            } else if (document.pictureInPictureElement) {
                document.exitPictureInPicture();
            }
        } catch (e) { /* ignore */ }
    }

    function setupAutoPiP(video) {
        if (!video || video._wblockAutoPiPHooked) return;
        video._wblockAutoPiPHooked = true;

        // Tab switch: enter PiP when tab hides, exit when visible
        document.addEventListener('visibilitychange', function () {
            if (!autoPiPEnabled) return;
            if (_realHidden) {
                if (!video.paused && !video.ended) {
                    enterPiP(video);
                }
            } else {
                if (document.hasFocus() && isPiPActive(video)) {
                    exitPiP(video);
                }
            }
        });

        // Window blur: enter PiP when switching to another app
        window.addEventListener('blur', function () {
            if (!autoPiPEnabled) return;
            if (_realHidden) return;
            setTimeout(function () {
                if (document.hasFocus()) return;
                if (!video.paused && !video.ended) {
                    enterPiP(video);
                }
            }, 100);
        });

        window.addEventListener('focus', function () {
            if (!autoPiPEnabled) return;
            if (_realHidden) return;
            if (document.hasFocus() && isPiPActive(video)) {
                exitPiP(video);
            }
        });

        // Scroll out of view
        var scrollObserver = new IntersectionObserver(function (entries) {
            if (!autoPiPEnabled) return;
            entries.forEach(function (entry) {
                if (!entry.isIntersecting && !video.paused && !video.ended) {
                    enterPiP(video);
                } else if (entry.isIntersecting && isPiPActive(video)) {
                    exitPiP(video);
                }
            });
        }, { threshold: 0.1 });
        scrollObserver.observe(video);
    }

    function log() {
        try {
            if (window.__wblockPlayerCleanerDebug) {
                console.log.apply(console, [LOG_PREFIX].concat([].slice.call(arguments)));
            }
        } catch (e) { /* ignore */ }
    }

    // Player container selectors for the common custom-player libraries.
    var PLAYER_SELECTORS = [
        '.video-js',                 // video.js
        '.vjs-tech',                 // video.js (inner tech, handled via parent)
        '.jwplayer',                 // JW Player
        '.jw-wrapper',               // JW Player
        '.plyr',                     // Plyr
        '.flowplayer',               // Flowplayer
        '.mejs-container',           // MediaElement.js
        '.mejs__container',          // MediaElement.js (newer)
        '.clappr',                   // Clappr
        '[data-clappr-player]',      // Clappr
        '.hlsjs',                    // hls.js wrappers
        '.fluid_video_wrapper',      // Fluid Player
        '.fp-player'                 // Flowplayer (inner)
    ];

    function isHttpUrl(value) {
        return typeof value === 'string' && /^https?:\/\//i.test(value);
    }

    function isPlayableUrl(value) {
        if (!isHttpUrl(value)) { return false; }
        // Prefer obviously-playable media; allow plain http(s) too since many
        // sites serve mp4/m3u8 from extensionless CDN URLs.
        return true;
    }

    // ------------------------------------------------------------------
    // Source discovery
    // ------------------------------------------------------------------

    function sourceFromVideoElement(video) {
        try {
            if (isHttpUrl(video.currentSrc)) { return video.currentSrc; }
            if (isHttpUrl(video.src) && video.src.indexOf('blob:') !== 0) { return video.src; }
            var sources = video.getElementsByTagName('source');
            for (var i = 0; i < sources.length; i++) {
                var src = sources[i].getAttribute('src');
                if (isHttpUrl(src)) { return src; }
            }
        } catch (e) { /* ignore */ }
        return null;
    }

    function sourceFromDom(container) {
        try {
            // Data attributes commonly used to hold the media URL.
            var candidates = container.querySelectorAll('[data-src],[data-video-src],[data-file],[data-video],[data-source],[data-url]');
            var attrs = ['data-src', 'data-video-src', 'data-file', 'data-video', 'data-source', 'data-url'];
            for (var i = 0; i < candidates.length; i++) {
                for (var a = 0; a < attrs.length; a++) {
                    var value = candidates[i].getAttribute(attrs[a]);
                    if (isPlayableUrl(value)) { return value; }
                }
            }
            var direct = container.getAttribute('data-src') || container.getAttribute('data-file') ||
                container.getAttribute('data-video-src');
            if (isPlayableUrl(direct)) { return direct; }
        } catch (e) { /* ignore */ }
        return null;
    }

    function sourceFromVideojs(container) {
        try {
            if (!window.videojs) { return null; }
            var players = window.videojs.getPlayers ? window.videojs.getPlayers() : {};
            for (var id in players) {
                var player = players[id];
                if (!player) { continue; }
                try {
                    var el = player.el ? player.el() : null;
                    if (el && (container.contains(el) || el.contains(container))) {
                        var current = player.currentSource ? player.currentSource() : null;
                        if (current && isPlayableUrl(current.src)) { return current.src; }
                        var list = player.currentSources ? player.currentSources() : [];
                        for (var i = 0; i < list.length; i++) {
                            if (isPlayableUrl(list[i].src)) { return list[i].src; }
                        }
                    }
                } catch (e) { /* keep looking */ }
            }
        } catch (e) { /* ignore */ }
        return null;
    }

    function sourceFromJwPlayer(container) {
        try {
            if (!window.jwplayer) { return null; }
            var instance = window.jwplayer(container.id || container);
            if (!instance) { return null; }
            var item = instance.getPlaylistItem ? instance.getPlaylistItem() : null;
            if (item) {
                if (isPlayableUrl(item.file)) { return item.file; }
                var sources = item.sources || [];
                for (var i = 0; i < sources.length; i++) {
                    if (isPlayableUrl(sources[i].file)) { return sources[i].file; }
                }
            }
        } catch (e) { /* ignore */ }
        return null;
    }

    function sourceFromPageMetadata() {
        try {
            var selectors = [
                'meta[property="og:video:secure_url"]',
                'meta[property="og:video:url"]',
                'meta[property="og:video"]',
                'meta[name="twitter:player:stream"]'
            ];
            for (var i = 0; i < selectors.length; i++) {
                var el = document.querySelector(selectors[i]);
                var content = el ? el.getAttribute('content') : null;
                if (isPlayableUrl(content)) { return content; }
            }
        } catch (e) { /* ignore */ }
        return null;
    }

    function discoverSource(container, video) {
        return sourceFromVideoElement(video) ||
            sourceFromVideojs(container) ||
            sourceFromJwPlayer(container) ||
            sourceFromDom(container) ||
            null;
    }

    // ------------------------------------------------------------------
    // Replacement
    // ------------------------------------------------------------------

    function copyRelevantAttributes(fromVideo, toVideo) {
        var attrs = ['poster', 'title', 'preload', 'loop', 'muted', 'autoplay'];
        for (var i = 0; i < attrs.length; i++) {
            var name = attrs[i];
            var value = fromVideo.getAttribute(name);
            if (value !== null) {
                try { toVideo.setAttribute(name, value); } catch (e) { /* ignore */ }
            }
        }
        // Carry over <track> elements (captions/subtitles).
        try {
            var tracks = fromVideo.getElementsByTagName('track');
            for (var t = 0; t < tracks.length; t++) {
                toVideo.appendChild(tracks[t].cloneNode(true));
            }
        } catch (e) { /* ignore */ }
    }

    function buildCleanVideo(src, originalVideo) {
        var video = document.createElement('video');
        video.controls = true;
        video.playsInline = true;
        video.setAttribute('playsinline', '');
        video.setAttribute('webkit-playsinline', '');
        video.removeAttribute('disablepictureinpicture');
        video.disablePictureInPicture = false;
        video.style.width = '100%';
        video.style.height = '100%';
        video.style.background = '#000';
        if (originalVideo) { copyRelevantAttributes(originalVideo, video); }
        if (src) { video.src = src; }
        return video;
    }

    function normalizeContainer(raw) {
        // Some selectors match inner elements; climb to the outermost player
        // wrapper so we replace the whole custom chrome, not just part of it.
        var container = raw;
        var wrapperSelectors = ['.video-js', '.jwplayer', '.jw-wrapper', '.plyr',
            '.flowplayer', '.mejs-container', '.mejs__container', '.clappr',
            '[data-clappr-player]', '.fluid_video_wrapper'];
        for (var i = 0; i < wrapperSelectors.length; i++) {
            var ancestor = container.closest ? container.closest(wrapperSelectors[i]) : null;
            if (ancestor) { container = ancestor; }
        }
        return container;
    }

    function forceNativeControls(video) {
        if (video._wblockControlsPatched) return;
        video._wblockControlsPatched = true;
        video.controls = true;
        try {
            Object.defineProperty(video, 'controls', {
                get: function () { return true; },
                set: function (v) { /* ignore */ },
                configurable: false
            });
        } catch (e) { /* ignore */ }
        video.setAttribute('controls', '');
    }

    // WebKit renders native controls from the `controls` CONTENT ATTRIBUTE, not
    // the JavaScript property. forceNativeControls() shadows the property so
    // `video.controls = false` is ignored, but a player can still strip the
    // attribute via removeAttribute(), hiding the controls. A `!video.controls`
    // guard never fires because the shadowed getter always returns true. So we
    // defend the attribute itself: a MutationObserver restores it whenever it is
    // removed, with a polling fallback.
    function guardNativeControls(video) {
        if (!video || video._wblockControlsGuarded) return;
        video._wblockControlsGuarded = true;

        function restore() {
            if (video && !video.hasAttribute('controls')) {
                video.setAttribute('controls', '');
            }
        }

        try {
            var observer = new MutationObserver(restore);
            observer.observe(video, { attributes: true, attributeFilter: ['controls'] });
        } catch (e) { /* ignore */ }

        restore();
        setInterval(restore, 1000);
    }

    function enhanceInPlace(container, video) {
        // We could not resolve a clean source (opaque MSE blob). Keep the
        // existing video playing but expose native controls + PiP and remove
        // obvious custom control overlays.
        try {
            forceNativeControls(video);
            video.playsInline = true;
            video.setAttribute('playsinline', '');
            video.removeAttribute('disablepictureinpicture');
            video.disablePictureInPicture = false;
        } catch (e) { /* ignore */ }

        setupAutoPiP(video);

        var overlaySelectors = [
            '.vjs-control-bar', '.vjs-big-play-button', '.vjs-poster',
            '.jw-controls', '.jw-display-icon-container',
            '.plyr__controls', '.fp-ui', '.fp-header',
            '.mejs-controls', '.mejs__controls',
            '.clappr-media-control'
        ];
        for (var i = 0; i < overlaySelectors.length; i++) {
            var overlays = container.querySelectorAll(overlaySelectors[i]);
            for (var j = 0; j < overlays.length; j++) {
                try { overlays[j].style.display = 'none'; } catch (e) { /* ignore */ }
            }
        }

        // Keep controls forced on
        guardNativeControls(video);
    }

    function replacePlayer(container) {
        if (container.getAttribute && container.getAttribute(ATTR_DONE)) { return; }
        var video = container.querySelector ? container.querySelector('video') : null;
        if (!video) { return; }
        if (video.getAttribute && video.getAttribute(ATTR_DONE)) { return; }

        var src = discoverSource(container, video);
        log('player detected', container.className, 'source:', src ? 'resolved' : 'opaque');

        enableBackgroundPlayback();

        if (src) {
            var clean = buildCleanVideo(src, video);
            clean.setAttribute(ATTR_DONE, '1');
            // Replace the container's contents with the clean video, keeping
            // the container itself so page layout/sizing still applies.
            while (container.firstChild) { container.removeChild(container.firstChild); }
            container.appendChild(clean);
            try {
                container.classList.remove('video-js', 'vjs-paused', 'vjs-playing');
            } catch (e) { /* ignore */ }
            container.setAttribute(ATTR_DONE, '1');
            forceNativeControls(clean);
            setupAutoPiP(clean);

            // Keep controls forced on
            guardNativeControls(clean);
        } else {
            video.setAttribute(ATTR_DONE, '1');
            container.setAttribute(ATTR_DONE, '1');
            enhanceInPlace(container, video);
        }
    }

    // ------------------------------------------------------------------
    // Scanning
    // ------------------------------------------------------------------

    function scan(root) {
        var scope = root || document;
        var seen = [];
        for (var i = 0; i < PLAYER_SELECTORS.length; i++) {
            var nodes;
            try { nodes = scope.querySelectorAll(PLAYER_SELECTORS[i]); }
            catch (e) { continue; }
            for (var j = 0; j < nodes.length; j++) {
                var container = normalizeContainer(nodes[j]);
                if (!container || seen.indexOf(container) !== -1) { continue; }
                seen.push(container);
                try { replacePlayer(container); }
                catch (e) { log('replace failed', e); }
            }
        }
    }

    function observe() {
        if (typeof MutationObserver === 'undefined') { return; }
        var scheduled = false;
        var observer = new MutationObserver(function () {
            if (scheduled) { return; }
            scheduled = true;
            setTimeout(function () {
                scheduled = false;
                scan(document);
            }, 500);
        });
        try {
            observer.observe(document.documentElement, { childList: true, subtree: true });
        } catch (e) { /* ignore */ }
    }

    function boot() {
        scan(document);
        // Players often mount after idle; rescan a few times then observe.
        setTimeout(function () { scan(document); }, 800);
        setTimeout(function () { scan(document); }, 2000);
        observe();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', boot, { once: true });
    } else {
        boot();
    }
})();
"""###

}
