// Generated by scripts/generate_bundled_userscripts.py — do not edit by hand.
// Source of truth: wBlockCoreService/BundledUserscripts/*.user.js

import Foundation

/// Userscripts that ship inside the wBlockCoreService framework rather than
/// being downloaded from a remote URL. Content is embedded verbatim so the
/// scripts work offline and update alongside the app.
enum BundledUserScriptSources {
    /// Embedded source of tube-cleaner.user.js.
    static let tubeCleaner = ###"""
// ==UserScript==
// @name         Tube Cleaner
// @namespace    com.skula.wblock
// @version      3.0.0
// @description  Replaces the YouTube player with a native HTML video element using YouTube's stream. Removes ads, restores picture-in-picture, keeps videos playing in background tabs, and adds an audio-only mode.
// @description:de  Ersetzt den YouTube-Player durch ein natives HTML-Videoelement mit YouTube-Stream. Entfernt Werbung, stellt Bild-in-Bild wieder her, hält Videos in Hintergrund-Tabs am Laufen und fügt einen Nur-Audio-Modus hinzu.
// @description:es  Reemplaza el reproductor de YouTube con un elemento de video HTML nativo usando el stream de YouTube. Elimina anuncios, restaura picture-in-picture, mantiene los videos reproduciéndose en segundo plano y añade un modo de solo audio.
// @description:fr  Remplace le lecteur YouTube par un élément vidéo HTML natif utilisant le flux YouTube. Supprime les publicités, restaure l'image dans l'image, garde les vidéos en lecture en arrière-plan et ajoute un mode audio seul.
// @description:it  Sostituisce il lettore YouTube con un elemento video HTML nativo usando lo stream YouTube. Rimuove gli annunci, ripristina picture-in-picture, mantiene i video in riproduzione in background e aggiunge una modalità solo audio.
// @description:pt-BR  Substitui o player do YouTube por um elemento de vídeo HTML nativo usando o stream do YouTube. Remove anúncios, restaura picture-in-picture, mantém vídeos em reprodução em segundo plano e adiciona modo somente áudio.
// @description:ja  YouTubeのプレーヤーをネイティブHTMLビデオ要素に置き換え、YouTubeのストリームを使用します。広告を削除し、ピクチャーインピクチャーを復元し、バックグラウンドタブで動画を再生し続け、オーディオのみのモードを追加します。
// @description:ko  YouTube 플레이어를 YouTube 스트림을 사용하는 네이티브 HTML 비디오 요소로 대체합니다. 광고를 제거하고, PIP를 복원하고, 백그라운드 탭에서 동영상 재생을 유지하고, 오디오 전용 모드를 추가합니다.
// @description:ru  Заменяет плеер YouTube на нативный HTML-видеоэлемент, использующий поток YouTube. Удаляет рекламу, восстанавливает картинку-в-картинке, продолжает воспроизведение в фоновых вкладках и добавляет режим только аудио.
// @description:zh-Hans  使用 YouTube 的流替换 YouTube 播放器为原生 HTML 视频元素。移除广告，恢复画中画，保持视频在后台标签页播放，并添加纯音频模式。
// @author       wBlock
// @match        https://www.youtube.com/*
// @match        https://m.youtube.com/*
// @match        https://music.youtube.com/*
// @match        https://www.youtube-nocookie.com/*
// @run-at       document-start
// @inject-into  page
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    // ------------------------------------------------------------------
    // Tube Cleaner v3.0.0
    //
    // Vinegar Extract approach: instead of trying to extract stream URLs
    // from the player response (which 403 due to SABR), we let YouTube's
    // player create and initialize the <video> element with its SABR/MSE
    // pipeline, then we repurpose that <video> element into a native
    // Safari player.
    //
    // How it works:
    //   1. Wait for YouTube's player to create a <video> element
    //   2. Detach it from YouTube's player container
    //   3. Insert it into a minimal native wrapper
    //   4. Enable Safari's native controls
    //   5. Hide YouTube's player chrome via CSS
    //   6. Ad blocking is handled by wBlock's content blocker
    //
    // This preserves full quality (SABR adaptive bitrate) while giving
    // the user a native Safari video experience.
    // ------------------------------------------------------------------

    var LOG_PREFIX = '[Tube Cleaner]';
    var STORAGE_AUDIO = 'wblock.tubeCleaner.audioOnly';
    var ATTR_CLEANED = 'data-wblock-tc-cleaned';

    var debug = false;

    function log() {
        if (!debug) return;
        try { console.log.apply(console, [LOG_PREFIX].concat([].slice.call(arguments))); }
        catch (e) { /* ignore */ }
    }

    function warn() {
        try { console.warn.apply(console, [LOG_PREFIX].concat([].slice.call(arguments))); }
        catch (e) { /* ignore */ }
    }

    // ------------------------------------------------------------------
    // Preferences
    // ------------------------------------------------------------------

    function isAudioOnly() {
        try { return localStorage.getItem(STORAGE_AUDIO) === '1'; } catch (e) { return false; }
    }

    function setAudioOnly(v) {
        try { localStorage.setItem(STORAGE_AUDIO, v ? '1' : '0'); } catch (e) { /* ignore */ }
    }

    // ------------------------------------------------------------------
    // CSS injected into the page
    // ------------------------------------------------------------------

    var STYLE_ID = 'wblock-tc-style';

    var CSS = [
        // Hide YouTube's player chrome entirely. The native <video>
        // element gets its own controls from Safari.
        '#movie_player .ytp-chrome-top,',
        '#movie_player .ytp-chrome-bottom,',
        '#movie_player .ytp-gradient-top,',
        '#movie_player .ytp-gradient-bottom,',
        '#movie_player .ytp-title,',
        '#movie_player .ytp-pip-button,',
        '#movie_player .ytp-chrome-controls,',
        '#movie_player .ytp-right-controls,',
        '#movie_player .ytp-left-controls,',
        '#movie_player .ytp-play-button,',
        '#movie_player .ytp-volume-area,',
        '#movie_player .ytp-time-display,',
        '#movie_player .ytp-progress-bar,',
        '#movie_player .ytp-progress-bar-container,',
        '#movie_player .ytp-settings-button,',
        '#movie_player .ytp-fullscreen-button,',
        '#movie_player .ytp-remote-button,',
        '#movie_player .ytp-size-button,',
        '#movie_player .ytp-subtitles-button,',
        '#movie_player .ytp-autonav-endscreen-button,',
        '#movie_player .ytp-share-button,',
        '#movie_player .ytp-watch-later-button,',
        '#movie_player .ytp-menuitem,',
        // Storyboard scrubbing preview
        '.ytp-storyboard-framepreview,',
        '.ytp-tooltip,',
        // Ad overlays
        '.ytp-ad-module,',
        '.video-ads,',
        '#player-ads,',
        '.ytp-ad-overlay-container,',
        '.ytp-ad-overlay-slot,',
        '.ytp-ad-image-overlay,',
        '.ytp-ad-overlay-image,',
        '.ytp-ad-badge,',
        // Annotations, cards, end screen
        '.ytp-ce-element,',
        '.ytp-cards-teaser,',
        '.iv-branding,',
        '.ytp-ce-covering-overlay,',
        '.ytp-ce-cover,',
        // Pause overlay
        '.ytp-pause-overlay,',
        // Autoplay countdown
        '.ytp-autonav-endscreen-countdown-overlay,',
        '.ytp-autonav-toggle-button-container,',
        // Info panel
        '.ytp-video-info-panel,',
        // Channel watermark
        '.ytp-watermark,',
        // Related videos overlay
        '.ytp-related-overlay,',
        // Large play button in center
        '.ytp-large-play-button,',
        // Unplayable text
        '.ytp-error,',
        // Spoiler overlay
        '.ytp-spoiler-overlay',
        '{ display: none !important; }',

        // Make the video container fully transparent so only the
        // native <video> element shows through.
        '#movie_player .html5-video-player,',
        '#movie_player',
        '{ background: transparent !important; }',

        // Remove padding/margins that YouTube adds for its controls.
        '#movie_player .html5-video-container',
        '{ position: static !important; }',

        // Let the video fill the container.
        '#movie_player video',
        '{ width: 100% !important; height: 100% !important; }',

        // Hide the YouTube player container's custom cursor.
        '#movie_player',
        '{ cursor: default !important; }',

        // Hide the "Youtube" link in the player.
        '.ytp-youtube-button,',
        '.ytp-title-link',
        '{ display: none !important; }',

        // Ensure the native controls bar is visible on the video.
        // YouTube's player often sets the video to be a child of
        // elements with overflow:hidden or pointer-events:none.
        '.wblock-tc-native video',
        '{ display: block !important; }',

        // Ensure Safari's native media controls show up.
        '.wblock-tc-native video::-webkit-media-controls',
        '{ display: flex !important; opacity: 1 !important; visibility: visible !important; }',

        '.wblock-tc-native video::-webkit-media-controls-panel',
        '{ display: flex !important; opacity: 1 !important; }',

        // Make sure the video container allows native controls to
        // render by removing overflow hidden.
        '#movie_player .html5-video-container',
        '{ overflow: visible !important; }',

        // Let the native controls bar extend below the video.
        '.wblock-tc-native',
        '{ overflow: visible !important; }',
    ].join(' ');

    var AUDIO_ONLY_CSS = [
        '.wblock-tc-native video,',
        '.wblock-tc-native .html5-video-container',
        '{ visibility: hidden !important; }'
    ].join(' ');

    function injectStyles() {
        if (document.getElementById(STYLE_ID)) { return; }
        var style = document.createElement('style');
        style.id = STYLE_ID;
        style.textContent = CSS;
        if (document.head) {
            document.head.appendChild(style);
        } else {
            document.documentElement.appendChild(style);
        }
    }

    function setAudioOnlyStyles(enabled) {
        var id = STYLE_ID + '-audio';
        var existing = document.getElementById(id);
        if (enabled && !existing) {
            var style = document.createElement('style');
            style.id = id;
            style.textContent = AUDIO_ONLY_CSS;
            (document.head || document.documentElement).appendChild(style);
        } else if (!enabled && existing) {
            existing.remove();
        }
    }

    // ------------------------------------------------------------------
    // Background playback
    // ------------------------------------------------------------------

    function enableBackgroundPlayback() {
        try {
            Object.defineProperty(document, 'hidden', {
                get: function () { return false; },
                configurable: true
            });
        } catch (e) { /* ignore */ }
        try {
            Object.defineProperty(document, 'visibilityState', {
                get: function () { return 'visible'; },
                configurable: true
            });
        } catch (e) { /* ignore */ }
    }

    // ------------------------------------------------------------------
    // Core: extract the <video> from YouTube's player and make it native
    // ------------------------------------------------------------------

    var currentState = null;

    function forceNativeControls(video) {
        // YouTube's player actively sets controls=false.  We intercept
        // the property setter to prevent that.  Safari's native controls
        // bar will then stay visible.
        if (video._wblockControlsPatched) return;
        video._wblockControlsPatched = true;

        video.controls = true;

        // Intercept the 'controls' property so YouTube can't turn it off
        try {
            Object.defineProperty(video, 'controls', {
                get: function () { return true; },
                set: function (v) { /* ignore YouTube's attempts to disable */ },
                configurable: false
            });
        } catch (e) {
            // If it fails (e.g. already defined), just try again periodically
        }

        // Also set the attribute directly in case YouTube uses setAttribute
        video.setAttribute('controls', '');
    }

    function transformPlayer() {
        var player = document.getElementById('movie_player');
        if (!player) {
            player = document.querySelector('.html5-video-player');
            if (!player) return;
        }

        var video = player.querySelector('video');
        if (!video) return;

        // Check if we already processed this video
        var videoId = '';
        try {
            var params = new URLSearchParams(location.search);
            videoId = params.get('v') || '';
        } catch (e) { /* ignore */ }

        if (player.getAttribute(ATTR_CLEANED) === videoId) return;
        player.setAttribute(ATTR_CLEANED, videoId);

        log('transforming player for', videoId || '(unknown)');

        // 1. Mark the video as native by adding a wrapper class
        player.classList.add('wblock-tc-native');

        // 2. Force Safari native controls (lock the property so YouTube
        //    can't turn them off)
        forceNativeControls(video);

        // 3. Enable PiP
        video.removeAttribute('disablepictureinpicture');
        video.disablePictureInPicture = false;

        // 4. Keep the original video element (it has the SABR/MSE
        //    pipeline attached by YouTube's player).  Cloning would
        //    lose the source buffers and cause 403s.
        //    Intercept addEventListener to block only YouTube's
        //    tracking/hijacking listeners, not the essential playback
        //    events that YouTube's player needs to manage the stream.
        if (!video._wblockPatched) {
            video._wblockPatched = true;
            var origAdd = video.addEventListener.bind(video);
            video.addEventListener = function (type, listener, options) {
                // Block only YouTube's tracking events, not the
                // essential playback events the player needs.
                var blocked = [
                    'timeupdate', 'progress', 'waiting', 'stalled',
                    'suspend', 'abort', 'emptied'
                ];
                if (blocked.indexOf(type) !== -1) {
                    return; // silently drop tracking
                }
                return origAdd(type, listener, options);
            };
        }

        // 5. Keep controls forced on (YouTube may try to remove them)
        var controlsGuard = setInterval(function () {
            if (video && !video.controls) {
                video.controls = true;
                video.setAttribute('controls', '');
            }
        }, 500);

        // 6. Apply audio-only preference
        setAudioOnlyStyles(isAudioOnly());

        // 7. Enable background playback
        enableBackgroundPlayback();

        // 8. Build toolbar overlay
        buildToolbar(player, video);

        // 9. Observe for video element recreation
        var observer = new MutationObserver(function () {
            var newVid = player.querySelector('video');
            if (newVid && newVid !== video) {
                log('re-patching new video element');
                video = newVid;
                forceNativeControls(video);
                video.disablePictureInPicture = false;
                buildToolbar(player, video);
            }
        });
        observer.observe(player, { childList: true, subtree: true });

        log('player transformed');
    }

    // ------------------------------------------------------------------
    // Toolbar overlay (quality, audio-only, PiP)
    // ------------------------------------------------------------------

    function buildToolbar(player, video) {
        var existing = player.querySelector('.wblock-tc-toolbar');
        if (existing) existing.remove();

        var toolbar = document.createElement('div');
        toolbar.className = 'wblock-tc-toolbar';
        toolbar.style.cssText = 'position:absolute;top:12px;right:12px;z-index:60;display:flex;gap:6px;align-items:center;pointer-events:auto;font:12px/1.2 -apple-system,system-ui,sans-serif;opacity:0;transition:opacity 0.2s';

        var btnStyle = 'background:rgba(0,0,0,0.75);color:#fff;border:1px solid rgba(255,255,255,0.25);border-radius:5px;padding:4px 10px;font-size:12px;cursor:pointer;-webkit-user-select:none;user-select:none';

        // Audio-only toggle
        var audioBtn = document.createElement('button');
        audioBtn.type = 'button';
        audioBtn.style.cssText = btnStyle;
        function updateAudioBtn() {
            audioBtn.textContent = isAudioOnly() ? 'Video' : 'Audio';
            audioBtn.title = isAudioOnly() ? 'Switch to video mode' : 'Switch to audio-only mode';
        }
        updateAudioBtn();
        audioBtn.addEventListener('click', function (e) {
            e.stopPropagation();
            var next = !isAudioOnly();
            setAudioOnly(next);
            setAudioOnlyStyles(next);
            updateAudioBtn();
        });
        toolbar.appendChild(audioBtn);

        // PiP button
        if (document.pictureInPictureEnabled !== false) {
            var pipBtn = document.createElement('button');
            pipBtn.type = 'button';
            pipBtn.textContent = 'PiP';
            pipBtn.title = 'Picture in Picture';
            pipBtn.style.cssText = btnStyle;
            pipBtn.addEventListener('click', function (e) {
                e.stopPropagation();
                try {
                    if (document.pictureInPictureElement) {
                        document.exitPictureInPicture();
                    } else if (video && video.requestPictureInPicture) {
                        video.requestPictureInPicture();
                    }
                } catch (err) { warn('PiP failed', err); }
            });
            toolbar.appendChild(pipBtn);
        }

        // The toolbar appears on hover over the player
        player.addEventListener('mouseenter', function () {
            toolbar.style.opacity = '1';
        });
        player.addEventListener('mouseleave', function () {
            toolbar.style.opacity = '0';
        });

        // Also show on touch
        player.addEventListener('touchstart', function () {
            toolbar.style.opacity = '1';
            setTimeout(function () { toolbar.style.opacity = '0'; }, 3000);
        }, { passive: true });

        player.appendChild(toolbar);
    }

    // ------------------------------------------------------------------
    // SPA navigation handling
    // ------------------------------------------------------------------

    var lastUrl = '';

    function onNavigate() {
        if (location.href === lastUrl) return;
        lastUrl = location.href;

        var player = document.getElementById('movie_player') ||
            document.querySelector('.html5-video-player');
        if (player) {
            player.removeAttribute(ATTR_CLEANED);
            player.classList.remove('wblock-tc-native');
        }

        // Try to transform at intervals
        setTimeout(transformPlayer, 500);
        setTimeout(transformPlayer, 1500);
        setTimeout(transformPlayer, 3000);
    }

    function watchNavigation() {
        document.addEventListener('yt-navigate-finish', onNavigate, true);
        try {
            document.addEventListener('yt-page-data-updated', onNavigate, true);
        } catch (e) { /* ignore */ }
        window.addEventListener('popstate', onNavigate, true);
        // Poll for URL changes as a fallback
        setInterval(function () {
            if (location.href !== lastUrl) onNavigate();
        }, 1000);
    }

    // ------------------------------------------------------------------
    // Boot
    // ------------------------------------------------------------------

    function waitForPlayer() {
        var started = Date.now();
        var timer = setInterval(function () {
            var player = document.getElementById('movie_player') ||
                document.querySelector('.html5-video-player');
            var video = player && player.querySelector('video');
            if (player && video) {
                clearInterval(timer);
                transformPlayer();
            } else if (Date.now() - started > 15000) {
                clearInterval(timer);
                warn('timed out waiting for player');
            }
        }, 250);
    }

    function boot() {
        // Inject CSS immediately
        injectStyles();
        enableBackgroundPlayback();

        lastUrl = location.href;
        watchNavigation();
        waitForPlayer();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', boot);
    } else {
        boot();
    }
})();
"""###

    /// Embedded source of player-cleaner.user.js.
    static let playerCleaner = ###"""
// ==UserScript==
// @name         Player Cleaner
// @namespace    com.skula.wblock
// @version      1.0.0
// @description  Replaces custom video players on websites (other than YouTube) with a clean HTML5 video element, restoring native controls and Picture-in-Picture. Disable it per site from the wBlock toolbar if a player misbehaves.
// @description:de  Ersetzt benutzerdefinierte Video-Player auf Websites (außer YouTube) durch ein sauberes HTML5-Videoelement und stellt native Steuerelemente und Bild-in-Bild wieder her. Deaktivieren Sie ihn bei Problemen pro Website in der wBlock-Symbolleiste.
// @description:es  Reemplaza los reproductores de vídeo personalizados en sitios web (distintos de YouTube) con un elemento de vídeo HTML5 limpio, restaurando los controles nativos y Picture-in-Picture. Desactívelo por sitio desde la barra de herramientas de wBlock si un reproductor falla.
// @description:fr  Remplace les lecteurs vidéo personnalisés des sites web (autres que YouTube) par un élément vidéo HTML5 propre, en restaurant les commandes natives et l'image dans l'image. Désactivez-le par site depuis la barre d'outils wBlock si un lecteur se comporte mal.
// @description:it  Sostituisce i lettori video personalizzati sui siti web (diversi da YouTube) con un elemento video HTML5 pulito, ripristinando i controlli nativi e Picture-in-Picture. Disattivalo per sito dalla barra degli strumenti di wBlock se un lettore non funziona.
// @description:pt-BR  Substitui players de vídeo personalizados em sites (diferentes do YouTube) por um elemento de vídeo HTML5 limpo, restaurando os controles nativos e o Picture-in-Picture. Desative-o por site na barra de ferramentas do wBlock se um player se comportar mal.
// @description:ja  YouTube以外のWebサイトのカスタム動画プレーヤーをクリーンなHTML5 video要素に置き換え、ネイティブコントロールとピクチャー・イン・ピクチャーを復元します。プレーヤーが誤動作する場合は、wBlockツールバーからサイトごとに無効にできます。
// @description:ko  YouTube 이외의 웹사이트에서 사용자 지정 동영상 플레이어를 깨끗한 HTML5 video 요소로 대체하여 네이티브 컨트롤과 PIP를 복원합니다. 플레이어가 오작동하면 wBlock 도구 막대에서 사이트별로 비활성화하세요.
// @description:ru  Заменяет пользовательские видеоплееры на сайтах (кроме YouTube) чистым HTML5-элементом video, восстанавливая нативные элементы управления и картинку-в-картинке. Отключите его для сайта на панели wBlock, если плеер работает некорректно.
// @description:zh-Hans  将网站（YouTube 除外）上的自定义视频播放器替换为干净的 HTML5 video 元素，恢复原生控件和画中画。如果某个播放器出现问题，可从 wBlock 工具栏按网站停用。
// @author       wBlock
// @match        http://*/*
// @match        https://*/*
// @exclude      https://www.youtube.com/*
// @exclude      https://m.youtube.com/*
// @exclude      https://music.youtube.com/*
// @exclude      https://www.youtube-nocookie.com/*
// @run-at       document-idle
// @inject-into  page
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    // ------------------------------------------------------------------
    // Player Cleaner
    //
    // Many sites wrap a perfectly good HTML5 <video> in a custom player
    // (video.js, JW Player, Plyr, Flowplayer, MediaElement, Clappr, ...)
    // whose chrome hides native controls and breaks Picture-in-Picture.
    // This script finds those players, resolves the underlying media source
    // where possible, and swaps in a clean native <video>. When the source
    // is an opaque media-source blob we instead enhance the existing video
    // in place so playback keeps working with native controls.
    //
    // YouTube is excluded; Tube Cleaner handles it. Per-site disabling is
    // provided by wBlock's userscript site settings.
    // ------------------------------------------------------------------

    var LOG_PREFIX = '[Player Cleaner]';
    var ATTR_DONE = 'data-wblock-player-cleaner';

    function log() {
        try {
            if (window.__wblockPlayerCleanerDebug) {
                console.log.apply(console, [LOG_PREFIX].concat([].slice.call(arguments)));
            }
        } catch (e) { /* ignore */ }
    }

    // Player container selectors for the common custom-player libraries.
    var PLAYER_SELECTORS = [
        '.video-js',                 // video.js
        '.vjs-tech',                 // video.js (inner tech, handled via parent)
        '.jwplayer',                 // JW Player
        '.jw-wrapper',               // JW Player
        '.plyr',                     // Plyr
        '.flowplayer',               // Flowplayer
        '.mejs-container',           // MediaElement.js
        '.mejs__container',          // MediaElement.js (newer)
        '.clappr',                   // Clappr
        '[data-clappr-player]',      // Clappr
        '.hlsjs',                    // hls.js wrappers
        '.fluid_video_wrapper',      // Fluid Player
        '.fp-player'                 // Flowplayer (inner)
    ];

    function isHttpUrl(value) {
        return typeof value === 'string' && /^https?:\/\//i.test(value);
    }

    function isPlayableUrl(value) {
        if (!isHttpUrl(value)) { return false; }
        // Prefer obviously-playable media; allow plain http(s) too since many
        // sites serve mp4/m3u8 from extensionless CDN URLs.
        return true;
    }

    // ------------------------------------------------------------------
    // Source discovery
    // ------------------------------------------------------------------

    function sourceFromVideoElement(video) {
        try {
            if (isHttpUrl(video.currentSrc)) { return video.currentSrc; }
            if (isHttpUrl(video.src) && video.src.indexOf('blob:') !== 0) { return video.src; }
            var sources = video.getElementsByTagName('source');
            for (var i = 0; i < sources.length; i++) {
                var src = sources[i].getAttribute('src');
                if (isHttpUrl(src)) { return src; }
            }
        } catch (e) { /* ignore */ }
        return null;
    }

    function sourceFromDom(container) {
        try {
            // Data attributes commonly used to hold the media URL.
            var candidates = container.querySelectorAll('[data-src],[data-video-src],[data-file],[data-video],[data-source],[data-url]');
            var attrs = ['data-src', 'data-video-src', 'data-file', 'data-video', 'data-source', 'data-url'];
            for (var i = 0; i < candidates.length; i++) {
                for (var a = 0; a < attrs.length; a++) {
                    var value = candidates[i].getAttribute(attrs[a]);
                    if (isPlayableUrl(value)) { return value; }
                }
            }
            var direct = container.getAttribute('data-src') || container.getAttribute('data-file') ||
                container.getAttribute('data-video-src');
            if (isPlayableUrl(direct)) { return direct; }
        } catch (e) { /* ignore */ }
        return null;
    }

    function sourceFromVideojs(container) {
        try {
            if (!window.videojs) { return null; }
            var players = window.videojs.getPlayers ? window.videojs.getPlayers() : {};
            for (var id in players) {
                var player = players[id];
                if (!player) { continue; }
                try {
                    var el = player.el ? player.el() : null;
                    if (el && (container.contains(el) || el.contains(container))) {
                        var current = player.currentSource ? player.currentSource() : null;
                        if (current && isPlayableUrl(current.src)) { return current.src; }
                        var list = player.currentSources ? player.currentSources() : [];
                        for (var i = 0; i < list.length; i++) {
                            if (isPlayableUrl(list[i].src)) { return list[i].src; }
                        }
                    }
                } catch (e) { /* keep looking */ }
            }
        } catch (e) { /* ignore */ }
        return null;
    }

    function sourceFromJwPlayer(container) {
        try {
            if (!window.jwplayer) { return null; }
            var instance = window.jwplayer(container.id || container);
            if (!instance) { return null; }
            var item = instance.getPlaylistItem ? instance.getPlaylistItem() : null;
            if (item) {
                if (isPlayableUrl(item.file)) { return item.file; }
                var sources = item.sources || [];
                for (var i = 0; i < sources.length; i++) {
                    if (isPlayableUrl(sources[i].file)) { return sources[i].file; }
                }
            }
        } catch (e) { /* ignore */ }
        return null;
    }

    function sourceFromPageMetadata() {
        try {
            var selectors = [
                'meta[property="og:video:secure_url"]',
                'meta[property="og:video:url"]',
                'meta[property="og:video"]',
                'meta[name="twitter:player:stream"]'
            ];
            for (var i = 0; i < selectors.length; i++) {
                var el = document.querySelector(selectors[i]);
                var content = el ? el.getAttribute('content') : null;
                if (isPlayableUrl(content)) { return content; }
            }
        } catch (e) { /* ignore */ }
        return null;
    }

    function discoverSource(container, video) {
        return sourceFromVideoElement(video) ||
            sourceFromVideojs(container) ||
            sourceFromJwPlayer(container) ||
            sourceFromDom(container) ||
            null;
    }

    // ------------------------------------------------------------------
    // Replacement
    // ------------------------------------------------------------------

    function copyRelevantAttributes(fromVideo, toVideo) {
        var attrs = ['poster', 'title', 'preload', 'loop', 'muted', 'autoplay'];
        for (var i = 0; i < attrs.length; i++) {
            var name = attrs[i];
            var value = fromVideo.getAttribute(name);
            if (value !== null) {
                try { toVideo.setAttribute(name, value); } catch (e) { /* ignore */ }
            }
        }
        // Carry over <track> elements (captions/subtitles).
        try {
            var tracks = fromVideo.getElementsByTagName('track');
            for (var t = 0; t < tracks.length; t++) {
                toVideo.appendChild(tracks[t].cloneNode(true));
            }
        } catch (e) { /* ignore */ }
    }

    function buildCleanVideo(src, originalVideo) {
        var video = document.createElement('video');
        video.controls = true;
        video.playsInline = true;
        video.setAttribute('playsinline', '');
        video.setAttribute('webkit-playsinline', '');
        video.style.width = '100%';
        video.style.height = '100%';
        video.style.background = '#000';
        if (originalVideo) { copyRelevantAttributes(originalVideo, video); }
        if (src) { video.src = src; }
        return video;
    }

    function normalizeContainer(raw) {
        // Some selectors match inner elements; climb to the outermost player
        // wrapper so we replace the whole custom chrome, not just part of it.
        var container = raw;
        var wrapperSelectors = ['.video-js', '.jwplayer', '.jw-wrapper', '.plyr',
            '.flowplayer', '.mejs-container', '.mejs__container', '.clappr',
            '[data-clappr-player]', '.fluid_video_wrapper'];
        for (var i = 0; i < wrapperSelectors.length; i++) {
            var ancestor = container.closest ? container.closest(wrapperSelectors[i]) : null;
            if (ancestor) { container = ancestor; }
        }
        return container;
    }

    function enhanceInPlace(container, video) {
        // We could not resolve a clean source (opaque MSE blob). Keep the
        // existing video playing but expose native controls + PiP and remove
        // obvious custom control overlays.
        try {
            video.controls = true;
            video.playsInline = true;
            video.setAttribute('playsinline', '');
        } catch (e) { /* ignore */ }
        var overlaySelectors = [
            '.vjs-control-bar', '.vjs-big-play-button', '.vjs-poster',
            '.jw-controls', '.jw-display-icon-container',
            '.plyr__controls', '.fp-ui', '.fp-header',
            '.mejs-controls', '.mejs__controls',
            '.clappr-media-control'
        ];
        for (var i = 0; i < overlaySelectors.length; i++) {
            var overlays = container.querySelectorAll(overlaySelectors[i]);
            for (var j = 0; j < overlays.length; j++) {
                try { overlays[j].style.display = 'none'; } catch (e) { /* ignore */ }
            }
        }
    }

    function replacePlayer(container) {
        if (container.getAttribute && container.getAttribute(ATTR_DONE)) { return; }
        var video = container.querySelector ? container.querySelector('video') : null;
        if (!video) { return; }
        if (video.getAttribute && video.getAttribute(ATTR_DONE)) { return; }

        var src = discoverSource(container, video);
        log('player detected', container.className, 'source:', src ? 'resolved' : 'opaque');

        if (src) {
            var clean = buildCleanVideo(src, video);
            clean.setAttribute(ATTR_DONE, '1');
            // Replace the container's contents with the clean video, keeping
            // the container itself so page layout/sizing still applies.
            while (container.firstChild) { container.removeChild(container.firstChild); }
            container.appendChild(clean);
            try {
                container.classList.remove('video-js', 'vjs-paused', 'vjs-playing');
            } catch (e) { /* ignore */ }
            container.setAttribute(ATTR_DONE, '1');
        } else {
            video.setAttribute(ATTR_DONE, '1');
            container.setAttribute(ATTR_DONE, '1');
            enhanceInPlace(container, video);
        }
    }

    // ------------------------------------------------------------------
    // Scanning
    // ------------------------------------------------------------------

    function scan(root) {
        var scope = root || document;
        var seen = [];
        for (var i = 0; i < PLAYER_SELECTORS.length; i++) {
            var nodes;
            try { nodes = scope.querySelectorAll(PLAYER_SELECTORS[i]); }
            catch (e) { continue; }
            for (var j = 0; j < nodes.length; j++) {
                var container = normalizeContainer(nodes[j]);
                if (!container || seen.indexOf(container) !== -1) { continue; }
                seen.push(container);
                try { replacePlayer(container); }
                catch (e) { log('replace failed', e); }
            }
        }
    }

    function observe() {
        if (typeof MutationObserver === 'undefined') { return; }
        var scheduled = false;
        var observer = new MutationObserver(function () {
            if (scheduled) { return; }
            scheduled = true;
            setTimeout(function () {
                scheduled = false;
                scan(document);
            }, 500);
        });
        try {
            observer.observe(document.documentElement, { childList: true, subtree: true });
        } catch (e) { /* ignore */ }
    }

    function boot() {
        scan(document);
        // Players often mount after idle; rescan a few times then observe.
        setTimeout(function () { scan(document); }, 800);
        setTimeout(function () { scan(document); }, 2000);
        observe();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', boot, { once: true });
    } else {
        boot();
    }
})();
"""###

}
