#!/usr/bin/env python3
"""Generate BundledUserScriptSources.generated.swift from the canonical
.user.js sources in wBlockCoreService/BundledUserscripts.

The generated file embeds each userscript as a Swift extended raw-string
constant (###\"\"\" ... \"\"\"###) so the wBlockCoreService framework can ship
the scripts without any bundle-resource wiring. Run this whenever a bundled
userscript changes; scripts/test_bundled_userscripts.swift fails if the
generated constants drift from the .user.js sources.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "wBlockCoreService", "BundledUserscripts")
OUT = os.path.join(ROOT, "wBlockCoreService", "BundledUserScriptSources.generated.swift")

# (constant name, source file)
SOURCES = [
    ("tubeCleaner", "tube-cleaner.user.js"),
    ("playerCleaner", "player-cleaner.user.js"),
]

OPEN_DELIM = '###"""'
CLOSE_DELIM = '"""###'


def main():
    lines = []
    lines.append("// Generated by scripts/generate_bundled_userscripts.py — do not edit by hand.")
    lines.append("// Source of truth: wBlockCoreService/BundledUserscripts/*.user.js")
    lines.append("")
    lines.append("import Foundation")
    lines.append("")
    lines.append("/// Userscripts that ship inside the wBlockCoreService framework rather than")
    lines.append("/// being downloaded from a remote URL. Content is embedded verbatim so the")
    lines.append("/// scripts work offline and update alongside the app.")
    lines.append("enum BundledUserScriptSources {")

    for const_name, file_name in SOURCES:
        path = os.path.join(SRC_DIR, file_name)
        with open(path, "r", encoding="utf-8") as handle:
            content = handle.read()
        if CLOSE_DELIM in content:
            sys.stderr.write("FAIL: %s contains the raw-string closing delimiter\n" % file_name)
            return 1
        # Normalize so the embedded constant is byte-stable: strip trailing
        # whitespace/newlines, then add exactly one trailing newline. Swift
        # multi-line literals drop the newline immediately before the closing
        # delimiter, so the constant equals the content without that newline.
        body = content.rstrip("\n")
        lines.append("    /// Embedded source of %s." % file_name)
        lines.append("    static let %s = %s" % (const_name, OPEN_DELIM))
        lines.append(body)
        lines.append("%s" % CLOSE_DELIM)
        lines.append("")

    lines.append("}")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    sys.stdout.write("Wrote %s\n" % os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
