#!/usr/bin/env python3
"""Generate BundledUserScriptSources.generated.swift from the canonical
.user.js sources in wBlockCoreService/BundledUserscripts.

The generated file embeds each userscript as a Swift extended raw-string
constant (###\"\"\" ... \"\"\"###) so the wBlockCoreService framework can ship
the scripts without any bundle-resource wiring. Run this whenever a bundled
userscript changes; scripts/test_bundled_userscripts.swift fails if the
generated constants drift from the .user.js sources. It also refreshes the
cross-process document-start cache revision in the extension and injector.
"""

import hashlib
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "wBlockCoreService", "BundledUserscripts")
OUT = os.path.join(ROOT, "wBlockCoreService", "BundledUserScriptSources.generated.swift")

# (constant name, source file)
SOURCES = [
    ("tubeCleaner", "tube-cleaner.user.js"),
    ("playerCleaner", "player-cleaner.user.js"),
    ("darkReader", "dark-reader.user.js"),
]

OPEN_DELIM = '###"""'
CLOSE_DELIM = '"""###'


def main():
    # Rebuild the Dark Reader userscript before embedding it. The vendored API
    # and handwritten adapter remain separate source artifacts.
    subprocess.run(
        [sys.executable, os.path.join(ROOT, "scripts", "build_darkreader_userscript.py")],
        cwd=ROOT,
        check=True,
    )
    lines = []
    lines.append("// Generated by scripts/generate_bundled_userscripts.py — do not edit by hand.")
    lines.append("// Source of truth: wBlockCoreService/BundledUserscripts/*.user.js")
    lines.append("")
    lines.append("import Foundation")
    lines.append("")
    revision_material = "\n".join(
        open(os.path.join(SRC_DIR, file_name), "r", encoding="utf-8").read().rstrip("\n")
        for _, file_name in SOURCES
    )
    cache_revision = hashlib.sha256(revision_material.encode("utf-8")).hexdigest()

    lines.append("/// Userscripts that ship inside the wBlockCoreService framework rather than")
    lines.append("/// being downloaded from a remote URL. Content is embedded verbatim so the")
    lines.append("/// scripts work offline and update alongside the app.")
    lines.append("enum BundledUserScriptSources {")
    lines.append('    static let documentStartCacheRevision = "{}"'.format(cache_revision))
    lines.append("")

    for const_name, file_name in SOURCES:
        path = os.path.join(SRC_DIR, file_name)
        with open(path, "r", encoding="utf-8") as handle:
            content = handle.read()
        if CLOSE_DELIM in content:
            sys.stderr.write("FAIL: %s contains the raw-string closing delimiter\n" % file_name)
            return 1
        # Normalize so the embedded constant is byte-stable: strip trailing
        # whitespace/newlines, then add exactly one trailing newline. Swift
        # multi-line literals drop the newline immediately before the closing
        # delimiter, so the constant equals the content without that newline.
        body = content.rstrip("\n")
        lines.append("    /// Embedded source of %s." % file_name)
        lines.append("    static let %s = %s" % (const_name, OPEN_DELIM))
        lines.append(body)
        lines.append("%s" % CLOSE_DELIM)
        lines.append("")

    lines.append("}")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    # Keep the shipped background manifest tied to the same source hash. This
    # makes bundled content/app upgrades invalidate old extension caches
    # without a manually bumped version constant.
    marker = "__WBLOCK_BUNDLED_USERSCRIPT_CACHE_REVISION__"
    for relative_path in [
        os.path.join("extension-src", "background.js"),
    ]:
        path = os.path.join(ROOT, relative_path)
        with open(path, "r", encoding="utf-8") as handle:
            source = handle.read()
        updated, count = re.subn(re.escape(marker), cache_revision, source)
        if count == 0:
            updated, count = re.subn(
                r"(?<=WBLOCK_BUNDLED_USERSCRIPT_CACHE_REVISION = ['\"]).*?(?=['\"])",
                cache_revision,
                source,
            )
        if count == 0:
            raise RuntimeError("missing cache revision marker in {}".format(relative_path))
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(updated)

    # The shipped background is a minified build artifact. Rebuild it from the
    # just-updated extension source so this generator is a complete, repeatable
    # source-to-artifact operation rather than a hash-only update.
    subprocess.run(
        [os.path.join(ROOT, "scripts", "minify-extension-js.sh")],
        cwd=ROOT,
        check=True,
    )

    sys.stdout.write("Wrote %s (cache revision %s)\n" % (os.path.relpath(OUT, ROOT), cache_revision))
    return 0


if __name__ == "__main__":
    sys.exit(main())
