#!/usr/bin/env swift
import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
func source(_ path: String) throws -> String { try String(contentsOf: root.appendingPathComponent(path), encoding: .utf8) }
func require(_ text: String, _ needle: String) {
    guard text.contains(needle) else { fputs("FAIL: missing \(needle)\n", stderr); exit(1) }
}
func requireCondition(_ condition: Bool, _ message: String) {
    guard condition else { fputs("FAIL: \(message)\n", stderr); exit(1) }
}
let content = try source("wBlock/ContentView.swift")
require(content, "OnboardingPresentationModifier")
require(content, "UIDevice.current.userInterfaceIdiom == .pad")
require(content, ".fullScreenCover(isPresented: $isPresented)")
require(content, ".sheet(isPresented: $isPresented)")
let onboarding = try source("wBlock/OnboardingView.swift")
require(onboarding, ".interactiveDismissDisabled(!hasCompletedOnboarding)")
require(content, ".onChangeCompat(of: selectedTab)")
require(content, "pendingEssentialFilter")
require(content, "filterRequirementsPanel")
require(content, "filterTextRequirementsPanel")
require(content, "filterFileRequirementsPanel")
require(content, "stageFile(at: url)")
require(content, "stagingGeneration")
require(content, "FilterListContentValidator.appearsToBeFilterList")
require(content, "stagedFile != nil")
require(content, "Text(\"Change File\")")
require(content, "case .paste, .file: return \"Add\"")
require(content, "FilterListContentValidator.isSupportedLocalFile")
let scripts = try source("wBlock/UserScriptManagerView.swift")
require(scripts, "showingPasteReplacementConfirmation")
require(scripts, "Replace Existing Content?")
require(scripts, "if currentText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty")
require(scripts, "requirementsPanel")
require(scripts, "FilterListCategory.userScriptCategories")
require(scripts, "stagingGeneration")
require(scripts, "editorMetadataOverrides")
let macOSBodyStart = scripts.range(of: "private var macosBody")!.lowerBound
let macOSBody = String(scripts[macOSBodyStart...])
require(macOSBody, "macosModeContent")
let macOSModeStart = scripts.range(of: "private var macosModeContent")!.lowerBound
let macOSURLStart = scripts.range(of: "private var macosURLCard")!.lowerBound
let macOSModeContent = String(scripts[macOSModeStart..<macOSURLStart])
requireCondition(macOSModeContent.components(separatedBy: "requirementsPanel").count - 1 == 1, "macOS URL mode must render one requirements panel")
requireCondition(!macOSBody.contains("if addMode == .url {\n                        requirementsPanel"), "macOS must not add a second requirements panel")
let localization = try source("wBlock/LocalizationHelpers.swift")
require(localization, "NSLocalizedString(\"Other\"")
let settings = try source("wBlock/SettingsView.swift")
require(settings, "private var advancedSection")
require(settings, "private var helpSection")
require(settings, "Report Issues")
require(settings, "private var logTimestampControls")
require(settings, "Toggle(\"Sync with device timezone\"")
require(settings, "Picker(\"Time zone\"")
let manager = try source("wBlock/AppFilterManager.swift")
require(manager, "func setFilterListSelection(id: UUID, selected: Bool)")
require(content, "setFilterListSelection(id: filter.id, selected: false)")
let siteSettings = try source("wBlock/SiteSettingsView.swift")
require(siteSettings, "struct SiteSettingsView: View")
require(siteSettings, "private struct SiteSettingsSnapshot: Equatable")
require(siteSettings, "private func undoSiteMutation()")
require(siteSettings, "private func redoSiteMutation()")
require(siteSettings, "await apply(state.before, to: state.domain)")
requireCondition(!siteSettings.contains("ZapperRuleManager"), "site settings must not own zapper state")
let zapper = try source("wBlock/ElementZapperSettingsView.swift")
require(zapper, "pendingConfirmation = .clearAll")
require(zapper, "await dataManager.deleteZapperRule(rule, forHost: domain)")
require(zapper, "await dataManager.restoreZapperRule(undo.rule, forHost: undo.domain, at: undo.index)")
require(zapper, "setZapperRulesDisabled(!applied, forHost: domain)")
require(zapper, "Changes take full effect after the next apply.")
let settingsDestination = try source("wBlock/SettingsView.swift")
require(settingsDestination, "ElementZapperSettingsView(filterManager: filterManager)")
print("PASS")
