#!/usr/bin/env swift
import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
func source(_ path: String) throws -> String { try String(contentsOf: root.appendingPathComponent(path), encoding: .utf8) }
func require(_ text: String, _ needle: String) {
    guard text.contains(needle) else { fputs("FAIL: missing \(needle)\n", stderr); exit(1) }
}
func requireCondition(_ condition: Bool, _ message: String) {
    guard condition else { fputs("FAIL: \(message)\n", stderr); exit(1) }
}
let content = try source("wBlock/ContentView.swift")
require(content, "OnboardingPresentationModifier")
require(content, "UIDevice.current.userInterfaceIdiom == .pad")
require(content, ".fullScreenCover(isPresented: $isPresented)")
require(content, ".sheet(isPresented: $isPresented)")
let onboarding = try source("wBlock/OnboardingView.swift")
require(onboarding, "@State private var step: OnboardingStep = .welcome")
require(onboarding, "case .welcome:\n            welcomeStep")
require(onboarding, "Text(\"The end of Safari ad-blocking B.S.\")")
require(onboarding, "Image(\"AppIcon\")")
require(onboarding, "Button(step == .welcome ? \"Get Started\"")
require(onboarding, ".interactiveDismissDisabled(!hasCompletedOnboarding)")
require(onboarding, "case userscripts")
require(onboarding, "[.welcome, .protection, .regional, .userscripts, .sync, .setup]")
require(onboarding, "case .userscripts:\n            userscriptsStep")
requireCondition(!onboarding.contains("TextField(\"Search languages\""), "onboarding must not show the old language search field")
requireCondition(!onboarding.contains("languageSearchText"), "onboarding must not retain obsolete language search state")
require(onboarding, "Menu {")
require(onboarding, "Image(systemName: \"plus\")")
require(onboarding, "Text(\"Add\")")
require(onboarding, ".frame(maxWidth: .infinity)")
require(onboarding, "selectedLanguages.remove(lang.code)")
let regionalStart = onboarding.range(of: "private var regionalStep")!.lowerBound
let userscriptsStart = onboarding.range(of: "private var userscriptsStep", range: regionalStart..<onboarding.endIndex)!.lowerBound
let syncStart = onboarding.range(of: "private var syncStep", range: userscriptsStart..<onboarding.endIndex)!.lowerBound
let regionalStep = String(onboarding[regionalStart..<userscriptsStart])
let userscriptsStep = String(onboarding[userscriptsStart..<syncStart])
requireCondition(!regionalStep.contains("userscriptCard"), "regional language selection must not bury userscripts below filters")
require(userscriptsStep, "Text(\"Userscripts\")")
require(userscriptsStep, "userscriptList(general)")
require(userscriptsStep, "private func userscriptList")
require(userscriptsStep, "Divider().padding(.leading, 44)")
require(userscriptsStep, "ForEach(selectedLanguagePickerOptions)")
require(userscriptsStep, "languageCodes.contains(language.code)")
require(content, ".onChangeCompat(of: selectedTab)")
require(content, "pendingEssentialFilter")
require(content, "filterRequirementsPanel")
require(content, "filterTextRequirementsPanel")
require(content, "filterFileRequirementsPanel")
require(content, "stageFile(at: url)")
require(content, "stagingGeneration")
require(content, "FilterListContentValidator.appearsToBeFilterList")
require(content, "stagedFile != nil")
require(content, "Text(\"Change File\")")
require(content, "case .paste, .file: return \"Add\"")
require(content, "FilterListContentValidator.isSupportedLocalFile")
require(content, "if showsFlags, let flags = filter.flagEmojis")
require(content, "filterRowView(for: filter, showsFlags: false)")
require(content, "ForEach(item.filters) { filter in")
require(content, "ForEach(filters) { filter in")
requireCondition(!content.contains("adGuardAnnoyances"), "annoyance filters must render individually without aggregate dropdown state")
requireCondition(
    !content.contains("Text(String(filter.localizedDisplayName.prefix(1)))"),
    "filter rows must not repeat list-name initials as decorative labels"
)
let scripts = try source("wBlock/UserScriptManagerView.swift")
let addContentShell = try source("wBlock/AddContentShell.swift")
require(addContentShell, "protocol AddContentMode")
require(addContentShell, "struct AddContentModePicker")
require(addContentShell, "struct AddContentRequirementsPanel")
require(addContentShell, ".frame(maxWidth: .infinity, alignment: .leading)")
for view in [content, scripts] {
    require(view, "AddContentModePicker(selection: $addMode)")
    require(view, "AddContentRequirementsPanel")
    require(view, ".tabItem { Label(\"URL\", systemImage: \"link\") }")
    require(view, ".tabItem { Label(\"Text\", systemImage: \"text.alignleft\") }")
    require(view, ".tabItem { Label(\"File\", systemImage: \"doc\") }")
}
requireCondition(!content.contains("ForEach(AddMode.allCases)"), "filter mode picker must use the shared picker")
requireCondition(!scripts.contains("ForEach(AddMode.allCases)"), "userscript mode picker must use the shared picker")
require(content, "case .url: return \"link\"")
require(content, "case .paste: return \"text.alignleft\"")
require(content, "case .file: return \"doc\"")
require(scripts, "case .url: return \"link\"")
require(scripts, "case .text: return \"text.alignleft\"")
require(scripts, "case .file: return \"doc\"")
require(scripts, "showingPasteReplacementConfirmation")
require(scripts, "Replace Existing Content?")
require(scripts, "if currentText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty")
require(scripts, "requirementsPanel")
require(scripts, "editorRequirementsPanel")
require(scripts, "fileRequirementsPanel")
require(scripts, "metadataRequirementText")
requireCondition(!scripts.contains("editorImportMessage"), "metadata guidance must not remain detached")
require(scripts, "FilterListCategory.userScriptCategories")
require(scripts, "stagingGeneration")
require(scripts, "editorMetadataOverrides")
let macOSBodyStart = scripts.range(of: "private var macosBody")!.lowerBound
let macOSBody = String(scripts[macOSBodyStart...])
require(macOSBody, "macosModeContent")
let macOSModeStart = scripts.range(of: "private var macosModeContent")!.lowerBound
let macOSURLStart = scripts.range(of: "private var macosURLCard")!.lowerBound
let macOSModeContent = String(scripts[macOSModeStart..<macOSURLStart])
requireCondition(macOSModeContent.components(separatedBy: "requirementsPanel").count - 1 == 1, "macOS URL mode must render one requirements panel")
requireCondition(!macOSBody.contains("if addMode == .url {\n                        requirementsPanel"), "macOS must not add a second requirements panel")
let localization = try source("wBlock/LocalizationHelpers.swift")
require(localization, "NSLocalizedString(\"Other\"")
let settings = try source("wBlock/SettingsView.swift")
require(settings, "private var advancedSection")
require(settings, "private var helpSection")
require(settings, "Report Issues")
require(settings, "Label(\"Contact Us\", systemImage: \"bubble.left\")")
requireCondition(!settings.contains("bubble.left.and.bubble.right"), "Contact Us must use a standard-width Help icon")
require(settings, "private var logTimestampControls")
require(settings, "Toggle(\"Sync timestamps with device timezone\"")
requireCondition(!settings.contains("Picker(\"Time zone\""), "timestamp settings must not show a custom time-zone picker")
let dangerStart = settings.range(of: "private var dangerZoneSection")!.lowerBound
let settingsContentStart = settings.range(of: "private var settingsContent", range: dangerStart..<settings.endIndex)!.lowerBound
let dangerZone = String(settings[dangerStart..<settingsContentStart])
require(dangerZone, ".buttonStyle(.bordered)")
require(dangerZone, ".tint(.red)")
require(dangerZone, ".controlSize(.small)")
requireCondition(!dangerZone.contains(".frame(maxWidth: .infinity)"), "Restart Onboarding must not fill the settings row")
let manager = try source("wBlock/AppFilterManager.swift")
require(manager, "func setFilterListSelection(id: UUID, selected: Bool)")
require(content, "setFilterListSelection(id: filter.id, selected: false)")
let siteSettings = try source("wBlock/SiteSettingsView.swift")
require(siteSettings, "struct SiteSettingsView: View")
require(siteSettings, "private struct SiteSettingsSnapshot: Equatable")
require(siteSettings, "private func undoSiteMutation()")
require(siteSettings, "private func redoSiteMutation()")
require(siteSettings, "await apply(state.before, to: state.domain)")
requireCondition(!siteSettings.contains("ZapperRuleManager"), "site settings must not own zapper state")
let zapper = try source("wBlock/ElementZapperSettingsView.swift")
require(zapper, "pendingConfirmation = .clearAll")
require(zapper, "await dataManager.deleteZapperRule(rule, forHost: domain)")
require(zapper, "await dataManager.restoreZapperRule(undo.rule, forHost: undo.domain, at:")
require(zapper, "setZapperRulesDisabled(!enabled, forHost: domain)")
require(zapper, "Element Zapper changes take full effect after the next apply.")
let settingsDestination = try source("wBlock/SettingsView.swift")
require(settingsDestination, "ElementZapperSettingsView(filterManager: filterManager)")
print("PASS")
