/*! SafariExtension v4.3.0. Upstream (c) Adguard Software Ltd., GPL-3.0, https://github.com/AdguardTeam/SafariConverterLib/tree/master/Extension */
/*! Generated artifact — do not edit. Edit extension-src/content.js and run scripts/minify-extension-js.sh */
function _defineProperty2(S,v,d){return(v=_toPropertyKey(v))in S?Object.defineProperty(S,v,{value:d,enumerable:!0,configurable:!0,writable:!0}):S[v]=d,S}function _toPropertyKey(S){var v=_toPrimitive(S,"string");return typeof v=="symbol"?v:v+""}function _toPrimitive(S,v){if(typeof S!="object"||!S)return S;var d=S[Symbol.toPrimitive];if(d!==void 0){var Y=d.call(S,v||"default");if(typeof Y!="object")return Y;throw new TypeError("@@toPrimitive must return a primitive value.")}return(v==="string"?String:
Number)(S)}(function(S){"use strict";function v(e,t,r){return t in e?Object.defineProperty(e,t,{value:r,enumerable:!0,configurable:!0,writable:!0}):e[t]=r,e}const d={SELECTOR_LIST:"SelectorList",SELECTOR:"Selector",REGULAR_SELECTOR:"RegularSelector",EXTENDED_SELECTOR:"ExtendedSelector",ABSOLUTE_PSEUDO_CLASS:"AbsolutePseudoClass",RELATIVE_PSEUDO_CLASS:"RelativePseudoClass"};class Y{constructor(t){v(this,"children",[]),this.type=t}addChild(t){this.children.push(t)}}class _r extends Y{constructor(t){
super(d.REGULAR_SELECTOR),this.value=t}}class Nr extends Y{constructor(t){super(d.RELATIVE_PSEUDO_CLASS),this.name=t}}class $r extends Y{constructor(t){super(d.ABSOLUTE_PSEUDO_CLASS),v(this,"value",""),this.name=t}}const gt="[",Rt="]",wt="(",Tt=")",yt="{",vt="}",h={SQUARE:{LEFT:gt,RIGHT:Rt},PARENTHESES:{LEFT:wt,RIGHT:Tt},CURLY:{LEFT:yt,RIGHT:vt}},g="/",N="\\",M=" ",j=",",Ie=".",Ee=";",A=":",D="'",_='"',Ot="^",bt="$",q="=",re="	",se="\r",ne=`
`,oe="\f",At=[M,re,se,ne,oe],T="*",Me="#",De=Ie,he=M,ie=">",le="+",ae="~",pe=[he,ie,le,ae],Ct=[gt,Rt,wt,Tt,yt,vt,g,N,Ee,A,j,D,_,Ot,bt,T,Me,De,he,ie,le,ae,re,se,ne,oe],kr=[A,Ee,D,_,N,M,re,se,ne,oe],Ue="contains",Be="has-text",xe="-abp-contains",Pt="matches-css",Lt="matches-css-before",_t="matches-css-after",Nt="matches-attr",$t="matches-property",W="xpath",Ve="nth-ancestor",Ir=[Ue,Be,xe],Ge="upward",U="remove",kt="has",It="-abp-has",Fe=[kt,It],He="is",Ye="not",Mt=[Ue,Be,xe,Pt,Lt,_t,Nt,$t,W,Ve,Ge],
Dt=[...Fe,He,Ye],We=[...Mt,...Dt],Mr=[Ye,He],Ke=":scope",Ut={AFTER:"after",BACKDROP:"backdrop",BEFORE:"before",CUE:"cue",CUE_REGION:"cue-region",FIRST_LETTER:"first-letter",FIRST_LINE:"first-line",FILE_SELECTION_BUTTON:"file-selector-button",GRAMMAR_ERROR:"grammar-error",MARKER:"marker",PART:"part",PLACEHOLDER:"placeholder",SELECTION:"selection",SLOTTED:"slotted",SPELLING_ERROR:"spelling-error",TARGET_TEXT:"target-text"},Bt="@",Xe="content",Q="true",xt="global",Se="Selector should be defined",L={
NO_STYLE:"No style declaration found",NO_SELECTOR:`${Se} before style declaration in stylesheet`,INVALID_STYLE:"Invalid style declaration",UNCLOSED_STYLE:"Unclosed style declaration",NO_PROPERTY:"Missing style property in declaration",NO_VALUE:"Missing style value in declaration",NO_STYLE_OR_REMOVE:"Style should be declared or :remove() pseudo-class should used",NO_COMMENT:"Comments are not supported"},Vt="At-rules are not supported",K={INVALID_REMOVE:"Invalid :remove() pseudo-class in selector",
NO_TARGET_SELECTOR:`${Se} before :remove() pseudo-class`,MULTIPLE_USAGE:"Pseudo-class :remove() appears more than once in selector",INVALID_POSITION:"Pseudo-class :remove() should be at the end of selector"},Dr="Error while matching element",Gt=50,Ur=/\[-(?:ext)-([a-z-_]+)=(["'])((?:(?=(\\?))\4.)*?)\2\]/g,Br="[-ext-",xr=(e,t,r,s)=>{const n=new RegExp(`([^\\\\]|^)\\\\${r}`,"g"),o=s.replace(n,`$1${r}`);return`:${t}(${o})`},Vr=/\(:scope >/g,Gr="(>",Fr=/(:matches-css)-(before|after)\(/g,Hr=(e,t,r)=>`${t}${h.
PARENTHESES.LEFT}${r}${j}`,Yr=e=>{const t=e.replace(Ur,xr).replace(Vr,Gr).replace(Fr,Hr);if(t.includes(Br))throw new Error(`Invalid extended-css old syntax selector: '${e}'`);return t},Wr=e=>{const t=e.trim();return Yr(t)},C={MARK:"mark",WORD:"word"},ze=(e,t)=>{let r="";const s=[];return e.split("").forEach(o=>{if(t.includes(o)){r.length>0&&(s.push({type:C.WORD,value:r}),r=""),s.push({type:C.MARK,value:o});return}r+=o}),r.length>0&&s.push({type:C.WORD,value:r}),s},Kr=e=>{const t=Wr(e);return ze(
t,Ct)},Xr=e=>ze(e,[...Ct,q]),je=e=>{const t=[];e.forEach(s=>t.push(s));const r=[];for(;t.length;){const s=t.pop();if(!s)throw new Error("Unable to make array flat");Array.isArray(s)?s.forEach(n=>t.push(n)):r.push(s)}return r.reverse()},J=e=>e[0],B=e=>e[e.length-1],Ft=e=>e[e.length-2],me=(e,t,r)=>{const s=e[t];if(!s)throw new Error(r||`No array item found by index ${t}`);return s},Ht="At least one of Selector node children should be RegularSelector",ge=e=>e?.type===d.SELECTOR_LIST,Z=e=>e?.type===
d.SELECTOR,O=e=>e?.type===d.REGULAR_SELECTOR,ee=e=>e.type===d.EXTENDED_SELECTOR,$=e=>e?.type===d.ABSOLUTE_PSEUDO_CLASS,x=e=>e?.type===d.RELATIVE_PSEUDO_CLASS,V=e=>{if(e===null)throw new Error("Ast node should be defined");if(!$(e)&&!x(e))throw new Error("Only AbsolutePseudoClass or RelativePseudoClass ast node can have a name");if(!e.name)throw new Error("Extended pseudo-class should have a name");return e.name},P=(e,t)=>{if(e===null)throw new Error("Ast node should be defined");if(!O(e)&&!$(e))
throw new Error("Only RegularSelector ot AbsolutePseudoClass ast node can have a value");if(!e.value)throw new Error(t||"Ast RegularSelector ot AbsolutePseudoClass node should have a value");return e.value},Yt=e=>e.filter(O),zr=(e,t)=>{const r=Yt(e),s=J(r);if(!s)throw new Error(t||Ht);return s},Wt=e=>{const t=Yt(e),r=B(t);if(!r)throw new Error(Ht);return r},Re=(e,t)=>{if(e.children.length!==1)throw new Error(t);const r=J(e.children);if(!r)throw new Error(t);return r},we=e=>Re(e,"Extended selecto\
r should be specified"),qe=e=>{if(!x(e))throw new Error("Only RelativePseudoClass node can have relative SelectorList node as child");return Re(e,`Missing arg for :${V(e)}() pseudo-class`)},jr="i",Kt={COMMON:[h.PARENTHESES.LEFT,D,_,q,Ie,A,M],CONTAINS:[h.PARENTHESES.LEFT,D,_]},Qe=e=>We.includes(e),Je=e=>Mr.includes(e),Xt=(e,t)=>!e||!t?!1:pe.includes(t)||e===C.WORD||t===T||t===Me||t===De||t===A||t===D||t===_||t===h.SQUARE.LEFT,qr=(e,t,r)=>{const s=B(e.extendedPseudoNamesStack);if(!s)throw new Error(
"Regexp pattern allowed only in arg of extended pseudo-class");if(Ir.includes(s))return Kt.CONTAINS.includes(t);if(t===g&&s!==W){const n=r?`in arg part: '${r}'`:"arg";throw new Error(`Invalid regexp pattern for :${s}() pseudo-class ${n}`)}return Kt.COMMON.includes(t)},ce=(e,t)=>e===h.SQUARE.LEFT&&t!==N,Qr=e=>{var t;if(!e.isAttributeBracketsOpen)return!1;const r=e.attributeBuffer.split(M).join(""),s=Xr(r),n=J(s),o=n?.type,i=n?.value;if(o===C.MARK&&i!==N)throw new Error(`'[${e.attributeBuffer}]' i\
s not a valid attribute due to '${i}' at start of it`);const l=B(s),c=l?.type,a=l?.value;if(a===q)throw new Error(`'[${e.attributeBuffer}]' is not a valid attribute due to '${q}'`);const f=s.findIndex(F=>F.type===C.MARK&&F.value===q),E=(t=Ft(s))===null||t===void 0?void 0:t.value;if(f===-1)return c===C.WORD?!0:E===N&&(a===_||a===D);const I=me(s,f+1).value;if(!(I===D||I===_)){if(c===C.WORD)return!0;throw new Error(`'[${e.attributeBuffer}]' is not a valid attribute`)}return c===C.WORD&&a?.toLocaleLowerCase()===
jr?E===I:a===I},zt=e=>e?At.includes(e):!1,Te=e=>Mt.includes(e),jt=e=>Dt.includes(e),X=e=>e.pathToBufferNode.length===0?null:B(e.pathToBufferNode)||null,Jr=e=>e.pathToBufferNode.length<2?null:Ft(e.pathToBufferNode)||null,Ze=e=>{const t=X(e);if(!t)throw new Error("No bufferNode found");if(!Z(t))throw new Error("Unsupported bufferNode type");const r=Wt(t.children);return e.pathToBufferNode.push(r),r},m=(e,t)=>{const r=X(e);if(r===null)throw new Error("No bufferNode to update");if($(r))r.value+=t;else if(O(
r))r.value+=t,e.isAttributeBracketsOpen&&(e.attributeBuffer+=t);else throw new Error(`${r.type} node cannot be updated. Only RegularSelector and AbsolutePseudoClass are supported`)},Zr=e=>{const t=new Y(d.SELECTOR_LIST);e.ast=t,e.pathToBufferNode.push(t)},y=function(e,t){let r=arguments.length>2&&arguments[2]!==void 0?arguments[2]:"";const s=X(e);if(s===null)throw new Error("No buffer node");let n;t===d.REGULAR_SELECTOR?n=new _r(r):t===d.ABSOLUTE_PSEUDO_CLASS?n=new $r(r):t===d.RELATIVE_PSEUDO_CLASS?
n=new Nr(r):n=new Y(t),s.addChild(n),e.pathToBufferNode.push(n)},ye=(e,t)=>{Zr(e),y(e,d.SELECTOR),y(e,d.REGULAR_SELECTOR,t)},ve=function(e){let t=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"";y(e,d.SELECTOR_LIST),y(e,d.SELECTOR),y(e,d.REGULAR_SELECTOR,t)},k=(e,t)=>{for(let s=e.pathToBufferNode.length-1;s>=0;s-=1){var r;if(((r=e.pathToBufferNode[s])===null||r===void 0?void 0:r.type)===t){e.pathToBufferNode=e.pathToBufferNode.slice(0,s+1);break}}},qt=e=>{const t=X(e);if(t&&ge(t)&&x(Jr(
e)))return t;k(e,d.SELECTOR);const r=X(e);if(!r)throw new Error("No SelectorNode, impossible to continue selector parsing by ExtendedCss");const s=B(r.children),n=s&&ee(s)&&e.standardPseudoBracketsStack.length===0,o=n&&J(s.children);let i=r;if(o){const l=n&&o.name,c=l&&jt(l),a=l&&Te(l),f=c&&e.extendedPseudoBracketsStack.length>0&&e.extendedPseudoBracketsStack.length===e.extendedPseudoNamesStack.length,E=a&&l===B(e.extendedPseudoNamesStack);(f||E)&&(e.pathToBufferNode.push(s),i=o)}else n?i=r:i=Ze(
e);return e.pathToBufferNode.push(i),i},Qt=(e,t,r,s,n)=>{if(!s)throw new Error(`Invalid colon ':' at the end of selector: '${t}'`);if(Qe(s.toLowerCase())){if(Fe.includes(s)&&e.standardPseudoNamesStack.length>0)throw new Error(`Usage of :${s}() pseudo-class is not allowed inside regular pseudo: '${B(e.standardPseudoNamesStack)}'`);k(e,d.SELECTOR),y(e,d.EXTENDED_SELECTOR)}else{if(s.toLowerCase()===U)throw new Error(`${K.INVALID_REMOVE}: '${t}'`);m(e,r),n&&n===h.PARENTHESES.LEFT&&!e.isAttributeBracketsOpen&&
e.standardPseudoNamesStack.push(s)}},es=`html ${T}`,ts=e=>e.children.some(t=>t.children.some(r=>ee(r))),rs=e=>e.children.map(r=>{const s=Re(r,"Ast Selector node should have RegularSelector node");return P(s)}).join(`${j}${M}`),Oe=(e,t)=>(e.children=t,e),et=e=>{if(e===null)return!1;const t=we(e),r=V(t);if(Te(r))return!1;const n=qe(t).children;return Je(r)&&n.every(i=>{try{const l=Re(i,"Selector node should have RegularSelector");return O(l)}catch{return!1}})?!0:n.some(o=>o.children.some(i=>ee(i)?
et(i):!1))},ss=(e,t)=>{if(!e)return null;const r=we(e),s=qe(r);if(!ts(s)){const l=rs(s),c=V(r),a=`${A}${c}${h.PARENTHESES.LEFT}${l}${h.PARENTHESES.RIGHT}`;return t.value=`${P(t)}${a}`,null}const o=Jt(s),i=Oe(r,[o]);return Oe(e,[i])},ns=(e,t)=>{t.value=`${P(t)}${M}${P(e)}`},os=e=>{const t=e.children,r=[];let s=0;for(;s<t.length;){const n=me(t,s,"currentChild should be specified");if(s===0)r.push(n);else{const o=Wt(r);if(ee(n)){let i=null,l=et(n);for(i=n;l;)i=ss(i,o),l=et(i);if(i!==null){r.push(i);
const c=we(i),a=V(c);P(o)===T&&Je(a)&&(o.value=es)}}else if(O(n)){const i=B(r)||null;O(i)&&ns(n,o)}}s+=1}return Oe(e,r)},Jt=e=>Oe(e,e.children.map(t=>os(t))),is=e=>Jt(e),ls="body",Zt="No white space is allowed before or after extended pseudo-class name in selector",as=e=>{const t=Kr(e),r={ast:null,pathToBufferNode:[],extendedPseudoNamesStack:[],extendedPseudoBracketsStack:[],standardPseudoNamesStack:[],standardPseudoBracketsStack:[],isAttributeBracketsOpen:!1,attributeBuffer:"",isRegexpOpen:!1,shouldOptimize:!1};
let s=0;for(;s<t.length;){const n=t[s];if(!n)break;const{type:o,value:i}=n,l=t[s+1],c=l?.type,a=l?.value,f=t[s+2],E=f?.value,p=t[s-1],I=p?.type,b=p?.value,F=t[s-2],xn=F?.value;let u=X(r);switch(o){case C.WORD:if(u===null)ye(r,i);else if(ge(u))y(r,d.SELECTOR),y(r,d.REGULAR_SELECTOR,i);else if(O(u))m(r,i);else if(ee(u)){if(zt(a)&&E===h.PARENTHESES.LEFT)throw new Error(`${Zt}: '${e}'`);const H=i.toLowerCase();r.extendedPseudoNamesStack.push(H),Te(H)?y(r,d.ABSOLUTE_PSEUDO_CLASS,H):(y(r,d.RELATIVE_PSEUDO_CLASS,
H),Je(H)&&(r.shouldOptimize=!0))}else $(u)?m(r,i):x(u)&&ve(r,i);break;case C.MARK:switch(i){case j:if(!u||typeof u<"u"&&!a)throw new Error(`'${e}' is not a valid selector`);O(u)?r.isAttributeBracketsOpen?m(r,i):k(r,d.SELECTOR_LIST):$(u)?m(r,i):Z(u)&&k(r,d.SELECTOR_LIST);break;case M:if(O(u)&&!r.isAttributeBracketsOpen&&(u=qt(r)),O(u)){if(!r.isAttributeBracketsOpen&&(b===A&&c===C.WORD||I===C.WORD&&a===h.PARENTHESES.LEFT))throw new Error(`'${e}' is not a valid selector`);(!a||Xt(c,a)||r.isAttributeBracketsOpen)&&
m(r,i)}$(u)&&m(r,i),x(u)&&ve(r),Z(u)&&Xt(c,a)&&y(r,d.REGULAR_SELECTOR);break;case he:case ie:case le:case ae:case Ee:case g:case N:case D:case _:case Ot:case bt:case h.CURLY.LEFT:case h.CURLY.RIGHT:case T:case Me:case De:case h.SQUARE.LEFT:if(pe.includes(i)){if(u===null)throw new Error(`'${e}' is not a valid selector`);u=qt(r)}if(u===null)ye(r,i),ce(i,b)&&(r.isAttributeBracketsOpen=!0);else if(O(u)){if(i===h.CURLY.LEFT&&!(r.isAttributeBracketsOpen||r.isRegexpOpen))throw new Error(`'${e}' is not \
a valid selector`);m(r,i),ce(i,b)&&(r.isAttributeBracketsOpen=!0)}else $(u)?(m(r,i),i===g&&r.extendedPseudoNamesStack.length>0&&(b===g&&xn===N?r.isRegexpOpen=!1:b&&b!==N&&(qr(r,b,P(u))?r.isRegexpOpen=!r.isRegexpOpen:r.isRegexpOpen=!1))):x(u)?(ve(r,i),ce(i,b)&&(r.isAttributeBracketsOpen=!0)):Z(u)?pe.includes(i)?y(r,d.REGULAR_SELECTOR,i):r.isRegexpOpen||(u=Ze(r),m(r,i),ce(i,b)&&(r.isAttributeBracketsOpen=!0)):ge(u)&&(y(r,d.SELECTOR),y(r,d.REGULAR_SELECTOR,i),ce(i,b)&&(r.isAttributeBracketsOpen=!0));
break;case h.SQUARE.RIGHT:if(O(u)){if(!r.isAttributeBracketsOpen&&b!==N)throw new Error(`'${e}' is not a valid selector due to '${i}' after '${P(u)}'`);Qr(r)&&(r.isAttributeBracketsOpen=!1,r.attributeBuffer=""),m(r,i)}$(u)&&m(r,i);break;case A:if(zt(a)&&E&&We.includes(E))throw new Error(`${Zt}: '${e}'`);if(u===null){if(a===W)ye(r,ls);else{if(a===Ge||a===Ve)throw new Error(`${Se} before :${a}() pseudo-class`);ye(r,T)}u=X(r)}if(ge(u)&&(y(r,d.SELECTOR),y(r,d.REGULAR_SELECTOR),u=X(r)),O(u)&&((b&&pe.
includes(b)||b===j)&&m(r,T),Qt(r,e,i,a,E)),Z(u)){if(!a)throw new Error(`Invalid colon ':' at the end of selector: '${e}'`);if(Qe(a.toLowerCase()))y(r,d.EXTENDED_SELECTOR);else{if(a.toLowerCase()===U)throw new Error(`${K.INVALID_REMOVE}: '${e}'`);u=Ze(r),Qt(r,e,i,c,E)}}if($(u)){if(V(u)===W&&a&&We.includes(a)&&E===h.PARENTHESES.LEFT)throw new Error(`:xpath() pseudo-class should be the last in selector: '${e}'`);m(r,i)}if(x(u)){if(!a)throw new Error(`Invalid pseudo-class arg at the end of selector:\
 '${e}'`);ve(r,T),Qe(a.toLowerCase())?(k(r,d.SELECTOR),y(r,d.EXTENDED_SELECTOR)):(m(r,i),E===h.PARENTHESES.LEFT&&r.standardPseudoNamesStack.push(a))}break;case h.PARENTHESES.LEFT:$(u)&&(V(u)!==W&&r.isRegexpOpen?m(r,i):(r.extendedPseudoBracketsStack.push(i),r.extendedPseudoBracketsStack.length>r.extendedPseudoNamesStack.length&&m(r,i))),O(u)&&(r.standardPseudoNamesStack.length>0&&(m(r,i),r.standardPseudoBracketsStack.push(i)),r.isAttributeBracketsOpen&&m(r,i)),x(u)&&r.extendedPseudoBracketsStack.
push(i);break;case h.PARENTHESES.RIGHT:if($(u)&&(V(u)!==W&&r.isRegexpOpen?m(r,i):(r.extendedPseudoBracketsStack.pop(),V(u)!==W?(r.extendedPseudoNamesStack.pop(),r.extendedPseudoBracketsStack.length>r.extendedPseudoNamesStack.length?m(r,i):r.extendedPseudoBracketsStack.length>=0&&r.extendedPseudoNamesStack.length>=0&&k(r,d.SELECTOR)):r.extendedPseudoBracketsStack.length<r.extendedPseudoNamesStack.length?r.extendedPseudoNamesStack.pop():m(r,i))),O(u))if(r.isAttributeBracketsOpen)m(r,i);else if(r.standardPseudoNamesStack.
length>0&&r.standardPseudoBracketsStack.length>0){m(r,i),r.standardPseudoBracketsStack.pop();const H=r.standardPseudoNamesStack.pop();if(!H)throw new Error(`Parsing error. Invalid selector: ${e}`);if(Object.values(Ut).includes(H)&&a===A&&E&&Fe.includes(E))throw new Error(`Usage of :${E}() pseudo-class is not allowed after any regular pseudo-element: '${H}'`)}else r.extendedPseudoBracketsStack.pop(),r.extendedPseudoNamesStack.pop(),k(r,d.EXTENDED_SELECTOR),k(r,d.SELECTOR);Z(u)&&(r.extendedPseudoBracketsStack.
pop(),r.extendedPseudoNamesStack.pop(),k(r,d.EXTENDED_SELECTOR),k(r,d.SELECTOR)),x(u)&&r.extendedPseudoNamesStack.length>0&&r.extendedPseudoBracketsStack.length>0&&(r.extendedPseudoBracketsStack.pop(),r.extendedPseudoNamesStack.pop());break;case ne:case oe:case se:throw new Error(`'${e}' is not a valid selector`);case re:if(O(u)&&r.isAttributeBracketsOpen)m(r,i);else throw new Error(`'${e}' is not a valid selector`)}break;default:throw new Error(`Unknown type of token: '${i}'`)}s+=1}if(r.ast===null)
throw new Error(`'${e}' is not a valid selector`);if(r.extendedPseudoNamesStack.length>0||r.extendedPseudoBracketsStack.length>0)throw new Error(`Unbalanced brackets for extended pseudo-class: '${B(r.extendedPseudoNamesStack)}'`);if(r.isAttributeBracketsOpen)throw new Error(`Unbalanced attribute brackets in selector: '${e}'`);return r.shouldOptimize?is(r.ast):r.ast},tt={MutationObserver:window.MutationObserver||window.WebKitMutationObserver};class cs{constructor(){this.nativeNode=window.Node||Node}setGetter(){
var t;this.getter=(t=Object.getOwnPropertyDescriptor(this.nativeNode.prototype,"textContent"))===null||t===void 0?void 0:t.get}}const rt=new cs,us=e=>rt.getter?rt.getter.apply(e):e.textContent||"",er=e=>{let t=e.tagName.toLowerCase();return t+=Array.from(e.attributes).map(r=>`[${r.name}="${e.getAttribute(r.name)}"]`).join(""),t},ds=e=>{if(!(e instanceof Element))throw new Error("Function received argument with wrong type");let t;t=e;const r=[];for(;t&&t.nodeType===Node.ELEMENT_NODE;){let s=t.nodeName.
toLowerCase();if(t.id&&typeof t.id=="string"){s+=`#${t.id}`,r.unshift(s);break}let n=t,o=1;for(;n.previousElementSibling;)n=n.previousElementSibling,n.nodeType===Node.ELEMENT_NODE&&n.nodeName.toLowerCase()===s&&(o+=1);o!==1&&(s+=`:nth-of-type(${o})`),r.unshift(s),t=t.parentElement}return r.join(" > ")},st=e=>e instanceof HTMLElement,tr=(e,t)=>{const{parentElement:r}=e;if(!r)throw new Error(t||"Element does no have parent element");return r},fs=e=>typeof e=="object"&&e!==null&&"message"in e&&typeof e.
message=="string",Es=e=>{if(fs(e))return e;try{return new Error(JSON.stringify(e))}catch{return new Error(String(e))}},w=e=>Es(e).message,R={error:typeof console<"u"&&console.error&&console.error.bind?console.error.bind(window.console):console.error,info:typeof console<"u"&&console.info&&console.info.bind?console.info.bind(window.console):console.info},hs=(e,t)=>{const r=e.indexOf(t,e.length-t.length);return r>=0?e.substring(0,r):e},rr=(e,t,r)=>e&&e.split(t).join(r),ps=e=>{if(e.startsWith(g)&&e.
endsWith(g))return new RegExp(e.slice(1,-1));const t=e.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(t)},Ss=e=>{let t;switch(e){case void 0:t="undefined";break;case null:t="null";break;default:t=e.toString()}return t},ms=e=>{const t=Number(e);let r;if(!Number.isNaN(t))r=t;else switch(e){case"undefined":r=void 0;break;case"null":r=null;break;case"true":r=!0;break;case"false":r=!1;break;default:r=e}return r},sr=/\sVersion\/(\d{2}\.\d)(.+\s|\s)(Safari)\//.test(navigator.userAgent),gs=e=>!(e.
includes("MSIE")||e.includes("Trident/")),Rs=()=>gs(navigator.userAgent),be={BACKGROUND:"background",BACKGROUND_IMAGE:"background-image",CONTENT:"content",OPACITY:"opacity"},nr=".*",ws=/^\s*\/.*\/[gmisuy]*\s*$/,Ts=e=>e.replace(/^(["'])([\s\S]*)\1$/,"$2"),or=e=>{if(!e.includes('url("')){const t=/url\((.*?)\)/g;return e.replace(t,'url("$1")')}return e},ir={regexpArg:e=>{const t=/(\^)?url(\\)?\\\((\w|\[\w)/g;return e.replace(t,'$1url$2\\(\\"?$3')},noneRegexpArg:or},ys=e=>{const t=[".","+","?","$","\
{","}","(",")","[","]","\\","/"],r=new RegExp(`[${t.join("\\")}]`,"g");return e.replace(r,"\\$&")},vs=e=>{let t;return e.startsWith(g)&&e.endsWith(g)?(t=ir.regexpArg(e),t=t.slice(1,-1)):(t=ir.noneRegexpArg(e),t=t.replace(/\\([\\()[\]"])/g,"$1"),t=ys(t),t=rr(t,T,nr)),new RegExp(t,"i")},Os=(e,t)=>{let r="";switch(e){case be.BACKGROUND:case be.BACKGROUND_IMAGE:r=or(t);break;case be.CONTENT:r=Ts(t);break;case be.OPACITY:r=sr?(Math.round(parseFloat(t)*100)/100).toString():t;break;default:r=t}return r},
bs=(e,t,r)=>{const n=window.getComputedStyle(e,r).getPropertyValue(t);return Os(t,n)},nt=(e,t)=>{const r=e.indexOf(t);let s,n;return r>-1?(s=e.substring(0,r).trim(),n=e.substring(r+1).trim()):s=e,{name:s,value:n}},As=(e,t)=>{const{name:r,value:s}=nt(t,j);let n=r,o=s;if(Object.values(Ut).includes(r)||(n=null,o=t),!o)throw new Error(`Required style property argument part is missing in :${e}() arg: '${t}'`);return n&&(n=`${A}${A}${n}`),{regularPseudoElement:n,styleMatchArg:o}},Cs=e=>{const{pseudoName:t,
pseudoArg:r,domElement:s}=e,{regularPseudoElement:n,styleMatchArg:o}=As(t,r),{name:i,value:l}=nt(o,A);if(!i||!l)throw new Error(`Required property name or value is missing in :${t}() arg: '${o}'`);let c;try{c=vs(l)}catch(f){throw R.error(w(f)),new Error(`Invalid argument of :${t}() pseudo-class: '${o}'`)}const a=bs(s,i,n);return c&&c.test(a)},Ps=e=>!(e.includes(g)||!/^[\w-]+$/.test(e)),Ae=function(e){let t=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!1,r;if(e.length>1&&e.startsWith(_)&&
e.endsWith(_)&&(e=e.slice(1,-1)),e==="")throw new Error("Argument should be specified. Empty arg is invalid.");if(e.startsWith(g)&&e.endsWith(g))if(e.length>2)r=ps(e);else throw new Error(`Invalid regexp: '${e}'`);else if(e.includes(T)){if(e===T&&!t)throw new Error(`Argument should be more specific than ${e}`);r=rr(e,T,nr),r=new RegExp(r)}else{if(!Ps(e))throw new Error(`Invalid argument: '${e}'`);r=e}return r},lr=(e,t)=>{const{name:r,value:s}=nt(t,q);if(!r)throw new Error(`Required attribute nam\
e is missing in :${e} arg: ${t}`);return{rawName:r,rawValue:s}},Ls=e=>{const{pseudoName:t,pseudoArg:r,domElement:s}=e,n=s.attributes;if(n.length===0)return!1;const{rawName:o,rawValue:i}=lr(t,r);let l;try{l=Ae(o)}catch(f){const E=w(f);throw R.error(E),new SyntaxError(E)}let c=!1,a=0;for(;a<n.length&&!c;){const f=n[a];if(!f)break;const E=l instanceof RegExp?l.test(f.name):l===f.name;if(!i)c=E;else{let p;try{p=Ae(i)}catch(b){const F=w(b);throw R.error(F),new SyntaxError(F)}const I=p instanceof RegExp?
p.test(f.value):p===f.value;c=E&&I}a+=1}return c},_s=e=>{e.length>1&&e.startsWith(_)&&e.endsWith(_)&&(e=e.slice(1,-1));const t=e.split(Ie),r=[];let s="",n=!1,o=0;for(;o<t.length;){const l=me(t,o,`Invalid pseudo-class arg: '${e}'`);l.startsWith(g)&&l.endsWith(g)&&l.length>2?r.push(l):l.startsWith(g)?(n=!0,s+=l):l.endsWith(g)?(n=!1,s+=`.${l}`,r.push(s),s=""):n?s+=l:r.push(l),o+=1}if(s.length>0)throw new Error(`Invalid regexp property pattern '${e}'`);return r.map(l=>{if(l.length===0)throw new Error(
`Empty pattern '${l}' is invalid in chain '${e}'`);let c;try{c=Ae(l,!0)}catch(a){throw R.error(w(a)),new Error(`Invalid property pattern '${l}' in property chain '${e}'`)}return c})},ot=function(e,t){let r=arguments.length>2&&arguments[2]!==void 0?arguments[2]:[];const s=J(t);if(t.length===1){let o;for(o in e)s instanceof RegExp?s.test(o)&&r.push({base:e,prop:o,value:e[o]}):s===o&&r.push({base:e,prop:s,value:e[o]});return r}if(s instanceof RegExp){const o=t.slice(1),i=[];for(const l in e)s.test(
l)&&i.push(l);i.forEach(l=>{var c;const a=(c=Object.getOwnPropertyDescriptor(e,l))===null||c===void 0?void 0:c.value;ot(a,o,r)})}if(e&&typeof s=="string"){var n;const o=(n=Object.getOwnPropertyDescriptor(e,s))===null||n===void 0?void 0:n.value;t=t.slice(1),o!==void 0&&ot(o,t,r)}return r},Ns=e=>{const{pseudoName:t,pseudoArg:r,domElement:s}=e,{rawName:n,rawValue:o}=lr(t,r);if(n.includes("\\/")||n.includes("\\."))throw new Error(`Invalid :${t} name pattern: ${n}`);let i;try{i=_s(n)}catch(f){const E=w(
f);throw R.error(E),new SyntaxError(E)}const l=ot(s,i);if(l.length===0)return!1;let c=!0;if(o){let f;try{f=Ae(o)}catch(E){const p=w(E);throw R.error(p),new SyntaxError(p)}if(f)for(let E=0;E<l.length;E+=1){var a;const p=(a=l[E])===null||a===void 0?void 0:a.value;if(f instanceof RegExp)c=f.test(Ss(p));else{if(p==="null"||p==="undefined"){c=f===p;break}c=ms(f)===p}if(c)break}}return c},$s=e=>{const{pseudoName:t,pseudoArg:r,domElement:s}=e,n=us(s);let o,i=r;if(i.startsWith(g)&&ws.test(i)){const l=i.
lastIndexOf("/"),c=i.substring(l+1);i=i.substring(0,l+1).slice(1,-1).replace(/\\([\\"])/g,"$1");let a;try{a=new RegExp(i,c)}catch{throw new Error(`Invalid argument of :${t}() pseudo-class: ${r}`)}o=a.test(n)}else i=i.replace(/\\([\\()[\]"])/g,"$1"),o=n.includes(i);return o},ks=(e,t)=>{const r=Number(e);if(Number.isNaN(r)||r<1||r>=256)throw new Error(`Invalid argument of :${t} pseudo-class: '${e}'`);return r},Is=(e,t,r)=>{let s=null,n=0;for(;n<t;){if(s=e.parentElement,!s)throw new Error(`Out of D\
OM: Argument of :${r}() pseudo-class is too big \u2014 '${t}'.`);e=s,n+=1}return s},Ms=e=>{let t;try{document.querySelectorAll(e),t=!0}catch{t=!1}return t},Ds=(e,t,r)=>{let s;try{s=e(t)}catch(n){throw R.error(w(n)),new Error(r)}return s},Ce=(e,t,r)=>`${Dr} ${e}, may be invalid :${t}() pseudo-class arg: '${r}'`,Us=(e,t,r)=>{let s,n,o;switch(t){case Ue:case Be:case xe:o=$s,s={pseudoName:t,pseudoArg:r,domElement:e},n=Ce("text content",t,r);break;case Pt:case _t:case Lt:o=Cs,s={pseudoName:t,pseudoArg:r,
domElement:e},n=Ce("style",t,r);break;case Nt:o=Ls,s={domElement:e,pseudoName:t,pseudoArg:r},n=Ce("attributes",t,r);break;case $t:o=Ns,s={domElement:e,pseudoName:t,pseudoArg:r},n=Ce("properties",t,r);break;default:throw new Error(`Unknown absolute pseudo-class :${t}()`)}return Ds(o,s,n)},Pe={nthAncestor:(e,t,r)=>{const s=ks(t,r);return e.map(o=>{let i=null;try{i=Is(o,s,r)}catch(l){R.error(w(l))}return i}).filter(st)},xpath:(e,t)=>{const r=e.map(s=>{const n=[];let o;try{o=document.evaluate(t,s,null,
window.XPathResult.UNORDERED_NODE_ITERATOR_TYPE,null)}catch(l){throw R.error(w(l)),new Error(`Invalid argument of :xpath() pseudo-class: '${t}'`)}let i=o.iterateNext();for(;i;)st(i)&&n.push(i),i=o.iterateNext();return n});return je(r)},upward:(e,t)=>{if(!Ms(t))throw new Error(`Invalid argument of :upward pseudo-class: '${t}'`);return e.map(s=>{const n=s.parentElement;return n?n.closest(t):null}).filter(st)}},Le=`${Ke}${ie}`,it=`${Ke}${he}`,lt=(e,t)=>zr(e.children,`RegularSelector is missing for \
:${t}() pseudo-class`),Bs=e=>{const{element:t,relativeSelectorList:r,pseudoName:s}=e;return r.children.every(n=>{const o=lt(n,s);let i="",l=null;const c=P(o);if(c.startsWith(le)||c.startsWith(ae)){l=t.parentElement;const f=er(t);i=`${Le}${f}${c}`}else c===T?(l=t,i=`${it}${T}`):(i=`${it}${c}`,l=t);if(!l)throw new Error(`Selection by :${s}() pseudo-class is not possible`);let a;try{a=Ne(n,l,i)}catch(f){throw R.error(w(f)),new Error(`Invalid selector for :${s}() pseudo-class: '${c}'`)}return a.length>
0})},xs=e=>{const{element:t,relativeSelectorList:r,pseudoName:s}=e;return r.children.some(n=>{const o=lt(n,s),i=tr(t,`Selection by :${s}() pseudo-class is not possible`),l=`${Le}${P(o)}`;let c;try{c=Ne(n,i,l)}catch{return!1}return c.includes(t)})},Vs=e=>{const{element:t,relativeSelectorList:r,pseudoName:s}=e;return r.children.every(n=>{const o=lt(n,s),i=tr(t,`Selection by :${s}() pseudo-class is not possible`),l=`${Le}${P(o)}`;let c;try{c=Ne(n,i,l)}catch(a){throw R.error(w(a)),new Error(`Invalid\
 selector for :${s}() pseudo-class: '${P(o)}'`)}return!c.includes(t)})},_e=(e,t,r)=>{const s=r||P(e);let n=[];try{n=Array.from(t.querySelectorAll(s))}catch(o){throw new Error(`Error: unable to select by '${s}' \u2014 ${w(o)}`)}return n},Gs=(e,t)=>{let r=[];const s=we(t),n=V(s);if(Te(n)){const o=P(s,`Missing arg for :${n}() pseudo-class`);if(n===Ve)r=Pe.nthAncestor(e,o,n);else if(n===W){try{document.createExpression(o,null)}catch{throw new Error(`Invalid argument of :${n}() pseudo-class: '${o}'`)}
r=Pe.xpath(e,o)}else n===Ge?Number.isNaN(Number(o))?r=Pe.upward(e,o):r=Pe.nthAncestor(e,o,n):r=e.filter(i=>Us(i,n,o))}else if(jt(n)){const o=qe(s);let i;switch(n){case kt:case It:i=l=>Bs({element:l,relativeSelectorList:o,pseudoName:n});break;case He:i=l=>xs({element:l,relativeSelectorList:o,pseudoName:n});break;case Ye:i=l=>Vs({element:l,relativeSelectorList:o,pseudoName:n});break;default:throw new Error(`Unknown relative pseudo-class: '${n}'`)}r=e.filter(i)}else throw new Error(`Unknown extende\
d pseudo-class: '${n}'`);return r},Fs=(e,t)=>{let r=[];const s=P(t);return s.startsWith(ie)?r=e.map(n=>{const o=`${Ke}${s}`;return _e(t,n,o)}):s.startsWith(le)||s.startsWith(ae)?r=e.map(n=>{const o=n.parentElement;if(!o)return[];const i=er(n),l=`${Le}${i}${s}`;return _e(t,o,l)}):r=e.map(n=>{const o=`${it}${P(t)}`;return _e(t,n,o)}),je(r)},Ne=(e,t,r)=>{let s=[],n=0;for(;n<e.children.length;){const o=me(e.children,n,"selectorNodeChild should be specified");n===0?s=_e(o,t,r):ee(o)?s=Gs(s,o):O(o)&&(s=
Fs(s,o)),n+=1}return s},ar=function(e){let t=arguments.length>1&&arguments[1]!==void 0?arguments[1]:document;const r=[];return e.children.forEach(n=>{r.push(...Ne(n,t))}),[...new Set(je(r))]};class Hs{constructor(){this.astCache=new Map}saveAstToCache(t,r){this.astCache.set(t,r)}getAstFromCache(t){return this.astCache.get(t)||null}getSelectorAst(t){let r=this.getAstFromCache(t);return r||(r=as(t)),this.saveAstToCache(t,r),r}querySelectorAll(t){const r=this.getSelectorAst(t);return ar(r)}}const at=new Hs,
Ys=e=>{const t={};return e.forEach(r=>{const[s,n]=r;t[s]=n}),t},cr="debug",ct=e=>{const t=`${A}${U}${h.PARENTHESES.LEFT}${h.PARENTHESES.RIGHT}`,r=`${A}${U}${h.PARENTHESES.LEFT}`;let s,n=!1;const o=e.indexOf(t);if(o===0)throw new Error(`${K.NO_TARGET_SELECTOR}: '${e}'`);if(o>0){if(o!==e.lastIndexOf(t))throw new Error(`${K.MULTIPLE_USAGE}: '${e}'`);if(o+t.length<e.length)throw new Error(`${K.INVALID_POSITION}: '${e}'`);s=e.substring(0,o),n=!0}else{if(e.includes(r))throw new Error(`${K.INVALID_REMOVE}\
: '${e}'`);s=e}return{selector:s,stylesOfSelector:n?[{property:U,value:Q}]:[]}},ur=(e,t)=>{let r=e.trim();if(r.startsWith(Bt))throw new Error(`${Vt}: '${r}'.`);let s;try{s=ct(r)}catch(l){throw R.error(w(l)),new Error(`${K.INVALID_REMOVE}: '${r}'`)}let n=[],o=!1,i;try{r=s.selector,n=s.stylesOfSelector,i=t.getSelectorAst(r),o=!0}catch{o=!1}return{success:o,selector:r,ast:i,stylesOfSelector:n}},dr=()=>new Map,ut=(e,t)=>{const{selector:r,ast:s,rawStyles:n}=t;if(!n)throw new Error(`No style declarati\
on for selector: '${r}'`);if(!s)throw new Error(`No ast parsed for selector: '${r}'`);const o=e.get(r);o?o.styles.push(...n):e.set(r,{ast:s,styles:n})},Ws=e=>e.some(t=>t.property===U&&t.value===Q),Ks=e=>{const t=e.find(r=>r.property===cr);return t?.value},Xs=e=>{const{selector:t,ast:r,rawStyles:s}=e;if(!r)throw new Error(`AST should be parsed for selector: '${t}'`);if(!s)throw new Error(`Styles should be parsed for selector: '${t}'`);const n={selector:t,ast:r},o=Ks(s),i=Ws(s);let l=s;if(o&&(l=s.
filter(c=>c.property!==cr),(o===Q||o===xt)&&(n.debug=o)),i){n.style={[U]:Q};const c=l.find(a=>a.property===Xe);c&&(n.style[Xe]=c.value)}else if(l.length>0){const c=l.map(f=>{const{property:E,value:p}=f;return[E,p]}),a=Ys(c);n.style=a}return n},fr=e=>{const t=[];return e.forEach((r,s)=>{const n=s,{ast:o,styles:i}=r;t.push(Xs({selector:n,ast:o,rawStyles:i}))}),t},zs=e=>{const t=e.trim();return ze(t,kr)},ue={PROPERTY:"property",VALUE:"value"},$e=e=>e.bufferValue!==""&&e.valueQuoteMark!==null,Er=e=>{
e.styles.push({property:e.bufferProperty.trim(),value:e.bufferValue.trim()}),e.bufferProperty="",e.bufferValue=""},js=(e,t,r)=>{const{value:s}=r;switch(r.type){case C.WORD:if(e.bufferProperty.length>0)throw new Error(`Invalid style property in style block: '${t}'`);e.bufferProperty+=s;break;case C.MARK:if(s===A){if(e.bufferProperty.trim().length===0)throw new Error(`Missing style property before ':' in style block: '${t}'`);e.bufferProperty=e.bufferProperty.trim(),e.processing=ue.VALUE}else if(!At.
includes(s))throw new Error(`Invalid style declaration in style block: '${t}'`);break;default:throw new Error(`Unsupported style property character: '${s}' in style block: '${t}'`)}},qs=(e,t,r)=>{const{value:s}=r;if(r.type===C.WORD)e.bufferValue+=s;else switch(s){case A:if(!$e(e))throw new Error(`Invalid style value for property '${e.bufferProperty}' in style block: '${t}'`);e.bufferValue+=s;break;case Ee:$e(e)?e.bufferValue+=s:(Er(e),e.processing=ue.PROPERTY);break;case D:case _:e.valueQuoteMark===
null?e.valueQuoteMark=s:!e.bufferValue.endsWith(N)&&e.valueQuoteMark===s&&(e.valueQuoteMark=null),e.bufferValue+=s;break;case N:if(!$e(e))throw new Error(`Invalid style value for property '${e.bufferProperty}' in style block: '${t}'`);e.bufferValue+=s;break;case M:case re:case se:case ne:case oe:e.bufferValue.length>0&&(e.bufferValue+=s);break;default:throw new Error(`Unknown style declaration token: '${s}'`)}},Qs=e=>{const t=e.trim(),r=zs(t),s={processing:ue.PROPERTY,styles:[],bufferProperty:"",
bufferValue:"",valueQuoteMark:null};let n=0;for(;n<r.length;){const o=r[n];if(!o)break;if(s.processing===ue.PROPERTY)js(s,t,o);else if(s.processing===ue.VALUE)qs(s,t,o);else throw new Error("Style declaration parsing failed");n+=1}if($e(s))throw new Error(`Unbalanced style declaration quotes in style block: '${t}'`);if(s.bufferProperty.length>0){if(s.bufferValue.length===0)throw new Error(`Missing style value for property '${s.bufferProperty}' in style block '${t}'`);Er(s)}if(s.styles.length===0)
throw new Error(L.NO_STYLE);return s.styles},Js=e=>{const t=[];for(let r=0;r<e.length;r+=1)e[r]===h.CURLY.LEFT&&t.push(r);return t},Zs=(e,t)=>{var r;const s=e.trim();if(s.includes(`${g}${T}`)&&s.includes(`${T}${g}`))throw new Error(L.NO_COMMENT);const n=Js(s);if(J(n)===0)throw new Error(Se);let o;if(n.length>0&&!s.includes(h.CURLY.RIGHT))throw new Error(`${L.NO_STYLE} OR ${L.UNCLOSED_STYLE}`);if(n.length===0||!s.includes(h.CURLY.RIGHT))try{if(o=ur(s,t),o.success){var i;if(((i=o.stylesOfSelector)===
null||i===void 0?void 0:i.length)===0)throw new Error(L.NO_STYLE_OR_REMOVE);return{selector:o.selector.trim(),ast:o.ast,rawStyles:o.stylesOfSelector}}else throw new Error("Invalid selector")}catch(E){throw new Error(w(E))}let l,c;const a={selector:""};for(let E=n.length-1;E>-1;E-=1){const p=n[E];if(!p)throw new Error(`Impossible to continue, no '{' to process for rule: '${s}'`);if(l=s.slice(0,p),c=s.slice(p+1,s.length-1),o=ur(l,t),o.success){var f;a.selector=o.selector.trim(),a.ast=o.ast,a.rawStyles=
o.stylesOfSelector;const I=Qs(c);(f=a.rawStyles)===null||f===void 0||f.push(...I);break}else continue}if(((r=a.selector)===null||r===void 0?void 0:r.length)===0)throw new Error("Selector in not valid");return a},en=(e,t)=>{const r=dr(),s=[];return[...new Set(e.map(o=>o.trim()))].forEach(o=>{try{ut(r,Zs(o,t))}catch(i){const l=w(i);s.push(`'${o}' - error: '${l}'`)}}),s.length>0&&R.info(`Invalid rules:
  ${s.join(`
  `)}`),fr(r)},hr=/[;}]/g,pr=/[;:}]/g,Sr=/\S/g,mr=e=>{e.rawRuleData={selector:""}},tn=(e,t)=>{let r=e.selectorBuffer.trim();if(r.startsWith(Bt))throw new Error(`${Vt}: '${r}'.`);let s;try{s=ct(r)}catch(l){throw R.error(w(l)),new Error(`${K.INVALID_REMOVE}: '${r}'`)}if(e.nextIndex===-1){if(r===s.selector)throw new Error(`${L.NO_STYLE_OR_REMOVE}: '${e.cssToParse}'`);e.cssToParse=""}let n=[],o=!1,i;try{r=s.selector,n=s.stylesOfSelector,i=t.getSelectorAst(r),o=!0}catch{o=!1}return e.nextIndex>0&&(e.
cssToParse=e.cssToParse.slice(e.nextIndex)),{success:o,selector:r,ast:i,stylesOfSelector:n}},gr=(e,t)=>{pr.lastIndex=e.nextIndex;let r=pr.exec(e.cssToParse);if(r===null)throw new Error(`${L.INVALID_STYLE}: '${e.cssToParse}'`);let s=r.index,n=r[0];if(n===h.CURLY.RIGHT){if(e.cssToParse.slice(e.nextIndex,s).trim().length===0){if(t.length===0)throw new Error(`${L.NO_STYLE}: '${e.cssToParse}'`)}else throw new Error(`${L.INVALID_STYLE}: '${e.cssToParse}'`);return s}if(n===A){const o=s;if(hr.lastIndex=
o,r=hr.exec(e.cssToParse),r===null)throw new Error(`${L.UNCLOSED_STYLE}: '${e.cssToParse}'`);s=r.index,n=r[0];const i=e.cssToParse.slice(e.nextIndex,o).trim();if(i.length===0)throw new Error(`${L.NO_PROPERTY}: '${e.cssToParse}'`);const l=e.cssToParse.slice(o+1,s).trim();if(l.length===0)throw new Error(`${L.NO_VALUE}: '${e.cssToParse}'`);if(t.push({property:i,value:l}),n===h.CURLY.RIGHT)return s}return e.cssToParse=e.cssToParse.slice(s+1),e.nextIndex=0,gr(e,t)},rn=e=>{const t=[],r=gr(e,t);Sr.lastIndex=
r+1;const s=Sr.exec(e.cssToParse);if(s===null)return e.cssToParse="",t;const n=s.index;return e.cssToParse=e.cssToParse.slice(n),t},sn=(e,t)=>{const r=e.trim();if(r.includes(`${g}${T}`)&&r.includes(`${T}${g}`))throw new Error(`${L.NO_COMMENT} in stylesheet: '${r}'`);const s={isSelector:!0,nextIndex:0,cssToParse:r,selectorBuffer:"",rawRuleData:{selector:""}},n=dr();let o;for(;s.cssToParse;)if(s.isSelector){if(s.nextIndex=s.cssToParse.indexOf(h.CURLY.LEFT),s.selectorBuffer.length===0&&s.nextIndex===
0)throw new Error(`${L.NO_SELECTOR}: '${s.cssToParse}'`);s.nextIndex===-1?s.selectorBuffer=s.cssToParse:s.selectorBuffer+=s.cssToParse.slice(0,s.nextIndex),o=tn(s,t),o.success?(s.rawRuleData.selector=o.selector.trim(),s.rawRuleData.ast=o.ast,s.rawRuleData.rawStyles=o.stylesOfSelector,s.isSelector=!1,s.nextIndex===-1?(ut(n,s.rawRuleData),mr(s)):(s.nextIndex=1,s.selectorBuffer="")):(s.selectorBuffer+=h.CURLY.LEFT,s.cssToParse=s.cssToParse.slice(1))}else{var i;const l=rn(s);(i=s.rawRuleData.rawStyles)===
null||i===void 0||i.push(...l),ut(n,s.rawRuleData),s.nextIndex=0,mr(s),s.isSelector=!0}return fr(n)},dt=e=>typeof e=="number"&&!Number.isNaN(e);class de{constructor(t){this.callback=t,this.executeCallback=this.executeCallback.bind(this)}executeCallback(){this.lastRunTime=performance.now(),dt(this.timerId)&&(clearTimeout(this.timerId),delete this.timerId),this.callback()}run(){if(!dt(this.timerId)){if(dt(this.lastRunTime)){const t=performance.now()-this.lastRunTime;if(t<de.THROTTLE_DELAY_MS){this.
timerId=window.setTimeout(this.executeCallback,de.THROTTLE_DELAY_MS-t);return}}this.timerId=window.setTimeout(this.executeCallback)}}}v(de,"THROTTLE_DELAY_MS",150);const nn=10,on=["mouseover","mouseleave","mouseenter","mouseout"],Rr=["keydown","keypress","keyup","auxclick","click","contextmenu","dblclick","mousedown","mouseenter","mouseleave","mousemove","mouseover","mouseout","mouseup","pointerlockchange","pointerlockerror","select","wheel"],ln=["wheel"];class an{constructor(){v(this,"getLastEv\
entType",()=>this.lastEventType),v(this,"getTimeSinceLastEvent",()=>this.lastEventTime?Date.now()-this.lastEventTime:null),this.trackedEvents=sr?Rr.filter(t=>!ln.includes(t)):Rr,this.trackedEvents.forEach(t=>{document.documentElement.addEventListener(t,this.trackEvent,!0)})}trackEvent(t){this.lastEventType=t.type,this.lastEventTime=Date.now()}isIgnoredEventType(){const t=this.getLastEventType(),r=this.getTimeSinceLastEvent();return!!t&&on.includes(t)&&!!r&&r<nn}stopTracking(){this.trackedEvents.
forEach(t=>{document.documentElement.removeEventListener(t,this.trackEvent,!0)})}}function cn(e){return!e.some(t=>t.type!=="attributes")}function un(e){e.isDomObserved||(e.isDomObserved=!0,e.domMutationObserver=new tt.MutationObserver(t=>{if(!t||t.length===0)return;const r=new an;r.isIgnoredEventType()&&cn(t)||(e.eventTracker=r,e.scheduler.run())}),e.domMutationObserver.observe(document,{childList:!0,subtree:!0,attributes:!0,attributeFilter:["id","class"]}))}function wr(e){e.isDomObserved&&(e.isDomObserved=
!1,e.domMutationObserver&&e.domMutationObserver.disconnect(),e.eventTracker&&e.eventTracker.stopTracking())}const dn=/^("|')adguard.+?/,fn=(e,t)=>{const{node:r}=t;t.removed=!0;const s=ds(r),n=e.removalsStatistic[s]||0;if(n>Gt){R.error(`ExtendedCss: infinite loop protection for selector: '${s}'`);return}r.parentElement&&(r.parentElement.removeChild(r),e.removalsStatistic[s]=n+1)},Tr=(e,t)=>{e instanceof HTMLElement&&Object.keys(t).forEach(r=>{if(typeof e.style.getPropertyValue(r.toString())<"u"){
let s=t[r];if(!s||r===Xe&&s.match(dn))return;s=hs(s.trim(),"!important").trim(),e.style.setProperty(r,s,"important")}})},En=e=>"node"in e&&"rules"in e&&e.rules instanceof Array,hn=e=>"node"in e&&"originalStyle"in e&&"rules"in e&&e.rules instanceof Array,yr=(e,t)=>{if(t.protectionObserver)return;let r;if(e.beforeStyleApplied){if(!En(t))throw new Error("Returned IAffectedElement should have 'node' and 'rules' properties");if(r=e.beforeStyleApplied(t),!r)throw new Error("Callback 'beforeStyleApplie\
d' should return IAffectedElement")}else r=t;if(!hn(r))throw new Error("Returned IAffectedElement should have 'node' and 'rules' properties");const{node:s,rules:n}=r;for(let o=0;o<n.length;o+=1){const i=n[o],l=i?.selector,c=i?.style,a=i?.debug;if(c){if(c[U]===Q){fn(e,r);return}Tr(s,c)}else if(!a)throw new Error(`No style declaration in rule for selector: '${l}'`)}},vr=e=>{e.protectionObserver&&e.protectionObserver.disconnect(),e.node.style.cssText=e.originalStyle};class pn{constructor(t){this.styleProtectionCount=
0,this.observer=new tt.MutationObserver(r=>{r.length&&(this.styleProtectionCount+=1,t(r,this))})}observe(t,r){this.styleProtectionCount<Gt?this.observer.observe(t,r):R.error("ExtendedCss: infinite loop protection for style")}disconnect(){this.observer.disconnect()}}const Or={attributes:!0,attributeOldValue:!0,attributeFilter:["style"]},Sn=e=>(r,s)=>{if(!r[0])return;const{target:n}=r[0];s.disconnect(),e.forEach(o=>{Tr(n,o)}),s.observe(n,Or)},mn=(e,t)=>{if(!tt.MutationObserver)return null;const r=[];
t.forEach(n=>{const{style:o}=n;o&&r.push(o)});const s=new pn(Sn(r));return s.observe(e,Or),s},gn=4;class Rn{constructor(){this.appliesTimings=[],this.appliesCount=0,this.timingsSum=0,this.meanTiming=0,this.squaredSum=0,this.standardDeviation=0}push(t){this.appliesTimings.push(t),this.appliesCount+=1,this.timingsSum+=t,this.meanTiming=this.timingsSum/this.appliesCount,this.squaredSum+=t*t,this.standardDeviation=Math.sqrt(this.squaredSum/this.appliesCount-Math.pow(this.meanTiming,2))}}const fe=e=>Number(
e.toFixed(gn)),wn=e=>({appliesTimings:e.appliesTimings.map(t=>fe(t)),appliesCount:fe(e.appliesCount),timingsSum:fe(e.timingsSum),meanTiming:fe(e.meanTiming),standardDeviation:fe(e.standardDeviation)}),Tn=e=>{if(e.areTimingsPrinted)return;e.areTimingsPrinted=!0;const t={};e.parsedRules.forEach(r=>{if(r.timingStats){const{selector:s,style:n,debug:o,matchedElements:i}=r;if(!n&&!o)throw new Error(`Rule should have style declaration for selector: '${s}'`);const l={selectorParsed:s,timings:wn(r.timingStats)};
n&&n[U]===Q?l.removed=!0:(l.styleApplied=n||null,l.matchedElements=i),t[s]=l}}),Object.keys(t).length!==0&&R.info(`[ExtendedCss] Timings in milliseconds for %o:
%o`,window.location.href,t)},yn=(e,t)=>e.find(r=>r.node===t),vn=(e,t)=>{const r=!!t.debug||e.debug;let s;r&&(s=performance.now());const{ast:n}=t,o=[];try{o.push(...ar(n))}catch(i){e.debug&&R.error(w(i))}if(o.forEach(i=>{let l=yn(e.affectedElements,i);if(l)l.rules.push(t),yr(e,l);else{const c=i.style.cssText;l={node:i,rules:[t],originalStyle:c,protectionObserver:null},yr(e,l),e.affectedElements.push(l)}}),r&&s){const i=performance.now()-s;t.timingStats||(t.timingStats=new Rn),t.timingStats.push(i)}
return o},br=e=>{const t=[];wr(e),e.parsedRules.forEach(s=>{const n=vn(e,s);Array.prototype.push.apply(t,n),s.debug&&(s.matchedElements=n)});let r=e.affectedElements.length;for(;r;){const s=e.affectedElements[r-1];if(!s)break;t.includes(s.node)?s.removed||s.protectionObserver||(s.protectionObserver=mn(s.node,s.rules)):(vr(s),e.affectedElements.splice(r-1,1)),r-=1}un(e),Tn(e)};class ft{constructor(t){if(!t)throw new Error("ExtendedCss configuration should be provided.");if(this.applyRulesCallbackListener=
this.applyRulesCallbackListener.bind(this),this.context={beforeStyleApplied:t.beforeStyleApplied,debug:!1,affectedElements:[],isDomObserved:!1,removalsStatistic:{},parsedRules:[],scheduler:new de(this.applyRulesCallbackListener)},!Rs()){R.error("Browser is not supported by ExtendedCss");return}if(!t.styleSheet&&!t.cssRules)throw new Error("ExtendedCss configuration should have 'styleSheet' or 'cssRules' defined.");if(t.styleSheet)try{this.context.parsedRules.push(...sn(t.styleSheet,at))}catch(r){
throw new Error(`Pass the rules as configuration.cssRules since configuration.styleSheet cannot be parsed because of: '${w(r)}'`)}if(t.cssRules&&this.context.parsedRules.push(...en(t.cssRules,at)),this.context.debug=t.debug||this.context.parsedRules.some(r=>r.debug===xt),this.context.beforeStyleApplied&&typeof this.context.beforeStyleApplied!="function")throw new Error(`Invalid configuration. Type of 'beforeStyleApplied' should be a function, received: '${typeof this.context.beforeStyleApplied}'`)}applyRulesCallbackListener(){
br(this.context)}init(){rt.setGetter()}apply(){br(this.context),document.readyState!=="complete"&&document.addEventListener("DOMContentLoaded",this.applyRulesCallbackListener,!1)}dispose(){wr(this.context),this.context.affectedElements.forEach(t=>{vr(t)}),document.removeEventListener("DOMContentLoaded",this.applyRulesCallbackListener,!1)}getAffectedElements(){return this.context.affectedElements}static query(t){let r=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!0;if(typeof t!="string")
throw new Error("Selector should be defined as a string.");const s=performance.now();try{return at.querySelectorAll(t)}finally{const n=performance.now();r||R.info(`[ExtendedCss] Elapsed: ${Math.round((n-s)*1e3)} \u03BCs.`)}}static validate(t){try{const{selector:r}=ct(t);return ft.query(r),{ok:!0,error:null}}catch(r){return{ok:!1,error:`Error: Invalid selector: '${t}' -- ${w(r)}`}}}}var z;(function(e){e[e.Debug=2]="Debug",e[e.Info=1]="Info",e[e.Error=0]="Error"})(z||(z={}));const On=()=>`[${new Date().
toISOString()}]`,bn=e=>{if(e instanceof Error)return e.stack||e.message||String(e);if(typeof e=="string")return e;try{return JSON.stringify(e)}catch{return String(e)}},Et=(e,t)=>[On(),e,...t.map(bn)].join(" ");class An{constructor(t,r){_defineProperty2(this,"prefix","[Safari Extension]"),_defineProperty2(this,"loggingLevel",z.Info),this.prefix=t,this.loggingLevel=r}get level(){return this.loggingLevel}set level(t){this.loggingLevel=t}debug(){if(this.loggingLevel>=z.Debug){for(var t=arguments.length,
r=new Array(t),s=0;s<t;s++)r[s]=arguments[s];console.debug(Et(this.prefix,r))}}info(){if(this.loggingLevel>=z.Info){for(var t=arguments.length,r=new Array(t),s=0;s<t;s++)r[s]=arguments[s];console.info(Et(this.prefix,r))}}error(){if(this.loggingLevel>=z.Error){for(var t=arguments.length,r=new Array(t),s=0;s<t;s++)r[s]=arguments[s];console.error(Et(this.prefix,r))}}}class Cn{constructor(){_defineProperty2(this,"level",z.Debug)}debug(){}info(){}error(){}}let te=new Cn;class Pn{get level(){return te.
level}set level(t){te.level=t}debug(){te.debug(...arguments)}info(){te.info(...arguments)}error(){te.error(...arguments)}}const Ln=e=>{te=e},ht=new Pn,Gn="4.3.0",Ar=e=>e.map(t=>t.trim()).filter(t=>t.length>0).map(t=>t.at(-1)!=="}"?`${t} {display:none!important;}`:t),_n=e=>{const t=document.createElement("script");return t.setAttribute("type","text/javascript"),t.textContent=e,(document.head||document.documentElement).appendChild(t),t.parentNode?(t.parentNode.removeChild(t),!1):!0},Nn=e=>{const t=new Blob(
[e],{type:"text/javascript"}),r=URL.createObjectURL(t),s=document.createElement("script");return s.src=r,(document.head||document.documentElement).appendChild(s),URL.revokeObjectURL(r),s.parentNode?(s.parentNode.removeChild(s),!1):!0},Cr=function(){let e=arguments.length>0&&arguments[0]!==void 0?arguments[0]:[];e.unshift("( function () { try {"),e.push(";document.currentScript && document.currentScript.remove();"),e.push("} catch (ex) { console.error('Error executing AG js: ' + ex); } })();");const t=e.
join(`\r
`);_n(t)||Nn(t)||console.warn("[wBlock] Page script injection was blocked; continuing without page-context scripts.")},$n=e=>{const{MutationObserver:t}=window;if(!t)return;new t(s=>{for(let n=0;n<s.length;n+=1){const o=s[n];if(e.hasAttribute("mod")&&e.getAttribute("mod")==="inner"){e.removeAttribute("mod");break}e.setAttribute("mod","inner");let i=!1;if(o.removedNodes.length>0)for(let l=0;l<o.removedNodes.length;l+=1)i=!0,e.appendChild(o.removedNodes[l]);else o.oldValue&&(i=!0,e.textContent=o.oldValue);
i||e.removeAttribute("mod")}}).observe(e,{childList:!0,characterData:!0,subtree:!0,characterDataOldValue:!0})};class kn{applyConfiguration(t){let r=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!1;this.insertCss(t.css),this.insertExtendedCss(t.extendedCss),this.runScriptlets(t.scriptlets,r),this.runScripts(t.js)}insertCss(t){if(!(!t||!t.length))try{const r=document.createElement("style");if(r.setAttribute("type","text/css"),(document.head||document.documentElement).appendChild(r),r.sheet){
const s=Ar(t);for(const n of s)r.sheet.insertRule(n)}$n(r)}catch(r){ht.error("Failed to insert CSS",r)}}insertExtendedCss(t){if(!(!t||!t.length))try{const r=Ar(t);new ft({cssRules:r}).apply()}catch(r){ht.error("Failed to insert extended CSS",r)}}runScripts(t){!t||t.length===0||Cr(t)}runScriptlets(t){if(!(!t||!t.length))for(const r of t){if(!r||typeof r.code!="string"||!r.code){ht.error("Missing precompiled scriptlet source",r&&r.name);continue}Cr([r.code])}}}var ke;(function(e){e.InitContentScript=
"InitContentScript"})(ke||(ke={}));const Pr=new An("[wBlock Scripts]",z.Error);if(Ln(Pr),!S||!S.runtime||!S.runtime.sendMessage)return;let G=!1;const In=/just a moment|verifying you are human|attention required|enable cookies/i,Lr=e=>In.test(e||""),pt=()=>{G||(G=!0,console.info("[wBlock] Cloudflare challenge context detected \u2014 skipping content script."))},Mn=()=>{try{const e=window.location&&typeof window.location.hostname=="string"?window.location.hostname:"",t=window.location&&typeof window.
location.pathname=="string"?window.location.pathname:"";if(e==="challenges.cloudflare.com"||t.startsWith("/cdn-cgi/challenge-platform")||t.startsWith("/cdn-cgi/challenge"))return!0}catch{}return!1},Dn=()=>{if(G)return;if(Lr(document.title)){pt();return}const e=typeof document<"u"?document.documentElement:null;if(!(!e||typeof MutationObserver>"u"))try{const t=new MutationObserver(()=>{if(G){t.disconnect();return}(document.querySelector('script[src^="/cdn-cgi/challenge-platform"]')||document.querySelector(
'script[src*="challenges.cloudflare.com"]')||document.querySelector("#challenge-form")||document.querySelector("#challenge-stage")||document.querySelector("#challenge-runner")||Lr(document.title))&&(t.disconnect(),pt())});t.observe(e,{childList:!0,subtree:!0}),setTimeout(()=>{try{t.disconnect()}catch{}},5e3)}catch{}};Mn()?pt():Dn();let St;const Un=()=>(St||(St=(async()=>{try{if(typeof S>"u"||!S.runtime||!S.runtime.sendMessage)return"error";const e=window.location&&typeof window.location.hostname==
"string"?window.location.hostname:"";if(!e)return!1;const t=await S.runtime.sendMessage({action:"wblock:getBlockingState",host:e});return t&&t.state==="error"||!t||typeof t.disabled!="boolean"||typeof t.paused!="boolean"?"error":t.disabled||t.paused}catch(e){return console.warn("[wBlock] Failed to resolve combined blocking state:",e),"error"}})()),St);let mt;const Bn=e=>{if(e&&e.state==="error")return Promise.resolve(!0);const t=e&&typeof e.disabled=="boolean"&&typeof e.paused=="boolean"?e:e&&e.
payload;return t&&typeof t.disabled=="boolean"&&typeof t.paused=="boolean"?Promise.resolve(t.disabled||t.paused):Un()};(async()=>{if(window.adguard={contentScript:new kn},G)return;const e={type:ke.InitContentScript},t=S.runtime.sendMessage(e).catch(s=>({type:ke.InitContentScript,state:"error",error:String(s&&s.message?s.message:s)}));mt=t.then(Bn);const r=await t;if(!await mt&&!G&&r!=null&&r.payload){const s=r.payload;window.adguard.contentScript.applyConfiguration(s)}})().catch(e=>{Pr.error("Er\
ror in content script: ",e)}),(async()=>{try{if(G||await(mt||Promise.resolve(!1))||window.top!==window||!/^https?:/i.test(window.location.href)||typeof S>"u"||!S.runtime||!S.runtime.sendMessage)return;const e=await S.runtime.sendMessage({action:"wblock:getCleanURL",url:window.location.href});let t=e&&typeof e.cleanUrl=="string"?e.cleanUrl:"";if(!t||t===window.location.href){const r=new URL(window.location.href);let s=!1;for(const n of Array.from(r.searchParams.keys()))/^(utm_|fbclid$|gclid$|dclid$|gbraid$|wbraid$|msclkid$|mc_cid$|mc_eid$|igshid$|yclid$|_hsenc$|_hsmi$|mkt_tok$|vero_id$|oly_anon_id$|oly_enc_id$)/i.
test(n)&&(r.searchParams.delete(n),s=!0);s&&(t=r.href)}if(t&&t!==window.location.href){if(G)return;console.info("[wBlock] Removing tracking parameters:",window.location.href,"\u2192",t),typeof history<"u"&&typeof history.replaceState=="function"&&history.replaceState(history.state,"",t)}}catch(e){try{const t=new URL(window.location.href);let r=!1;for(const s of Array.from(t.searchParams.keys()))/^(utm_|fbclid$|gclid$|dclid$|gbraid$|wbraid$|msclkid$|mc_cid$|mc_eid$|igshid$|yclid$|_hsenc$|_hsmi$|mkt_tok$|vero_id$|oly_anon_id$|oly_enc_id$)/i.
test(s)&&(t.searchParams.delete(s),r=!0);if(r&&t.href!==window.location.href){if(G)return;console.info("[wBlock] Removing common tracking parameters:",window.location.href,"\u2192",t.href),typeof history<"u"&&typeof history.replaceState=="function"&&history.replaceState(history.state,"",t.href)}}catch{console.warn("[wBlock] URL cleanup fallback failed:",e)}}})()})(typeof browser>"u"?void 0:browser);
