/*! SafariExtension v4.3.0. Upstream (c) Adguard Software Ltd., GPL-3.0, https://github.com/AdguardTeam/SafariConverterLib/tree/master/Extension */
/*! Generated artifact — do not edit. Edit extension-src/content.js and run scripts/minify-extension-js.sh */
function _defineProperty2(S,y,E){return(y=_toPropertyKey(y))in S?Object.defineProperty(S,y,{value:E,enumerable:!0,configurable:!0,writable:!0}):S[y]=E,S}function _toPropertyKey(S){var y=_toPrimitive(S,"string");return typeof y=="symbol"?y:y+""}function _toPrimitive(S,y){if(typeof S!="object"||!S)return S;var E=S[Symbol.toPrimitive];if(E!==void 0){var Y=E.call(S,y||"default");if(typeof Y!="object")return Y;throw new TypeError("@@toPrimitive must return a primitive value.")}return(y==="string"?String:
Number)(S)}(function(S){"use strict";function y(e,t,r){return t in e?Object.defineProperty(e,t,{value:r,enumerable:!0,configurable:!0,writable:!0}):e[t]=r,e}const E={SELECTOR_LIST:"SelectorList",SELECTOR:"Selector",REGULAR_SELECTOR:"RegularSelector",EXTENDED_SELECTOR:"ExtendedSelector",ABSOLUTE_PSEUDO_CLASS:"AbsolutePseudoClass",RELATIVE_PSEUDO_CLASS:"RelativePseudoClass"};class Y{constructor(t){y(this,"children",[]),this.type=t}addChild(t){this.children.push(t)}}class Nr extends Y{constructor(t){
super(E.REGULAR_SELECTOR),this.value=t}}class $r extends Y{constructor(t){super(E.RELATIVE_PSEUDO_CLASS),this.name=t}}class kr extends Y{constructor(t){super(E.ABSOLUTE_PSEUDO_CLASS),y(this,"value",""),this.name=t}}const Rt="[",wt="]",Tt="(",vt=")",yt="{",Ot="}",p={SQUARE:{LEFT:Rt,RIGHT:wt},PARENTHESES:{LEFT:Tt,RIGHT:vt},CURLY:{LEFT:yt,RIGHT:Ot}},g="/",$="\\",D=" ",j=",",Me=".",pe=";",A=":",M="'",_='"',bt="^",At="$",q="=",ne="	",oe="\r",ie=`
`,le="\f",Ct=[D,ne,oe,ie,le],T="*",Ue="#",Be=Me,Se=D,ae=">",ce="+",ue="~",me=[Se,ae,ce,ue],Pt=[Rt,wt,Tt,vt,yt,Ot,g,$,pe,A,j,M,_,bt,At,T,Ue,Be,Se,ae,ce,ue,ne,oe,ie,le],Ir=[A,pe,M,_,$,D,ne,oe,ie,le],xe="contains",Ve="has-text",Ge="-abp-contains",Lt="matches-css",_t="matches-css-before",Nt="matches-css-after",$t="matches-attr",kt="matches-property",W="xpath",Fe="nth-ancestor",Dr=[xe,Ve,Ge],He="upward",U="remove",It="has",Dt="-abp-has",Ye=[It,Dt],We="is",Ke="not",Mt=[xe,Ve,Ge,Lt,_t,Nt,$t,kt,W,Fe,He],
Ut=[...Ye,We,Ke],Xe=[...Mt,...Ut],Mr=[Ke,We],ze=":scope",Bt={AFTER:"after",BACKDROP:"backdrop",BEFORE:"before",CUE:"cue",CUE_REGION:"cue-region",FIRST_LETTER:"first-letter",FIRST_LINE:"first-line",FILE_SELECTION_BUTTON:"file-selector-button",GRAMMAR_ERROR:"grammar-error",MARKER:"marker",PART:"part",PLACEHOLDER:"placeholder",SELECTION:"selection",SLOTTED:"slotted",SPELLING_ERROR:"spelling-error",TARGET_TEXT:"target-text"},xt="@",je="content",Q="true",Vt="global",ge="Selector should be defined",L={
NO_STYLE:"No style declaration found",NO_SELECTOR:`${ge} before style declaration in stylesheet`,INVALID_STYLE:"Invalid style declaration",UNCLOSED_STYLE:"Unclosed style declaration",NO_PROPERTY:"Missing style property in declaration",NO_VALUE:"Missing style value in declaration",NO_STYLE_OR_REMOVE:"Style should be declared or :remove() pseudo-class should used",NO_COMMENT:"Comments are not supported"},Gt="At-rules are not supported",K={INVALID_REMOVE:"Invalid :remove() pseudo-class in selector",
NO_TARGET_SELECTOR:`${ge} before :remove() pseudo-class`,MULTIPLE_USAGE:"Pseudo-class :remove() appears more than once in selector",INVALID_POSITION:"Pseudo-class :remove() should be at the end of selector"},Ur="Error while matching element",Ft=50,Br=/\[-(?:ext)-([a-z-_]+)=(["'])((?:(?=(\\?))\4.)*?)\2\]/g,xr="[-ext-",Vr=(e,t,r,s)=>{const n=new RegExp(`([^\\\\]|^)\\\\${r}`,"g"),o=s.replace(n,`$1${r}`);return`:${t}(${o})`},Gr=/\(:scope >/g,Fr="(>",Hr=/(:matches-css)-(before|after)\(/g,Yr=(e,t,r)=>`${t}${p.
PARENTHESES.LEFT}${r}${j}`,Wr=e=>{const t=e.replace(Br,Vr).replace(Gr,Fr).replace(Hr,Yr);if(t.includes(xr))throw new Error(`Invalid extended-css old syntax selector: '${e}'`);return t},Kr=e=>{const t=e.trim();return Wr(t)},C={MARK:"mark",WORD:"word"},qe=(e,t)=>{let r="";const s=[];return e.split("").forEach(o=>{if(t.includes(o)){r.length>0&&(s.push({type:C.WORD,value:r}),r=""),s.push({type:C.MARK,value:o});return}r+=o}),r.length>0&&s.push({type:C.WORD,value:r}),s},Xr=e=>{const t=Kr(e);return qe(
t,Pt)},zr=e=>qe(e,[...Pt,q]),Qe=e=>{const t=[];e.forEach(s=>t.push(s));const r=[];for(;t.length;){const s=t.pop();if(!s)throw new Error("Unable to make array flat");Array.isArray(s)?s.forEach(n=>t.push(n)):r.push(s)}return r.reverse()},J=e=>e[0],B=e=>e[e.length-1],Ht=e=>e[e.length-2],Re=(e,t,r)=>{const s=e[t];if(!s)throw new Error(r||`No array item found by index ${t}`);return s},Yt="At least one of Selector node children should be RegularSelector",we=e=>e?.type===E.SELECTOR_LIST,Z=e=>e?.type===
E.SELECTOR,O=e=>e?.type===E.REGULAR_SELECTOR,ee=e=>e.type===E.EXTENDED_SELECTOR,k=e=>e?.type===E.ABSOLUTE_PSEUDO_CLASS,x=e=>e?.type===E.RELATIVE_PSEUDO_CLASS,V=e=>{if(e===null)throw new Error("Ast node should be defined");if(!k(e)&&!x(e))throw new Error("Only AbsolutePseudoClass or RelativePseudoClass ast node can have a name");if(!e.name)throw new Error("Extended pseudo-class should have a name");return e.name},P=(e,t)=>{if(e===null)throw new Error("Ast node should be defined");if(!O(e)&&!k(e))
throw new Error("Only RegularSelector ot AbsolutePseudoClass ast node can have a value");if(!e.value)throw new Error(t||"Ast RegularSelector ot AbsolutePseudoClass node should have a value");return e.value},Wt=e=>e.filter(O),jr=(e,t)=>{const r=Wt(e),s=J(r);if(!s)throw new Error(t||Yt);return s},Kt=e=>{const t=Wt(e),r=B(t);if(!r)throw new Error(Yt);return r},Te=(e,t)=>{if(e.children.length!==1)throw new Error(t);const r=J(e.children);if(!r)throw new Error(t);return r},ve=e=>Te(e,"Extended selecto\
r should be specified"),Je=e=>{if(!x(e))throw new Error("Only RelativePseudoClass node can have relative SelectorList node as child");return Te(e,`Missing arg for :${V(e)}() pseudo-class`)},qr="i",Xt={COMMON:[p.PARENTHESES.LEFT,M,_,q,Me,A,D],CONTAINS:[p.PARENTHESES.LEFT,M,_]},Ze=e=>Xe.includes(e),et=e=>Mr.includes(e),zt=(e,t)=>!e||!t?!1:me.includes(t)||e===C.WORD||t===T||t===Ue||t===Be||t===A||t===M||t===_||t===p.SQUARE.LEFT,Qr=(e,t,r)=>{const s=B(e.extendedPseudoNamesStack);if(!s)throw new Error(
"Regexp pattern allowed only in arg of extended pseudo-class");if(Dr.includes(s))return Xt.CONTAINS.includes(t);if(t===g&&s!==W){const n=r?`in arg part: '${r}'`:"arg";throw new Error(`Invalid regexp pattern for :${s}() pseudo-class ${n}`)}return Xt.COMMON.includes(t)},de=(e,t)=>e===p.SQUARE.LEFT&&t!==$,Jr=e=>{var t;if(!e.isAttributeBracketsOpen)return!1;const r=e.attributeBuffer.split(D).join(""),s=zr(r),n=J(s),o=n?.type,i=n?.value;if(o===C.MARK&&i!==$)throw new Error(`'[${e.attributeBuffer}]' i\
s not a valid attribute due to '${i}' at start of it`);const l=B(s),c=l?.type,a=l?.value;if(a===q)throw new Error(`'[${e.attributeBuffer}]' is not a valid attribute due to '${q}'`);const f=s.findIndex(F=>F.type===C.MARK&&F.value===q),u=(t=Ht(s))===null||t===void 0?void 0:t.value;if(f===-1)return c===C.WORD?!0:u===$&&(a===_||a===M);const N=Re(s,f+1).value;if(!(N===M||N===_)){if(c===C.WORD)return!0;throw new Error(`'[${e.attributeBuffer}]' is not a valid attribute`)}return c===C.WORD&&a?.toLocaleLowerCase()===
qr?u===N:a===N},jt=e=>e?Ct.includes(e):!1,ye=e=>Mt.includes(e),qt=e=>Ut.includes(e),X=e=>e.pathToBufferNode.length===0?null:B(e.pathToBufferNode)||null,Zr=e=>e.pathToBufferNode.length<2?null:Ht(e.pathToBufferNode)||null,tt=e=>{const t=X(e);if(!t)throw new Error("No bufferNode found");if(!Z(t))throw new Error("Unsupported bufferNode type");const r=Kt(t.children);return e.pathToBufferNode.push(r),r},m=(e,t)=>{const r=X(e);if(r===null)throw new Error("No bufferNode to update");if(k(r))r.value+=t;else if(O(
r))r.value+=t,e.isAttributeBracketsOpen&&(e.attributeBuffer+=t);else throw new Error(`${r.type} node cannot be updated. Only RegularSelector and AbsolutePseudoClass are supported`)},es=e=>{const t=new Y(E.SELECTOR_LIST);e.ast=t,e.pathToBufferNode.push(t)},v=function(e,t){let r=arguments.length>2&&arguments[2]!==void 0?arguments[2]:"";const s=X(e);if(s===null)throw new Error("No buffer node");let n;t===E.REGULAR_SELECTOR?n=new Nr(r):t===E.ABSOLUTE_PSEUDO_CLASS?n=new kr(r):t===E.RELATIVE_PSEUDO_CLASS?
n=new $r(r):n=new Y(t),s.addChild(n),e.pathToBufferNode.push(n)},Oe=(e,t)=>{es(e),v(e,E.SELECTOR),v(e,E.REGULAR_SELECTOR,t)},be=function(e){let t=arguments.length>1&&arguments[1]!==void 0?arguments[1]:"";v(e,E.SELECTOR_LIST),v(e,E.SELECTOR),v(e,E.REGULAR_SELECTOR,t)},I=(e,t)=>{for(let s=e.pathToBufferNode.length-1;s>=0;s-=1){var r;if(((r=e.pathToBufferNode[s])===null||r===void 0?void 0:r.type)===t){e.pathToBufferNode=e.pathToBufferNode.slice(0,s+1);break}}},Qt=e=>{const t=X(e);if(t&&we(t)&&x(Zr(
e)))return t;I(e,E.SELECTOR);const r=X(e);if(!r)throw new Error("No SelectorNode, impossible to continue selector parsing by ExtendedCss");const s=B(r.children),n=s&&ee(s)&&e.standardPseudoBracketsStack.length===0,o=n&&J(s.children);let i=r;if(o){const l=n&&o.name,c=l&&qt(l),a=l&&ye(l),f=c&&e.extendedPseudoBracketsStack.length>0&&e.extendedPseudoBracketsStack.length===e.extendedPseudoNamesStack.length,u=a&&l===B(e.extendedPseudoNamesStack);(f||u)&&(e.pathToBufferNode.push(s),i=o)}else n?i=r:i=tt(
e);return e.pathToBufferNode.push(i),i},Jt=(e,t,r,s,n)=>{if(!s)throw new Error(`Invalid colon ':' at the end of selector: '${t}'`);if(Ze(s.toLowerCase())){if(Ye.includes(s)&&e.standardPseudoNamesStack.length>0)throw new Error(`Usage of :${s}() pseudo-class is not allowed inside regular pseudo: '${B(e.standardPseudoNamesStack)}'`);I(e,E.SELECTOR),v(e,E.EXTENDED_SELECTOR)}else{if(s.toLowerCase()===U)throw new Error(`${K.INVALID_REMOVE}: '${t}'`);m(e,r),n&&n===p.PARENTHESES.LEFT&&!e.isAttributeBracketsOpen&&
e.standardPseudoNamesStack.push(s)}},ts=`html ${T}`,rs=e=>e.children.some(t=>t.children.some(r=>ee(r))),ss=e=>e.children.map(r=>{const s=Te(r,"Ast Selector node should have RegularSelector node");return P(s)}).join(`${j}${D}`),Ae=(e,t)=>(e.children=t,e),rt=e=>{if(e===null)return!1;const t=ve(e),r=V(t);if(ye(r))return!1;const n=Je(t).children;return et(r)&&n.every(i=>{try{const l=Te(i,"Selector node should have RegularSelector");return O(l)}catch{return!1}})?!0:n.some(o=>o.children.some(i=>ee(i)?
rt(i):!1))},ns=(e,t)=>{if(!e)return null;const r=ve(e),s=Je(r);if(!rs(s)){const l=ss(s),c=V(r),a=`${A}${c}${p.PARENTHESES.LEFT}${l}${p.PARENTHESES.RIGHT}`;return t.value=`${P(t)}${a}`,null}const o=Zt(s),i=Ae(r,[o]);return Ae(e,[i])},os=(e,t)=>{t.value=`${P(t)}${D}${P(e)}`},is=e=>{const t=e.children,r=[];let s=0;for(;s<t.length;){const n=Re(t,s,"currentChild should be specified");if(s===0)r.push(n);else{const o=Kt(r);if(ee(n)){let i=null,l=rt(n);for(i=n;l;)i=ns(i,o),l=rt(i);if(i!==null){r.push(i);
const c=ve(i),a=V(c);P(o)===T&&et(a)&&(o.value=ts)}}else if(O(n)){const i=B(r)||null;O(i)&&os(n,o)}}s+=1}return Ae(e,r)},Zt=e=>Ae(e,e.children.map(t=>is(t))),ls=e=>Zt(e),as="body",er="No white space is allowed before or after extended pseudo-class name in selector",cs=e=>{const t=Xr(e),r={ast:null,pathToBufferNode:[],extendedPseudoNamesStack:[],extendedPseudoBracketsStack:[],standardPseudoNamesStack:[],standardPseudoBracketsStack:[],isAttributeBracketsOpen:!1,attributeBuffer:"",isRegexpOpen:!1,shouldOptimize:!1};
let s=0;for(;s<t.length;){const n=t[s];if(!n)break;const{type:o,value:i}=n,l=t[s+1],c=l?.type,a=l?.value,f=t[s+2],u=f?.value,h=t[s-1],N=h?.type,b=h?.value,F=t[s-2],Gn=F?.value;let d=X(r);switch(o){case C.WORD:if(d===null)Oe(r,i);else if(we(d))v(r,E.SELECTOR),v(r,E.REGULAR_SELECTOR,i);else if(O(d))m(r,i);else if(ee(d)){if(jt(a)&&u===p.PARENTHESES.LEFT)throw new Error(`${er}: '${e}'`);const H=i.toLowerCase();r.extendedPseudoNamesStack.push(H),ye(H)?v(r,E.ABSOLUTE_PSEUDO_CLASS,H):(v(r,E.RELATIVE_PSEUDO_CLASS,
H),et(H)&&(r.shouldOptimize=!0))}else k(d)?m(r,i):x(d)&&be(r,i);break;case C.MARK:switch(i){case j:if(!d||typeof d<"u"&&!a)throw new Error(`'${e}' is not a valid selector`);O(d)?r.isAttributeBracketsOpen?m(r,i):I(r,E.SELECTOR_LIST):k(d)?m(r,i):Z(d)&&I(r,E.SELECTOR_LIST);break;case D:if(O(d)&&!r.isAttributeBracketsOpen&&(d=Qt(r)),O(d)){if(!r.isAttributeBracketsOpen&&(b===A&&c===C.WORD||N===C.WORD&&a===p.PARENTHESES.LEFT))throw new Error(`'${e}' is not a valid selector`);(!a||zt(c,a)||r.isAttributeBracketsOpen)&&
m(r,i)}k(d)&&m(r,i),x(d)&&be(r),Z(d)&&zt(c,a)&&v(r,E.REGULAR_SELECTOR);break;case Se:case ae:case ce:case ue:case pe:case g:case $:case M:case _:case bt:case At:case p.CURLY.LEFT:case p.CURLY.RIGHT:case T:case Ue:case Be:case p.SQUARE.LEFT:if(me.includes(i)){if(d===null)throw new Error(`'${e}' is not a valid selector`);d=Qt(r)}if(d===null)Oe(r,i),de(i,b)&&(r.isAttributeBracketsOpen=!0);else if(O(d)){if(i===p.CURLY.LEFT&&!(r.isAttributeBracketsOpen||r.isRegexpOpen))throw new Error(`'${e}' is not \
a valid selector`);m(r,i),de(i,b)&&(r.isAttributeBracketsOpen=!0)}else k(d)?(m(r,i),i===g&&r.extendedPseudoNamesStack.length>0&&(b===g&&Gn===$?r.isRegexpOpen=!1:b&&b!==$&&(Qr(r,b,P(d))?r.isRegexpOpen=!r.isRegexpOpen:r.isRegexpOpen=!1))):x(d)?(be(r,i),de(i,b)&&(r.isAttributeBracketsOpen=!0)):Z(d)?me.includes(i)?v(r,E.REGULAR_SELECTOR,i):r.isRegexpOpen||(d=tt(r),m(r,i),de(i,b)&&(r.isAttributeBracketsOpen=!0)):we(d)&&(v(r,E.SELECTOR),v(r,E.REGULAR_SELECTOR,i),de(i,b)&&(r.isAttributeBracketsOpen=!0));
break;case p.SQUARE.RIGHT:if(O(d)){if(!r.isAttributeBracketsOpen&&b!==$)throw new Error(`'${e}' is not a valid selector due to '${i}' after '${P(d)}'`);Jr(r)&&(r.isAttributeBracketsOpen=!1,r.attributeBuffer=""),m(r,i)}k(d)&&m(r,i);break;case A:if(jt(a)&&u&&Xe.includes(u))throw new Error(`${er}: '${e}'`);if(d===null){if(a===W)Oe(r,as);else{if(a===He||a===Fe)throw new Error(`${ge} before :${a}() pseudo-class`);Oe(r,T)}d=X(r)}if(we(d)&&(v(r,E.SELECTOR),v(r,E.REGULAR_SELECTOR),d=X(r)),O(d)&&((b&&me.
includes(b)||b===j)&&m(r,T),Jt(r,e,i,a,u)),Z(d)){if(!a)throw new Error(`Invalid colon ':' at the end of selector: '${e}'`);if(Ze(a.toLowerCase()))v(r,E.EXTENDED_SELECTOR);else{if(a.toLowerCase()===U)throw new Error(`${K.INVALID_REMOVE}: '${e}'`);d=tt(r),Jt(r,e,i,c,u)}}if(k(d)){if(V(d)===W&&a&&Xe.includes(a)&&u===p.PARENTHESES.LEFT)throw new Error(`:xpath() pseudo-class should be the last in selector: '${e}'`);m(r,i)}if(x(d)){if(!a)throw new Error(`Invalid pseudo-class arg at the end of selector:\
 '${e}'`);be(r,T),Ze(a.toLowerCase())?(I(r,E.SELECTOR),v(r,E.EXTENDED_SELECTOR)):(m(r,i),u===p.PARENTHESES.LEFT&&r.standardPseudoNamesStack.push(a))}break;case p.PARENTHESES.LEFT:k(d)&&(V(d)!==W&&r.isRegexpOpen?m(r,i):(r.extendedPseudoBracketsStack.push(i),r.extendedPseudoBracketsStack.length>r.extendedPseudoNamesStack.length&&m(r,i))),O(d)&&(r.standardPseudoNamesStack.length>0&&(m(r,i),r.standardPseudoBracketsStack.push(i)),r.isAttributeBracketsOpen&&m(r,i)),x(d)&&r.extendedPseudoBracketsStack.
push(i);break;case p.PARENTHESES.RIGHT:if(k(d)&&(V(d)!==W&&r.isRegexpOpen?m(r,i):(r.extendedPseudoBracketsStack.pop(),V(d)!==W?(r.extendedPseudoNamesStack.pop(),r.extendedPseudoBracketsStack.length>r.extendedPseudoNamesStack.length?m(r,i):r.extendedPseudoBracketsStack.length>=0&&r.extendedPseudoNamesStack.length>=0&&I(r,E.SELECTOR)):r.extendedPseudoBracketsStack.length<r.extendedPseudoNamesStack.length?r.extendedPseudoNamesStack.pop():m(r,i))),O(d))if(r.isAttributeBracketsOpen)m(r,i);else if(r.standardPseudoNamesStack.
length>0&&r.standardPseudoBracketsStack.length>0){m(r,i),r.standardPseudoBracketsStack.pop();const H=r.standardPseudoNamesStack.pop();if(!H)throw new Error(`Parsing error. Invalid selector: ${e}`);if(Object.values(Bt).includes(H)&&a===A&&u&&Ye.includes(u))throw new Error(`Usage of :${u}() pseudo-class is not allowed after any regular pseudo-element: '${H}'`)}else r.extendedPseudoBracketsStack.pop(),r.extendedPseudoNamesStack.pop(),I(r,E.EXTENDED_SELECTOR),I(r,E.SELECTOR);Z(d)&&(r.extendedPseudoBracketsStack.
pop(),r.extendedPseudoNamesStack.pop(),I(r,E.EXTENDED_SELECTOR),I(r,E.SELECTOR)),x(d)&&r.extendedPseudoNamesStack.length>0&&r.extendedPseudoBracketsStack.length>0&&(r.extendedPseudoBracketsStack.pop(),r.extendedPseudoNamesStack.pop());break;case ie:case le:case oe:throw new Error(`'${e}' is not a valid selector`);case ne:if(O(d)&&r.isAttributeBracketsOpen)m(r,i);else throw new Error(`'${e}' is not a valid selector`)}break;default:throw new Error(`Unknown type of token: '${i}'`)}s+=1}if(r.ast===null)
throw new Error(`'${e}' is not a valid selector`);if(r.extendedPseudoNamesStack.length>0||r.extendedPseudoBracketsStack.length>0)throw new Error(`Unbalanced brackets for extended pseudo-class: '${B(r.extendedPseudoNamesStack)}'`);if(r.isAttributeBracketsOpen)throw new Error(`Unbalanced attribute brackets in selector: '${e}'`);return r.shouldOptimize?ls(r.ast):r.ast},st={MutationObserver:window.MutationObserver||window.WebKitMutationObserver};class us{constructor(){this.nativeNode=window.Node||Node}setGetter(){
var t;this.getter=(t=Object.getOwnPropertyDescriptor(this.nativeNode.prototype,"textContent"))===null||t===void 0?void 0:t.get}}const nt=new us,ds=e=>nt.getter?nt.getter.apply(e):e.textContent||"",tr=e=>{let t=e.tagName.toLowerCase();return t+=Array.from(e.attributes).map(r=>`[${r.name}="${e.getAttribute(r.name)}"]`).join(""),t},fs=e=>{if(!(e instanceof Element))throw new Error("Function received argument with wrong type");let t;t=e;const r=[];for(;t&&t.nodeType===Node.ELEMENT_NODE;){let s=t.nodeName.
toLowerCase();if(t.id&&typeof t.id=="string"){s+=`#${t.id}`,r.unshift(s);break}let n=t,o=1;for(;n.previousElementSibling;)n=n.previousElementSibling,n.nodeType===Node.ELEMENT_NODE&&n.nodeName.toLowerCase()===s&&(o+=1);o!==1&&(s+=`:nth-of-type(${o})`),r.unshift(s),t=t.parentElement}return r.join(" > ")},ot=e=>e instanceof HTMLElement,rr=(e,t)=>{const{parentElement:r}=e;if(!r)throw new Error(t||"Element does no have parent element");return r},Es=e=>typeof e=="object"&&e!==null&&"message"in e&&typeof e.
message=="string",hs=e=>{if(Es(e))return e;try{return new Error(JSON.stringify(e))}catch{return new Error(String(e))}},w=e=>hs(e).message,R={error:typeof console<"u"&&console.error&&console.error.bind?console.error.bind(window.console):console.error,info:typeof console<"u"&&console.info&&console.info.bind?console.info.bind(window.console):console.info},ps=(e,t)=>{const r=e.indexOf(t,e.length-t.length);return r>=0?e.substring(0,r):e},sr=(e,t,r)=>e&&e.split(t).join(r),Ss=e=>{if(e.startsWith(g)&&e.
endsWith(g))return new RegExp(e.slice(1,-1));const t=e.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(t)},ms=e=>{let t;switch(e){case void 0:t="undefined";break;case null:t="null";break;default:t=e.toString()}return t},gs=e=>{const t=Number(e);let r;if(!Number.isNaN(t))r=t;else switch(e){case"undefined":r=void 0;break;case"null":r=null;break;case"true":r=!0;break;case"false":r=!1;break;default:r=e}return r},nr=/\sVersion\/(\d{2}\.\d)(.+\s|\s)(Safari)\//.test(navigator.userAgent),Rs=e=>!(e.
includes("MSIE")||e.includes("Trident/")),ws=()=>Rs(navigator.userAgent),Ce={BACKGROUND:"background",BACKGROUND_IMAGE:"background-image",CONTENT:"content",OPACITY:"opacity"},or=".*",Ts=/^\s*\/.*\/[gmisuy]*\s*$/,vs=e=>e.replace(/^(["'])([\s\S]*)\1$/,"$2"),ir=e=>{if(!e.includes('url("')){const t=/url\((.*?)\)/g;return e.replace(t,'url("$1")')}return e},lr={regexpArg:e=>{const t=/(\^)?url(\\)?\\\((\w|\[\w)/g;return e.replace(t,'$1url$2\\(\\"?$3')},noneRegexpArg:ir},ys=e=>{const t=[".","+","?","$","\
{","}","(",")","[","]","\\","/"],r=new RegExp(`[${t.join("\\")}]`,"g");return e.replace(r,"\\$&")},Os=e=>{let t;return e.startsWith(g)&&e.endsWith(g)?(t=lr.regexpArg(e),t=t.slice(1,-1)):(t=lr.noneRegexpArg(e),t=t.replace(/\\([\\()[\]"])/g,"$1"),t=ys(t),t=sr(t,T,or)),new RegExp(t,"i")},bs=(e,t)=>{let r="";switch(e){case Ce.BACKGROUND:case Ce.BACKGROUND_IMAGE:r=ir(t);break;case Ce.CONTENT:r=vs(t);break;case Ce.OPACITY:r=nr?(Math.round(parseFloat(t)*100)/100).toString():t;break;default:r=t}return r},
As=(e,t,r)=>{const n=window.getComputedStyle(e,r).getPropertyValue(t);return bs(t,n)},it=(e,t)=>{const r=e.indexOf(t);let s,n;return r>-1?(s=e.substring(0,r).trim(),n=e.substring(r+1).trim()):s=e,{name:s,value:n}},Cs=(e,t)=>{const{name:r,value:s}=it(t,j);let n=r,o=s;if(Object.values(Bt).includes(r)||(n=null,o=t),!o)throw new Error(`Required style property argument part is missing in :${e}() arg: '${t}'`);return n&&(n=`${A}${A}${n}`),{regularPseudoElement:n,styleMatchArg:o}},Ps=e=>{const{pseudoName:t,
pseudoArg:r,domElement:s}=e,{regularPseudoElement:n,styleMatchArg:o}=Cs(t,r),{name:i,value:l}=it(o,A);if(!i||!l)throw new Error(`Required property name or value is missing in :${t}() arg: '${o}'`);let c;try{c=Os(l)}catch(f){throw R.error(w(f)),new Error(`Invalid argument of :${t}() pseudo-class: '${o}'`)}const a=As(s,i,n);return c&&c.test(a)},Ls=e=>!(e.includes(g)||!/^[\w-]+$/.test(e)),Pe=function(e){let t=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!1,r;if(e.length>1&&e.startsWith(_)&&
e.endsWith(_)&&(e=e.slice(1,-1)),e==="")throw new Error("Argument should be specified. Empty arg is invalid.");if(e.startsWith(g)&&e.endsWith(g))if(e.length>2)r=Ss(e);else throw new Error(`Invalid regexp: '${e}'`);else if(e.includes(T)){if(e===T&&!t)throw new Error(`Argument should be more specific than ${e}`);r=sr(e,T,or),r=new RegExp(r)}else{if(!Ls(e))throw new Error(`Invalid argument: '${e}'`);r=e}return r},ar=(e,t)=>{const{name:r,value:s}=it(t,q);if(!r)throw new Error(`Required attribute nam\
e is missing in :${e} arg: ${t}`);return{rawName:r,rawValue:s}},_s=e=>{const{pseudoName:t,pseudoArg:r,domElement:s}=e,n=s.attributes;if(n.length===0)return!1;const{rawName:o,rawValue:i}=ar(t,r);let l;try{l=Pe(o)}catch(f){const u=w(f);throw R.error(u),new SyntaxError(u)}let c=!1,a=0;for(;a<n.length&&!c;){const f=n[a];if(!f)break;const u=l instanceof RegExp?l.test(f.name):l===f.name;if(!i)c=u;else{let h;try{h=Pe(i)}catch(b){const F=w(b);throw R.error(F),new SyntaxError(F)}const N=h instanceof RegExp?
h.test(f.value):h===f.value;c=u&&N}a+=1}return c},Ns=e=>{e.length>1&&e.startsWith(_)&&e.endsWith(_)&&(e=e.slice(1,-1));const t=e.split(Me),r=[];let s="",n=!1,o=0;for(;o<t.length;){const l=Re(t,o,`Invalid pseudo-class arg: '${e}'`);l.startsWith(g)&&l.endsWith(g)&&l.length>2?r.push(l):l.startsWith(g)?(n=!0,s+=l):l.endsWith(g)?(n=!1,s+=`.${l}`,r.push(s),s=""):n?s+=l:r.push(l),o+=1}if(s.length>0)throw new Error(`Invalid regexp property pattern '${e}'`);return r.map(l=>{if(l.length===0)throw new Error(
`Empty pattern '${l}' is invalid in chain '${e}'`);let c;try{c=Pe(l,!0)}catch(a){throw R.error(w(a)),new Error(`Invalid property pattern '${l}' in property chain '${e}'`)}return c})},lt=function(e,t){let r=arguments.length>2&&arguments[2]!==void 0?arguments[2]:[];const s=J(t);if(t.length===1){let o;for(o in e)s instanceof RegExp?s.test(o)&&r.push({base:e,prop:o,value:e[o]}):s===o&&r.push({base:e,prop:s,value:e[o]});return r}if(s instanceof RegExp){const o=t.slice(1),i=[];for(const l in e)s.test(
l)&&i.push(l);i.forEach(l=>{var c;const a=(c=Object.getOwnPropertyDescriptor(e,l))===null||c===void 0?void 0:c.value;lt(a,o,r)})}if(e&&typeof s=="string"){var n;const o=(n=Object.getOwnPropertyDescriptor(e,s))===null||n===void 0?void 0:n.value;t=t.slice(1),o!==void 0&&lt(o,t,r)}return r},$s=e=>{const{pseudoName:t,pseudoArg:r,domElement:s}=e,{rawName:n,rawValue:o}=ar(t,r);if(n.includes("\\/")||n.includes("\\."))throw new Error(`Invalid :${t} name pattern: ${n}`);let i;try{i=Ns(n)}catch(f){const u=w(
f);throw R.error(u),new SyntaxError(u)}const l=lt(s,i);if(l.length===0)return!1;let c=!0;if(o){let f;try{f=Pe(o)}catch(u){const h=w(u);throw R.error(h),new SyntaxError(h)}if(f)for(let u=0;u<l.length;u+=1){var a;const h=(a=l[u])===null||a===void 0?void 0:a.value;if(f instanceof RegExp)c=f.test(ms(h));else{if(h==="null"||h==="undefined"){c=f===h;break}c=gs(f)===h}if(c)break}}return c},ks=e=>{const{pseudoName:t,pseudoArg:r,domElement:s}=e,n=ds(s);let o,i=r;if(i.startsWith(g)&&Ts.test(i)){const l=i.
lastIndexOf("/"),c=i.substring(l+1);i=i.substring(0,l+1).slice(1,-1).replace(/\\([\\"])/g,"$1");let a;try{a=new RegExp(i,c)}catch{throw new Error(`Invalid argument of :${t}() pseudo-class: ${r}`)}o=a.test(n)}else i=i.replace(/\\([\\()[\]"])/g,"$1"),o=n.includes(i);return o},Is=(e,t)=>{const r=Number(e);if(Number.isNaN(r)||r<1||r>=256)throw new Error(`Invalid argument of :${t} pseudo-class: '${e}'`);return r},Ds=(e,t,r)=>{let s=null,n=0;for(;n<t;){if(s=e.parentElement,!s)throw new Error(`Out of D\
OM: Argument of :${r}() pseudo-class is too big \u2014 '${t}'.`);e=s,n+=1}return s},Ms=e=>{let t;try{document.querySelectorAll(e),t=!0}catch{t=!1}return t},Us=(e,t,r)=>{let s;try{s=e(t)}catch(n){throw R.error(w(n)),new Error(r)}return s},Le=(e,t,r)=>`${Ur} ${e}, may be invalid :${t}() pseudo-class arg: '${r}'`,Bs=(e,t,r)=>{let s,n,o;switch(t){case xe:case Ve:case Ge:o=ks,s={pseudoName:t,pseudoArg:r,domElement:e},n=Le("text content",t,r);break;case Lt:case Nt:case _t:o=Ps,s={pseudoName:t,pseudoArg:r,
domElement:e},n=Le("style",t,r);break;case $t:o=_s,s={domElement:e,pseudoName:t,pseudoArg:r},n=Le("attributes",t,r);break;case kt:o=$s,s={domElement:e,pseudoName:t,pseudoArg:r},n=Le("properties",t,r);break;default:throw new Error(`Unknown absolute pseudo-class :${t}()`)}return Us(o,s,n)},_e={nthAncestor:(e,t,r)=>{const s=Is(t,r);return e.map(o=>{let i=null;try{i=Ds(o,s,r)}catch(l){R.error(w(l))}return i}).filter(ot)},xpath:(e,t)=>{const r=e.map(s=>{const n=[];let o;try{o=document.evaluate(t,s,null,
window.XPathResult.UNORDERED_NODE_ITERATOR_TYPE,null)}catch(l){throw R.error(w(l)),new Error(`Invalid argument of :xpath() pseudo-class: '${t}'`)}let i=o.iterateNext();for(;i;)ot(i)&&n.push(i),i=o.iterateNext();return n});return Qe(r)},upward:(e,t)=>{if(!Ms(t))throw new Error(`Invalid argument of :upward pseudo-class: '${t}'`);return e.map(s=>{const n=s.parentElement;return n?n.closest(t):null}).filter(ot)}},Ne=`${ze}${ae}`,at=`${ze}${Se}`,ct=(e,t)=>jr(e.children,`RegularSelector is missing for \
:${t}() pseudo-class`),xs=e=>{const{element:t,relativeSelectorList:r,pseudoName:s}=e;return r.children.every(n=>{const o=ct(n,s);let i="",l=null;const c=P(o);if(c.startsWith(ce)||c.startsWith(ue)){l=t.parentElement;const f=tr(t);i=`${Ne}${f}${c}`}else c===T?(l=t,i=`${at}${T}`):(i=`${at}${c}`,l=t);if(!l)throw new Error(`Selection by :${s}() pseudo-class is not possible`);let a;try{a=ke(n,l,i)}catch(f){throw R.error(w(f)),new Error(`Invalid selector for :${s}() pseudo-class: '${c}'`)}return a.length>
0})},Vs=e=>{const{element:t,relativeSelectorList:r,pseudoName:s}=e;return r.children.some(n=>{const o=ct(n,s),i=rr(t,`Selection by :${s}() pseudo-class is not possible`),l=`${Ne}${P(o)}`;let c;try{c=ke(n,i,l)}catch{return!1}return c.includes(t)})},Gs=e=>{const{element:t,relativeSelectorList:r,pseudoName:s}=e;return r.children.every(n=>{const o=ct(n,s),i=rr(t,`Selection by :${s}() pseudo-class is not possible`),l=`${Ne}${P(o)}`;let c;try{c=ke(n,i,l)}catch(a){throw R.error(w(a)),new Error(`Invalid\
 selector for :${s}() pseudo-class: '${P(o)}'`)}return!c.includes(t)})},$e=(e,t,r)=>{const s=r||P(e);let n=[];try{n=Array.from(t.querySelectorAll(s))}catch(o){throw new Error(`Error: unable to select by '${s}' \u2014 ${w(o)}`)}return n},Fs=(e,t)=>{let r=[];const s=ve(t),n=V(s);if(ye(n)){const o=P(s,`Missing arg for :${n}() pseudo-class`);if(n===Fe)r=_e.nthAncestor(e,o,n);else if(n===W){try{document.createExpression(o,null)}catch{throw new Error(`Invalid argument of :${n}() pseudo-class: '${o}'`)}
r=_e.xpath(e,o)}else n===He?Number.isNaN(Number(o))?r=_e.upward(e,o):r=_e.nthAncestor(e,o,n):r=e.filter(i=>Bs(i,n,o))}else if(qt(n)){const o=Je(s);let i;switch(n){case It:case Dt:i=l=>xs({element:l,relativeSelectorList:o,pseudoName:n});break;case We:i=l=>Vs({element:l,relativeSelectorList:o,pseudoName:n});break;case Ke:i=l=>Gs({element:l,relativeSelectorList:o,pseudoName:n});break;default:throw new Error(`Unknown relative pseudo-class: '${n}'`)}r=e.filter(i)}else throw new Error(`Unknown extende\
d pseudo-class: '${n}'`);return r},Hs=(e,t)=>{let r=[];const s=P(t);return s.startsWith(ae)?r=e.map(n=>{const o=`${ze}${s}`;return $e(t,n,o)}):s.startsWith(ce)||s.startsWith(ue)?r=e.map(n=>{const o=n.parentElement;if(!o)return[];const i=tr(n),l=`${Ne}${i}${s}`;return $e(t,o,l)}):r=e.map(n=>{const o=`${at}${P(t)}`;return $e(t,n,o)}),Qe(r)},ke=(e,t,r)=>{let s=[],n=0;for(;n<e.children.length;){const o=Re(e.children,n,"selectorNodeChild should be specified");n===0?s=$e(o,t,r):ee(o)?s=Fs(s,o):O(o)&&(s=
Hs(s,o)),n+=1}return s},cr=function(e){let t=arguments.length>1&&arguments[1]!==void 0?arguments[1]:document;const r=[];return e.children.forEach(n=>{r.push(...ke(n,t))}),[...new Set(Qe(r))]};class Ys{constructor(){this.astCache=new Map}saveAstToCache(t,r){this.astCache.set(t,r)}getAstFromCache(t){return this.astCache.get(t)||null}getSelectorAst(t){let r=this.getAstFromCache(t);return r||(r=cs(t)),this.saveAstToCache(t,r),r}querySelectorAll(t){const r=this.getSelectorAst(t);return cr(r)}}const ut=new Ys,
Ws=e=>{const t={};return e.forEach(r=>{const[s,n]=r;t[s]=n}),t},ur="debug",dt=e=>{const t=`${A}${U}${p.PARENTHESES.LEFT}${p.PARENTHESES.RIGHT}`,r=`${A}${U}${p.PARENTHESES.LEFT}`;let s,n=!1;const o=e.indexOf(t);if(o===0)throw new Error(`${K.NO_TARGET_SELECTOR}: '${e}'`);if(o>0){if(o!==e.lastIndexOf(t))throw new Error(`${K.MULTIPLE_USAGE}: '${e}'`);if(o+t.length<e.length)throw new Error(`${K.INVALID_POSITION}: '${e}'`);s=e.substring(0,o),n=!0}else{if(e.includes(r))throw new Error(`${K.INVALID_REMOVE}\
: '${e}'`);s=e}return{selector:s,stylesOfSelector:n?[{property:U,value:Q}]:[]}},dr=(e,t)=>{let r=e.trim();if(r.startsWith(xt))throw new Error(`${Gt}: '${r}'.`);let s;try{s=dt(r)}catch(l){throw R.error(w(l)),new Error(`${K.INVALID_REMOVE}: '${r}'`)}let n=[],o=!1,i;try{r=s.selector,n=s.stylesOfSelector,i=t.getSelectorAst(r),o=!0}catch{o=!1}return{success:o,selector:r,ast:i,stylesOfSelector:n}},fr=()=>new Map,ft=(e,t)=>{const{selector:r,ast:s,rawStyles:n}=t;if(!n)throw new Error(`No style declarati\
on for selector: '${r}'`);if(!s)throw new Error(`No ast parsed for selector: '${r}'`);const o=e.get(r);o?o.styles.push(...n):e.set(r,{ast:s,styles:n})},Ks=e=>e.some(t=>t.property===U&&t.value===Q),Xs=e=>{const t=e.find(r=>r.property===ur);return t?.value},zs=e=>{const{selector:t,ast:r,rawStyles:s}=e;if(!r)throw new Error(`AST should be parsed for selector: '${t}'`);if(!s)throw new Error(`Styles should be parsed for selector: '${t}'`);const n={selector:t,ast:r},o=Xs(s),i=Ks(s);let l=s;if(o&&(l=s.
filter(c=>c.property!==ur),(o===Q||o===Vt)&&(n.debug=o)),i){n.style={[U]:Q};const c=l.find(a=>a.property===je);c&&(n.style[je]=c.value)}else if(l.length>0){const c=l.map(f=>{const{property:u,value:h}=f;return[u,h]}),a=Ws(c);n.style=a}return n},Er=e=>{const t=[];return e.forEach((r,s)=>{const n=s,{ast:o,styles:i}=r;t.push(zs({selector:n,ast:o,rawStyles:i}))}),t},js=e=>{const t=e.trim();return qe(t,Ir)},fe={PROPERTY:"property",VALUE:"value"},Ie=e=>e.bufferValue!==""&&e.valueQuoteMark!==null,hr=e=>{
e.styles.push({property:e.bufferProperty.trim(),value:e.bufferValue.trim()}),e.bufferProperty="",e.bufferValue=""},qs=(e,t,r)=>{const{value:s}=r;switch(r.type){case C.WORD:if(e.bufferProperty.length>0)throw new Error(`Invalid style property in style block: '${t}'`);e.bufferProperty+=s;break;case C.MARK:if(s===A){if(e.bufferProperty.trim().length===0)throw new Error(`Missing style property before ':' in style block: '${t}'`);e.bufferProperty=e.bufferProperty.trim(),e.processing=fe.VALUE}else if(!Ct.
includes(s))throw new Error(`Invalid style declaration in style block: '${t}'`);break;default:throw new Error(`Unsupported style property character: '${s}' in style block: '${t}'`)}},Qs=(e,t,r)=>{const{value:s}=r;if(r.type===C.WORD)e.bufferValue+=s;else switch(s){case A:if(!Ie(e))throw new Error(`Invalid style value for property '${e.bufferProperty}' in style block: '${t}'`);e.bufferValue+=s;break;case pe:Ie(e)?e.bufferValue+=s:(hr(e),e.processing=fe.PROPERTY);break;case M:case _:e.valueQuoteMark===
null?e.valueQuoteMark=s:!e.bufferValue.endsWith($)&&e.valueQuoteMark===s&&(e.valueQuoteMark=null),e.bufferValue+=s;break;case $:if(!Ie(e))throw new Error(`Invalid style value for property '${e.bufferProperty}' in style block: '${t}'`);e.bufferValue+=s;break;case D:case ne:case oe:case ie:case le:e.bufferValue.length>0&&(e.bufferValue+=s);break;default:throw new Error(`Unknown style declaration token: '${s}'`)}},Js=e=>{const t=e.trim(),r=js(t),s={processing:fe.PROPERTY,styles:[],bufferProperty:"",
bufferValue:"",valueQuoteMark:null};let n=0;for(;n<r.length;){const o=r[n];if(!o)break;if(s.processing===fe.PROPERTY)qs(s,t,o);else if(s.processing===fe.VALUE)Qs(s,t,o);else throw new Error("Style declaration parsing failed");n+=1}if(Ie(s))throw new Error(`Unbalanced style declaration quotes in style block: '${t}'`);if(s.bufferProperty.length>0){if(s.bufferValue.length===0)throw new Error(`Missing style value for property '${s.bufferProperty}' in style block '${t}'`);hr(s)}if(s.styles.length===0)
throw new Error(L.NO_STYLE);return s.styles},Zs=e=>{const t=[];for(let r=0;r<e.length;r+=1)e[r]===p.CURLY.LEFT&&t.push(r);return t},en=(e,t)=>{var r;const s=e.trim();if(s.includes(`${g}${T}`)&&s.includes(`${T}${g}`))throw new Error(L.NO_COMMENT);const n=Zs(s);if(J(n)===0)throw new Error(ge);let o;if(n.length>0&&!s.includes(p.CURLY.RIGHT))throw new Error(`${L.NO_STYLE} OR ${L.UNCLOSED_STYLE}`);if(n.length===0||!s.includes(p.CURLY.RIGHT))try{if(o=dr(s,t),o.success){var i;if(((i=o.stylesOfSelector)===
null||i===void 0?void 0:i.length)===0)throw new Error(L.NO_STYLE_OR_REMOVE);return{selector:o.selector.trim(),ast:o.ast,rawStyles:o.stylesOfSelector}}else throw new Error("Invalid selector")}catch(u){throw new Error(w(u))}let l,c;const a={selector:""};for(let u=n.length-1;u>-1;u-=1){const h=n[u];if(!h)throw new Error(`Impossible to continue, no '{' to process for rule: '${s}'`);if(l=s.slice(0,h),c=s.slice(h+1,s.length-1),o=dr(l,t),o.success){var f;a.selector=o.selector.trim(),a.ast=o.ast,a.rawStyles=
o.stylesOfSelector;const N=Js(c);(f=a.rawStyles)===null||f===void 0||f.push(...N);break}else continue}if(((r=a.selector)===null||r===void 0?void 0:r.length)===0)throw new Error("Selector in not valid");return a},tn=(e,t)=>{const r=fr(),s=[];return[...new Set(e.map(o=>o.trim()))].forEach(o=>{try{ft(r,en(o,t))}catch(i){const l=w(i);s.push(`'${o}' - error: '${l}'`)}}),s.length>0&&R.info(`Invalid rules:
  ${s.join(`
  `)}`),Er(r)},pr=/[;}]/g,Sr=/[;:}]/g,mr=/\S/g,gr=e=>{e.rawRuleData={selector:""}},rn=(e,t)=>{let r=e.selectorBuffer.trim();if(r.startsWith(xt))throw new Error(`${Gt}: '${r}'.`);let s;try{s=dt(r)}catch(l){throw R.error(w(l)),new Error(`${K.INVALID_REMOVE}: '${r}'`)}if(e.nextIndex===-1){if(r===s.selector)throw new Error(`${L.NO_STYLE_OR_REMOVE}: '${e.cssToParse}'`);e.cssToParse=""}let n=[],o=!1,i;try{r=s.selector,n=s.stylesOfSelector,i=t.getSelectorAst(r),o=!0}catch{o=!1}return e.nextIndex>0&&(e.
cssToParse=e.cssToParse.slice(e.nextIndex)),{success:o,selector:r,ast:i,stylesOfSelector:n}},Rr=(e,t)=>{Sr.lastIndex=e.nextIndex;let r=Sr.exec(e.cssToParse);if(r===null)throw new Error(`${L.INVALID_STYLE}: '${e.cssToParse}'`);let s=r.index,n=r[0];if(n===p.CURLY.RIGHT){if(e.cssToParse.slice(e.nextIndex,s).trim().length===0){if(t.length===0)throw new Error(`${L.NO_STYLE}: '${e.cssToParse}'`)}else throw new Error(`${L.INVALID_STYLE}: '${e.cssToParse}'`);return s}if(n===A){const o=s;if(pr.lastIndex=
o,r=pr.exec(e.cssToParse),r===null)throw new Error(`${L.UNCLOSED_STYLE}: '${e.cssToParse}'`);s=r.index,n=r[0];const i=e.cssToParse.slice(e.nextIndex,o).trim();if(i.length===0)throw new Error(`${L.NO_PROPERTY}: '${e.cssToParse}'`);const l=e.cssToParse.slice(o+1,s).trim();if(l.length===0)throw new Error(`${L.NO_VALUE}: '${e.cssToParse}'`);if(t.push({property:i,value:l}),n===p.CURLY.RIGHT)return s}return e.cssToParse=e.cssToParse.slice(s+1),e.nextIndex=0,Rr(e,t)},sn=e=>{const t=[],r=Rr(e,t);mr.lastIndex=
r+1;const s=mr.exec(e.cssToParse);if(s===null)return e.cssToParse="",t;const n=s.index;return e.cssToParse=e.cssToParse.slice(n),t},nn=(e,t)=>{const r=e.trim();if(r.includes(`${g}${T}`)&&r.includes(`${T}${g}`))throw new Error(`${L.NO_COMMENT} in stylesheet: '${r}'`);const s={isSelector:!0,nextIndex:0,cssToParse:r,selectorBuffer:"",rawRuleData:{selector:""}},n=fr();let o;for(;s.cssToParse;)if(s.isSelector){if(s.nextIndex=s.cssToParse.indexOf(p.CURLY.LEFT),s.selectorBuffer.length===0&&s.nextIndex===
0)throw new Error(`${L.NO_SELECTOR}: '${s.cssToParse}'`);s.nextIndex===-1?s.selectorBuffer=s.cssToParse:s.selectorBuffer+=s.cssToParse.slice(0,s.nextIndex),o=rn(s,t),o.success?(s.rawRuleData.selector=o.selector.trim(),s.rawRuleData.ast=o.ast,s.rawRuleData.rawStyles=o.stylesOfSelector,s.isSelector=!1,s.nextIndex===-1?(ft(n,s.rawRuleData),gr(s)):(s.nextIndex=1,s.selectorBuffer="")):(s.selectorBuffer+=p.CURLY.LEFT,s.cssToParse=s.cssToParse.slice(1))}else{var i;const l=sn(s);(i=s.rawRuleData.rawStyles)===
null||i===void 0||i.push(...l),ft(n,s.rawRuleData),s.nextIndex=0,gr(s),s.isSelector=!0}return Er(n)},Et=e=>typeof e=="number"&&!Number.isNaN(e);class Ee{constructor(t){this.callback=t,this.executeCallback=this.executeCallback.bind(this)}executeCallback(){this.lastRunTime=performance.now(),Et(this.timerId)&&(clearTimeout(this.timerId),delete this.timerId),this.callback()}run(){if(!Et(this.timerId)){if(Et(this.lastRunTime)){const t=performance.now()-this.lastRunTime;if(t<Ee.THROTTLE_DELAY_MS){this.
timerId=window.setTimeout(this.executeCallback,Ee.THROTTLE_DELAY_MS-t);return}}this.timerId=window.setTimeout(this.executeCallback)}}}y(Ee,"THROTTLE_DELAY_MS",150);const on=10,ln=["mouseover","mouseleave","mouseenter","mouseout"],wr=["keydown","keypress","keyup","auxclick","click","contextmenu","dblclick","mousedown","mouseenter","mouseleave","mousemove","mouseover","mouseout","mouseup","pointerlockchange","pointerlockerror","select","wheel"],an=["wheel"];class cn{constructor(){y(this,"getLastEv\
entType",()=>this.lastEventType),y(this,"getTimeSinceLastEvent",()=>this.lastEventTime?Date.now()-this.lastEventTime:null),this.trackedEvents=nr?wr.filter(t=>!an.includes(t)):wr,this.trackedEvents.forEach(t=>{document.documentElement.addEventListener(t,this.trackEvent,!0)})}trackEvent(t){this.lastEventType=t.type,this.lastEventTime=Date.now()}isIgnoredEventType(){const t=this.getLastEventType(),r=this.getTimeSinceLastEvent();return!!t&&ln.includes(t)&&!!r&&r<on}stopTracking(){this.trackedEvents.
forEach(t=>{document.documentElement.removeEventListener(t,this.trackEvent,!0)})}}function un(e){return!e.some(t=>t.type!=="attributes")}function dn(e){if(e.isDomObserved)return;e.isDomObserved=!0;const t=new cn;e.eventTracker=t,e.domMutationObserver=new st.MutationObserver(r=>{!r||r.length===0||t.isIgnoredEventType()&&un(r)||e.scheduler.run()}),e.domMutationObserver.observe(document,{childList:!0,subtree:!0,attributes:!0,attributeFilter:["id","class"]})}function Tr(e){e.isDomObserved&&(e.isDomObserved=
!1,e.domMutationObserver&&e.domMutationObserver.disconnect(),e.eventTracker&&e.eventTracker.stopTracking())}const fn=/^("|')adguard.+?/,En=(e,t)=>{const{node:r}=t;t.removed=!0;const s=fs(r),n=e.removalsStatistic[s]||0;if(n>Ft){R.error(`ExtendedCss: infinite loop protection for selector: '${s}'`);return}r.parentElement&&(r.parentElement.removeChild(r),e.removalsStatistic[s]=n+1)},vr=(e,t)=>{e instanceof HTMLElement&&Object.keys(t).forEach(r=>{if(typeof e.style.getPropertyValue(r.toString())<"u"){
let s=t[r];if(!s||r===je&&s.match(fn))return;s=ps(s.trim(),"!important").trim(),e.style.setProperty(r,s,"important")}})},hn=e=>"node"in e&&"rules"in e&&e.rules instanceof Array,pn=e=>"node"in e&&"originalStyle"in e&&"rules"in e&&e.rules instanceof Array,yr=(e,t)=>{if(t.protectionObserver)return;let r;if(e.beforeStyleApplied){if(!hn(t))throw new Error("Returned IAffectedElement should have 'node' and 'rules' properties");if(r=e.beforeStyleApplied(t),!r)throw new Error("Callback 'beforeStyleApplie\
d' should return IAffectedElement")}else r=t;if(!pn(r))throw new Error("Returned IAffectedElement should have 'node' and 'rules' properties");const{node:s,rules:n}=r;for(let o=0;o<n.length;o+=1){const i=n[o],l=i?.selector,c=i?.style,a=i?.debug;if(c){if(c[U]===Q){En(e,r);return}vr(s,c)}else if(!a)throw new Error(`No style declaration in rule for selector: '${l}'`)}},Or=e=>{e.protectionObserver&&e.protectionObserver.disconnect(),e.node.style.cssText=e.originalStyle};class Sn{constructor(t){this.styleProtectionCount=
0,this.observer=new st.MutationObserver(r=>{r.length&&(this.styleProtectionCount+=1,t(r,this))})}observe(t,r){this.styleProtectionCount<Ft?this.observer.observe(t,r):R.error("ExtendedCss: infinite loop protection for style")}disconnect(){this.observer.disconnect()}}const br={attributes:!0,attributeOldValue:!0,attributeFilter:["style"]},mn=e=>(r,s)=>{if(!r[0])return;const{target:n}=r[0];s.disconnect(),e.forEach(o=>{vr(n,o)}),s.observe(n,br)},gn=(e,t)=>{if(!st.MutationObserver)return null;const r=[];
t.forEach(n=>{const{style:o}=n;o&&r.push(o)});const s=new Sn(mn(r));return s.observe(e,br),s},Rn=4;class wn{constructor(){this.appliesTimings=[],this.appliesCount=0,this.timingsSum=0,this.meanTiming=0,this.squaredSum=0,this.standardDeviation=0}push(t){this.appliesTimings.push(t),this.appliesCount+=1,this.timingsSum+=t,this.meanTiming=this.timingsSum/this.appliesCount,this.squaredSum+=t*t,this.standardDeviation=Math.sqrt(this.squaredSum/this.appliesCount-Math.pow(this.meanTiming,2))}}const he=e=>Number(
e.toFixed(Rn)),Tn=e=>({appliesTimings:e.appliesTimings.map(t=>he(t)),appliesCount:he(e.appliesCount),timingsSum:he(e.timingsSum),meanTiming:he(e.meanTiming),standardDeviation:he(e.standardDeviation)}),vn=e=>{if(e.areTimingsPrinted)return;e.areTimingsPrinted=!0;const t={};e.parsedRules.forEach(r=>{if(r.timingStats){const{selector:s,style:n,debug:o,matchedElements:i}=r;if(!n&&!o)throw new Error(`Rule should have style declaration for selector: '${s}'`);const l={selectorParsed:s,timings:Tn(r.timingStats)};
n&&n[U]===Q?l.removed=!0:(l.styleApplied=n||null,l.matchedElements=i),t[s]=l}}),Object.keys(t).length!==0&&R.info(`[ExtendedCss] Timings in milliseconds for %o:
%o`,window.location.href,t)},yn=(e,t)=>e.find(r=>r.node===t),On=(e,t)=>{const r=!!t.debug||e.debug;let s;r&&(s=performance.now());const{ast:n}=t,o=[];try{o.push(...cr(n))}catch(i){e.debug&&R.error(w(i))}if(o.forEach(i=>{let l=yn(e.affectedElements,i);if(l)l.rules.push(t),yr(e,l);else{const c=i.style.cssText;l={node:i,rules:[t],originalStyle:c,protectionObserver:null},yr(e,l),e.affectedElements.push(l)}}),r&&s){const i=performance.now()-s;t.timingStats||(t.timingStats=new wn),t.timingStats.push(i)}
return o},Ar=e=>{const t=[];Tr(e),e.parsedRules.forEach(s=>{const n=On(e,s);Array.prototype.push.apply(t,n),s.debug&&(s.matchedElements=n)});let r=e.affectedElements.length;for(;r;){const s=e.affectedElements[r-1];if(!s)break;t.includes(s.node)?s.removed||s.protectionObserver||(s.protectionObserver=gn(s.node,s.rules)):(Or(s),e.affectedElements.splice(r-1,1)),r-=1}dn(e),vn(e)};class ht{constructor(t){if(!t)throw new Error("ExtendedCss configuration should be provided.");if(this.applyRulesCallbackListener=
this.applyRulesCallbackListener.bind(this),this.context={beforeStyleApplied:t.beforeStyleApplied,debug:!1,affectedElements:[],isDomObserved:!1,removalsStatistic:{},parsedRules:[],scheduler:new Ee(this.applyRulesCallbackListener)},!ws()){R.error("Browser is not supported by ExtendedCss");return}if(!t.styleSheet&&!t.cssRules)throw new Error("ExtendedCss configuration should have 'styleSheet' or 'cssRules' defined.");if(t.styleSheet)try{this.context.parsedRules.push(...nn(t.styleSheet,ut))}catch(r){
throw new Error(`Pass the rules as configuration.cssRules since configuration.styleSheet cannot be parsed because of: '${w(r)}'`)}if(t.cssRules&&this.context.parsedRules.push(...tn(t.cssRules,ut)),this.context.debug=t.debug||this.context.parsedRules.some(r=>r.debug===Vt),this.context.beforeStyleApplied&&typeof this.context.beforeStyleApplied!="function")throw new Error(`Invalid configuration. Type of 'beforeStyleApplied' should be a function, received: '${typeof this.context.beforeStyleApplied}'`)}applyRulesCallbackListener(){
Ar(this.context)}init(){nt.setGetter()}apply(){Ar(this.context),document.readyState!=="complete"&&document.addEventListener("DOMContentLoaded",this.applyRulesCallbackListener,!1)}dispose(){Tr(this.context),this.context.affectedElements.forEach(t=>{Or(t)}),document.removeEventListener("DOMContentLoaded",this.applyRulesCallbackListener,!1)}getAffectedElements(){return this.context.affectedElements}static query(t){let r=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!0;if(typeof t!="string")
throw new Error("Selector should be defined as a string.");const s=performance.now();try{return ut.querySelectorAll(t)}finally{const n=performance.now();r||R.info(`[ExtendedCss] Elapsed: ${Math.round((n-s)*1e3)} \u03BCs.`)}}static validate(t){try{const{selector:r}=dt(t);return ht.query(r),{ok:!0,error:null}}catch(r){return{ok:!1,error:`Error: Invalid selector: '${t}' -- ${w(r)}`}}}}var z;(function(e){e[e.Debug=2]="Debug",e[e.Info=1]="Info",e[e.Error=0]="Error"})(z||(z={}));const bn=()=>`[${new Date().
toISOString()}]`,An=e=>{if(e instanceof Error)return e.stack||e.message||String(e);if(typeof e=="string")return e;try{return JSON.stringify(e)}catch{return String(e)}},pt=(e,t)=>[bn(),e,...t.map(An)].join(" ");class Cn{constructor(t,r){_defineProperty2(this,"prefix","[Safari Extension]"),_defineProperty2(this,"loggingLevel",z.Info),this.prefix=t,this.loggingLevel=r}get level(){return this.loggingLevel}set level(t){this.loggingLevel=t}debug(){if(this.loggingLevel>=z.Debug){for(var t=arguments.length,
r=new Array(t),s=0;s<t;s++)r[s]=arguments[s];console.debug(pt(this.prefix,r))}}info(){if(this.loggingLevel>=z.Info){for(var t=arguments.length,r=new Array(t),s=0;s<t;s++)r[s]=arguments[s];console.info(pt(this.prefix,r))}}error(){if(this.loggingLevel>=z.Error){for(var t=arguments.length,r=new Array(t),s=0;s<t;s++)r[s]=arguments[s];console.error(pt(this.prefix,r))}}}class Pn{constructor(){_defineProperty2(this,"level",z.Debug)}debug(){}info(){}error(){}}let te=new Pn;class Ln{get level(){return te.
level}set level(t){te.level=t}debug(){te.debug(...arguments)}info(){te.info(...arguments)}error(){te.error(...arguments)}}const _n=e=>{te=e},re=new Ln,Hn="4.3.0",Cr=e=>e.map(t=>t.trim()).filter(t=>t.length>0).map(t=>t.at(-1)!=="}"?`${t} {display:none!important;}`:t),Nn=e=>{const t=document.createElement("script");return t.setAttribute("type","text/javascript"),t.textContent=e,(document.head||document.documentElement).appendChild(t),t.parentNode?(t.parentNode.removeChild(t),!1):!0},$n=e=>{const t=new Blob(
[e],{type:"text/javascript"}),r=URL.createObjectURL(t),s=document.createElement("script");return s.src=r,(document.head||document.documentElement).appendChild(s),URL.revokeObjectURL(r),s.parentNode?(s.parentNode.removeChild(s),!1):!0},Pr=function(){let e=arguments.length>0&&arguments[0]!==void 0?arguments[0]:[];e.unshift("( function () { try {"),e.push(";document.currentScript && document.currentScript.remove();"),e.push("} catch (ex) { console.error('Error executing AG js: ' + ex); } })();");const t=e.
join(`\r
`);Nn(t)||$n(t)||console.warn("[wBlock] Page script injection was blocked; continuing without page-context scripts.")},kn=e=>{const{MutationObserver:t}=window;if(!t)return;new t(s=>{for(let n=0;n<s.length;n+=1){const o=s[n];if(e.hasAttribute("mod")&&e.getAttribute("mod")==="inner"){e.removeAttribute("mod");break}e.setAttribute("mod","inner");let i=!1;if(o.removedNodes.length>0)for(let l=0;l<o.removedNodes.length;l+=1)i=!0,e.appendChild(o.removedNodes[l]);else o.oldValue&&(i=!0,e.textContent=o.oldValue);
i||e.removeAttribute("mod")}}).observe(e,{childList:!0,characterData:!0,subtree:!0,characterDataOldValue:!0})};class In{applyConfiguration(t){let r=arguments.length>1&&arguments[1]!==void 0?arguments[1]:!1;this.insertCss(t.css),this.insertExtendedCss(t.extendedCss),this.runScriptlets(t.scriptlets,r),this.runScripts(t.js)}insertCss(t){if(!(!t||!t.length))try{const r=document.createElement("style");if(r.setAttribute("type","text/css"),(document.head||document.documentElement).appendChild(r),r.sheet){
const s=Cr(t);for(const n of s)r.sheet.insertRule(n)}kn(r)}catch(r){re.error("Failed to insert CSS",r)}}insertExtendedCss(t){if(!(!t||!t.length))try{const r=Cr(t);new ht({cssRules:r}).apply()}catch(r){re.error("Failed to insert extended CSS",r)}}runScripts(t){!t||t.length===0||Pr(t)}runScriptlets(t){if(!(!t||!t.length))for(const r of t){if(!r||typeof r.code!="string"||!r.code){re.error("Missing precompiled scriptlet source",r&&r.name);continue}Pr([r.code])}}}function Dn(){let e=arguments.length>
0&&arguments[0]!==void 0?arguments[0]:3e3;const t={cancelDispatch:()=>{},disarm:()=>{}},r=[{name:"DOMContentLoaded",options:{bubbles:!0,cancelable:!1},target:document,shouldListen:document.readyState==="loading"},{name:"load",options:{bubbles:!1,cancelable:!1},target:window,shouldListen:document.readyState!=="complete"}].filter(f=>f.shouldListen);if(r.length===0)return t;let s=!0;const n=[];r.forEach(f=>{const u={name:f.name,options:f.options,intercepted:!1,target:f.target,listener:h=>{s&&(h.stopImmediatePropagation(),
u.intercepted=!0,re.debug("Event has been intercepted:",f.name))}};n.push(u),u.target.addEventListener(f.name,u.listener,{capture:!0})});let o=!1;const i=f=>{o||(o=!0,n.forEach(u=>{if(u.target.removeEventListener(u.name,u.listener,{capture:!0}),u.intercepted){const h=new Event(u.name,u.options);u.target.dispatchEvent(h);const N=u.target===document?"document":"window";re.debug(`${u.name} event re-dispatched due to ${f} on ${N}.`)}else re.debug(`Interceptor for ${u.name} removed due to ${f}.`)}))},
l=setTimeout(()=>{i("timeout")},e),c=()=>{clearTimeout(l),i("response received")};return{cancelDispatch:c,disarm:()=>{s=!1,c()}}}var De;(function(e){e.InitContentScript="InitContentScript"})(De||(De={}));const Lr=new Cn("[wBlock Scripts]",z.Error);if(_n(Lr),!S||!S.runtime||!S.runtime.sendMessage)return;const se=Dn(3e3);let G=!1;const Mn=/just a moment|verifying you are human|attention required|enable cookies/i,_r=e=>Mn.test(e||""),St=()=>{G||(G=!0,se&&se.disarm(),console.info("[wBlock] Cloudflar\
e challenge context detected \u2014 skipping content script."))},Un=()=>{try{const e=window.location&&typeof window.location.hostname=="string"?window.location.hostname:"",t=window.location&&typeof window.location.pathname=="string"?window.location.pathname:"";if(e==="challenges.cloudflare.com"||t.startsWith("/cdn-cgi/challenge-platform")||t.startsWith("/cdn-cgi/challenge"))return!0}catch{}return!1},Bn=()=>{if(G)return;if(_r(document.title)){St();return}const e=typeof document<"u"?document.documentElement:
null;if(!(!e||typeof MutationObserver>"u"))try{const t=new MutationObserver(()=>{if(G){t.disconnect();return}(document.querySelector('script[src^="/cdn-cgi/challenge-platform"]')||document.querySelector('script[src*="challenges.cloudflare.com"]')||document.querySelector("#challenge-form")||document.querySelector("#challenge-stage")||document.querySelector("#challenge-runner")||_r(document.title))&&(t.disconnect(),St())});t.observe(e,{childList:!0,subtree:!0}),setTimeout(()=>{try{t.disconnect()}catch{}},
5e3)}catch{}};Un()?St():Bn();let mt;const xn=()=>(mt||(mt=(async()=>{try{if(typeof S>"u"||!S.runtime||!S.runtime.sendMessage)return"error";const e=window.location&&typeof window.location.hostname=="string"?window.location.hostname:"";if(!e)return!1;const t=await S.runtime.sendMessage({action:"wblock:getBlockingState",host:e});return t&&t.state==="error"||!t||typeof t.disabled!="boolean"||typeof t.paused!="boolean"?"error":t.disabled||t.paused}catch(e){return console.warn("[wBlock] Failed to reso\
lve combined blocking state:",e),"error"}})()),mt);let gt;const Vn=e=>{if(e&&e.state==="error")return Promise.resolve(!0);const t=e&&typeof e.disabled=="boolean"&&typeof e.paused=="boolean"?e:e&&e.payload;return t&&typeof t.disabled=="boolean"&&typeof t.paused=="boolean"?Promise.resolve(t.disabled||t.paused):xn()};(async()=>{if(window.adguard={contentScript:new In},G){se.disarm();return}const e={type:De.InitContentScript},t=S.runtime.sendMessage(e).catch(s=>({type:De.InitContentScript,state:"err\
or",error:String(s&&s.message?s.message:s)}));gt=t.then(Vn);const r=await t;if(await gt){se.disarm();return}if(G){se.disarm();return}if(r!=null&&r.payload){const s=r.payload;window.adguard.contentScript.applyConfiguration(s)}se.cancelDispatch()})().catch(e=>{Lr.error("Error in content script: ",e)}),(async()=>{try{if(G||await(gt||Promise.resolve(!1))||window.top!==window||!/^https?:/i.test(window.location.href)||typeof S>"u"||!S.runtime||!S.runtime.sendMessage)return;const e=await S.runtime.sendMessage(
{action:"wblock:getCleanURL",url:window.location.href});let t=e&&typeof e.cleanUrl=="string"?e.cleanUrl:"";if(!t||t===window.location.href){const r=new URL(window.location.href);let s=!1;for(const n of Array.from(r.searchParams.keys()))/^(utm_|fbclid$|gclid$|dclid$|gbraid$|wbraid$|msclkid$|mc_cid$|mc_eid$|igshid$|yclid$|_hsenc$|_hsmi$|mkt_tok$|vero_id$|oly_anon_id$|oly_enc_id$)/i.test(n)&&(r.searchParams.delete(n),s=!0);s&&(t=r.href)}if(t&&t!==window.location.href){if(G)return;console.info("[wBl\
ock] Removing tracking parameters:",window.location.href,"\u2192",t),window.location.replace(t)}}catch(e){try{const t=new URL(window.location.href);let r=!1;for(const s of Array.from(t.searchParams.keys()))/^(utm_|fbclid$|gclid$|dclid$|gbraid$|wbraid$|msclkid$|mc_cid$|mc_eid$|igshid$|yclid$|_hsenc$|_hsmi$|mkt_tok$|vero_id$|oly_anon_id$|oly_enc_id$)/i.test(s)&&(t.searchParams.delete(s),r=!0);if(r&&t.href!==window.location.href){if(G)return;console.info("[wBlock] Removing common tracking parameter\
s:",window.location.href,"\u2192",t.href),window.location.replace(t.href)}}catch{console.warn("[wBlock] URL cleanup fallback failed:",e)}}})()})(typeof browser>"u"?void 0:browser);
